Repository babel/babel, pull requests merged in 2018-04, with the labels that each got.

#7655 Remove setting BABEL_ENV to test by default in makefile
  Makefile
Labels: PR: Bug Fix :bug:

#7662 Fix typo in ast spec
  packages/babylon/ast/spec.md
Labels: PR: Docs :memo:, pkg: babylon

#7663 Add missing exponential operators to ast spec
  packages/babylon/ast/spec.md
Labels: PR: Docs :memo:, pkg: babylon

#7668 OptionalMemberExpression properties are not referenced
  packages/babel-plugin-proposal-optional-chaining/package.json
  packages/babel-plugin-proposal-optional-chaining/test/fixtures/regression/7642/input.js
  packages/babel-plugin-proposal-optional-chaining/test/fixtures/regression/7642/options.json
  packages/babel-plugin-proposal-optional-chaining/test/fixtures/regression/7642/output.js
  packages/babel-types/src/validators/isReferenced.js
Labels: PR: Bug Fix :bug:

#7679 Add option to overwrite failing output fixtures
  packages/babel-helper-transform-fixture-test-runner/src/index.js
Labels: PR: New Feature :rocket:

#7681 Cleanup object super traversal
  packages/babel-plugin-transform-object-super/src/index.js
Labels: PR: Polish :nail_care:

#7685 Make babel-types type checking functions 36% faster
  packages/babel-traverse/src/path/index.js
  packages/babel-types/scripts/generators/generateValidators.js
  packages/babel-types/src/validators/generated/index.js
Labels: area: perf, pkg: types

#7435 Fix function name computation for literal values
  packages/babel-helper-function-name/src/index.js
  packages/babel-plugin-transform-function-name/test/fixtures/issues/7199/input.js
  packages/babel-plugin-transform-function-name/test/fixtures/issues/7199/options.json
  packages/babel-plugin-transform-function-name/test/fixtures/issues/7199/output.js
Labels: PR: Bug Fix :bug:

#7704 Use yarn provided by circle
  .circleci/config.yml
Labels: PR: Internal :house:

#7708 ESLint: Ignore lerna.json and .git
  .eslintignore
Labels: PR: Internal :house:

#7706 Fix literal type annotation argument number
  packages/babel-types/README.md
  packages/babel-types/src/definitions/flow.js
Labels: pkg: types

#7714 Use new isInStrictMode
  packages/babel-helper-replace-supers/src/index.js
  packages/babel-plugin-transform-classes/test/fixtures/regression/5769/output.js
Labels: PR: Polish :nail_care:

#7549 Migrate `babel-cli` and `babel-generator` tests to use jest-expect
  packages/babel-cli/test/index.js
  packages/babel-core/test/config-chain.js
  packages/babel-generator/test/index.js
  packages/babel-plugin-proposal-decorators/test/fixtures/class-static-properties/properties-without-initializer/exec.js
  packages/babel-plugin-proposal-logical-assignment-operators/test/fixtures/logical-assignment/null-coalescing/exec.js
  packages/babel-plugin-proposal-logical-assignment-operators/test/fixtures/logical-assignment/null-coalescing/input.js
  packages/babel-plugin-proposal-logical-assignment-operators/test/fixtures/logical-assignment/null-coalescing/output.js
  packages/babel-preset-es2015/test/fixtures/traceur/Classes/ExtendStrange.js
Labels: PR: Internal :house:, area: tests

#7713 Add slack links to CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: PR: Docs :memo:

#7691 Fix super nested class bugs
  packages/babel-helper-replace-supers/src/index.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/nested-class/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/nested-class/super-call-in-key/exec.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/nested-class/super-call-in-key/input.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/nested-class/super-call-in-key/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/nested-class/super-property-in-key/exec.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/nested-class/super-property-in-key/input.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/nested-class/super-property-in-key/output.js
  packages/babel-plugin-transform-classes/src/transformClass.js
  packages/babel-plugin-transform-classes/test/fixtures/regression/5769/input.js
  packages/babel-plugin-transform-classes/test/fixtures/regression/5769/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-class-super-call-in-key/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-class-super-call-in-key/input.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-class-super-call-in-key/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-class-super-property-in-key/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-class-super-property-in-key/input.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-class-super-property-in-key/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-object-super-call-in-key/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-object-super-call-in-key/input.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-object-super-call-in-key/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-object-super-property-in-key/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-object-super-property-in-key/input.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-object-super-property-in-key/output.js
  packages/babel-plugin-transform-exponentiation-operator/test/fixtures/regression/4349/output.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/nested-class-super-property-in-key/exec.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/nested-class-super-property-in-key/input.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/nested-class-super-property-in-key/output.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/nested-object-super-property-in-key/exec.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/nested-object-super-property-in-key/input.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/nested-object-super-property-in-key/output.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-exponentiation/output.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-increment-postfix/exec.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-increment-postfix/input.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-increment-postfix/output.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-increment-prefix/exec.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-increment-prefix/input.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-increment-prefix/output.js
Labels: PR: Bug Fix :bug:, PR: Spec Compliancy :eyeglasses:, Spec: Classes

#7717 Provide better error message for invalid default export declaration
  packages/babylon/src/parser/statement.js
  packages/babylon/test/fixtures/es2015/modules/export-default-class-declaration/input.js
  packages/babylon/test/fixtures/es2015/modules/export-default-class-declaration/output.json
  packages/babylon/test/fixtures/es2015/modules/export-default-class-expression/input.js
  packages/babylon/test/fixtures/es2015/modules/export-default-class-expression/output.json
  packages/babylon/test/fixtures/es2015/modules/export-default-variable-declaration/input.js
  packages/babylon/test/fixtures/es2015/modules/export-default-variable-declaration/options.json
  packages/babylon/test/fixtures/es2015/modules/export-default-variable-declaration2/input.js
  packages/babylon/test/fixtures/es2015/modules/export-default-variable-declaration2/options.json
  packages/babylon/test/fixtures/es2015/modules/export-default-variable-declaration3/input.js
  packages/babylon/test/fixtures/es2015/modules/export-default-variable-declaration3/options.json
Labels: PR: Polish :nail_care:, pkg: babylon

#7722 Remove tagged template literal global caching
  packages/babel-plugin-transform-template-literals/src/index.js
  packages/babel-plugin-transform-template-literals/test/fixtures/default/cache-revision/exec.js
  packages/babel-plugin-transform-template-literals/test/fixtures/default/cache-revision/input.js
  packages/babel-plugin-transform-template-literals/test/fixtures/default/cache-revision/output.js
  packages/babel-plugin-transform-template-literals/test/fixtures/default/template-revision/output.js
  packages/babel-plugin-transform-template-literals/test/fixtures/loose/template-revision/output.js
Labels: PR: Spec Compliancy :eyeglasses:, Spec: Template Literal Revision

#7729 Drop Chai from packages
  package.json
  packages/babel-helper-transform-fixture-test-runner/package.json
Labels: PR: Internal :house:

#7732 Fix default class super inheritance
  packages/babel-plugin-transform-classes/src/transformClass.js
  packages/babel-plugin-transform-classes/test/fixtures/loose/default-super/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/loose/default-super/input.js
  packages/babel-plugin-transform-classes/test/fixtures/loose/default-super/output.js
  packages/babel-plugin-transform-classes/test/fixtures/loose/super-function-fallback/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/default-super/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/default-super/input.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/default-super/output.js
Labels: PR: Spec Compliancy :eyeglasses:, Spec: Classes

#6656 Optimize class properties output
  packages/babel-plugin-proposal-class-properties/src/index.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/compile-to-class/constructor-collision-ignores-types/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/nested-class/super-call-in-key/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/nested-class/super-property-in-key/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/computed/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/constructor-collision/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/derived/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/foobar/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/instance-computed/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/instance-undefined/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/instance/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/non-block-arrow-func/output.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/regression-T2983/output.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/regression-T6719/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/regression-T7364/output.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/static-export/output.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/static-infer-name/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/static-undefined/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/static/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/super-call/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/super-expression/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/super-statement/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/super-with-collision/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/6153/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/6154/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/7371/output.js
  packages/babel-plugin-transform-parameters/test/fixtures/regression/6057-expanded/output.js
Labels: PR: Polish :nail_care:, area: perf

#7658 Add initial support for ES2018 in preset-env
  packages/babel-preset-env/data/built-in-features.js
  packages/babel-preset-env/data/plugin-features.js
  packages/babel-preset-env/data/plugins.json
  packages/babel-preset-env/data/shipped-proposals.js
  packages/babel-preset-env/test/debug-fixtures/android/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins-no-import/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins-uglify/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/electron/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/force-all-transforms/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/plugins-only/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/shippedProposals-chrome60/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/shippedProposals/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/specific-targets/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/usage-none/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/usage-with-import/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/usage/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/versions-decimals/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/versions-strings/stdout.txt
  packages/babel-preset-env/test/fixtures/dom-iterable/symbol-iterator-in/output.mjs
  packages/babel-preset-env/test/fixtures/dom-iterable/symbol-iterator/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/builtins-used-native-support/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/builtins-used/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/for-of-destructure-with/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/for-of-destructure-without/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/core-js/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/electron/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/exclude-include/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/exclude-regenerator/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/force-all-transforms/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/ie-11-built-ins/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/include-built-ins/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-all/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-chrome-48/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-chrome-49/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-chrome-66/input.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-chrome-66/options.json
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-chrome-66/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-ie-9/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-import/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-node-web/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-node/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-require/output.js
Labels: PR: New Feature :rocket:, pkg: preset-env

#7737 Classes cleanup
  packages/babel-helper-replace-supers/src/index.js
  packages/babel-plugin-transform-classes/src/transformClass.js
  packages/babel-plugin-transform-exponentiation-operator/test/fixtures/regression/4349/output.js
  packages/babel-plugin-transform-object-super/src/index.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-exponentiation/output.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-increment-postfix/output.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-increment-prefix/output.js
  packages/babel-traverse/src/scope/index.js
Labels: PR: Internal :house:, PR: Polish :nail_care:

#7745 Improve asyncIterator error
  packages/babel-helpers/src/helpers.js
Labels: PR: Polish :nail_care:

#7734 Decorators legacy option
  packages/babel-core/test/fixtures/transformation/misc/regression-4855/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/foobar/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/foobar/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/6154/options.json
  packages/babel-plugin-proposal-decorators/README.md
  packages/babel-plugin-proposal-decorators/src/index.js
  packages/babel-plugin-proposal-decorators/src/transformer-legacy.js
  packages/babel-plugin-proposal-decorators/src/transformer.js
  packages/babel-plugin-proposal-decorators/test/fixtures/decl-to-expression/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/regression/7030/options.json
  packages/babel-plugin-syntax-decorators/README.md
  packages/babel-plugin-syntax-decorators/src/index.js
  packages/babel-plugin-transform-function-name/test/fixtures/function-name/modules-2/options.json
  packages/babel-plugin-transform-function-name/test/fixtures/function-name/modules-3/options.json
  packages/babel-plugin-transform-function-name/test/fixtures/function-name/modules/options.json
  packages/babel-plugin-transform-function-name/test/fixtures/function-name/options.json
  packages/babel-preset-stage-0/README.md
  packages/babel-preset-stage-0/src/index.js
  packages/babel-preset-stage-1/README.md
  packages/babel-preset-stage-1/package.json
  packages/babel-preset-stage-1/src/index.js
  packages/babel-preset-stage-2/README.md
  packages/babel-preset-stage-2/package.json
  packages/babel-preset-stage-2/src/index.js
Labels: PR: Breaking Change :boom:, Priority: High

#7762 Fix small typo with decorators legacy option [skip ci]
  packages/babel-plugin-proposal-decorators/src/index.js
  packages/babel-preset-stage-0/src/index.js
  packages/babel-preset-stage-1/src/index.js
  packages/babel-preset-stage-2/src/index.js
Labels: PR: Docs :memo:

#7755 drop support for Node.js v4
  .travis.yml
  CONTRIBUTING.md
  doc/design/compiler-environment-support.md
  package.json
  packages/babylon/package.json
Labels: PR: Breaking Change :boom:

#7769 [bebal-generator] fix: don't write ': ' token when name is null
  packages/babel-generator/src/generators/flow.js
  packages/babel-generator/test/fixtures/flow/type-alias/input.js
  packages/babel-generator/test/fixtures/flow/type-alias/output.js
Labels: PR: Bug Fix :bug:

#7763 Implement MemberExpressionToFunctions helper
  packages/babel-helper-member-expression-to-functions/.npmignore
  packages/babel-helper-member-expression-to-functions/README.md
  packages/babel-helper-member-expression-to-functions/package.json
  packages/babel-helper-member-expression-to-functions/src/index.js
  packages/babel-helper-replace-supers/package.json
  packages/babel-helper-replace-supers/src/index.js
  packages/babel-plugin-transform-classes/test/fixtures/regression/5769/output.js
  packages/babel-plugin-transform-exponentiation-operator/test/fixtures/regression/4349/output.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-exponentiation/output.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-increment-postfix/output.js
  packages/babel-plugin-transform-object-super/test/fixtures/object-super/super-increment-prefix/output.js
Labels: PR: Internal :house:

#7776 Memoize computed super properties
  packages/babel-helper-member-expression-to-functions/README.md
  packages/babel-helper-member-expression-to-functions/src/index.js
  packages/babel-helper-replace-supers/src/index.js
  packages/babel-plugin-transform-classes/test/fixtures/get-set/memoized-assign/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/get-set/memoized-assign/input.js
  packages/babel-plugin-transform-classes/test/fixtures/get-set/memoized-assign/output.js
  packages/babel-plugin-transform-classes/test/fixtures/get-set/memoized-update/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/get-set/memoized-update/input.js
  packages/babel-plugin-transform-classes/test/fixtures/get-set/memoized-update/output.js
Labels: PR: Bug Fix :bug:

#7750 Move more class state out of replaceSupers
  packages/babel-helper-replace-supers/src/index.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/nested-class/super-property-in-key/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/super-call/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/super-with-collision/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/derived/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/foobar/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/super-call/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/super-expression/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/super-statement/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/super-with-collision/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/6154/output.js
  packages/babel-plugin-transform-classes/src/transformClass.js
  packages/babel-plugin-transform-classes/test/fixtures/get-set/memoized-assign/output.js
  packages/babel-plugin-transform-classes/test/fixtures/get-set/memoized-update/output.js
  packages/babel-plugin-transform-classes/test/fixtures/loose/accessing-super-class/output.js
  packages/babel-plugin-transform-classes/test/fixtures/loose/calling-super-properties/output.js
  packages/babel-plugin-transform-classes/test/fixtures/regression/3028/output.js
  packages/babel-plugin-transform-classes/test/fixtures/regression/5769/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/accessing-super-class/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/calling-super-properties/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/default-super/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-class-super-property-in-key/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/nested-object-super-property-in-key/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/super-function-fallback/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/super-reference-before-bare-super-inline/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/super-reference-before-bare-super/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/super-reference-before-in-lambda-2/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/super-reference-before-in-lambda-3/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/super-reference-before-in-lambda/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/super-reference-in-prop-exression/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/this-not-allowed-before-super-in-derived-classes-2/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/this-not-allowed-before-super-in-derived-classes-3/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/this-not-allowed-before-super-in-derived-classes-4/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/this-not-allowed-before-super-in-derived-classes-5/output.js
  packages/babel-plugin-transform-parameters/test/fixtures/regression/6057-expanded/output.js
Labels: PR: Internal :house:

#7766 Correct update expression Number coercion
  packages/babel-helper-simple-access/src/index.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression/4462-T7565/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/update-expression/negative-suffix/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/update-expression/positive-suffix/output.js
  packages/babel-plugin-transform-modules-systemjs/src/index.js
  packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/hoisting-bindings/output.mjs
  packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/remap/output.mjs
Labels: PR: Bug Fix :bug:, PR: Spec Compliancy :eyeglasses:

#7358 Allow more flexible file-based configuration while preventing .babelrcs from breaking things
  packages/babel-cli/src/babel/index.js
  packages/babel-core/README.md
  packages/babel-core/src/config/config-chain.js
  packages/babel-core/src/config/files/configuration.js
  packages/babel-core/src/config/files/index-browser.js
  packages/babel-core/src/config/files/index.js
  packages/babel-core/src/config/files/package.js
  packages/babel-core/src/config/files/types.js
  packages/babel-core/src/config/files/utils.js
  packages/babel-core/src/config/partial.js
  packages/babel-core/src/config/validation/option-assertions.js
  packages/babel-core/src/config/validation/options.js
  packages/babel-core/test/api.js
  packages/babel-core/test/config-chain.js
  packages/babel-core/test/config-loading.js
  packages/babel-preset-env/test/debug-fixtures.js
  packages/babel-register/test/index.js
Labels: PR: Breaking Change :boom:, PR: New Feature :rocket:, Priority: High

#6371 Add noConflict entry mode to @babel/polyfill
  packages/babel-polyfill/noConflict.js
  packages/babel-polyfill/src/index.js
  packages/babel-polyfill/src/noConflict.js
Labels: PR: New Feature :rocket:

#7777 Use Object Spread Syntax
  codemods/babel-plugin-codemod-object-assign-to-object-spread/.npmignore
  codemods/babel-plugin-codemod-object-assign-to-object-spread/README.md
  codemods/babel-plugin-codemod-object-assign-to-object-spread/package.json
  codemods/babel-plugin-codemod-object-assign-to-object-spread/src/index.js
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/fixtures/object-assign-to-object-spread/multiple-objects/input.js
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/fixtures/object-assign-to-object-spread/multiple-objects/options.json
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/fixtures/object-assign-to-object-spread/multiple-objects/output.js
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/fixtures/object-assign-to-object-spread/multiple/input.js
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/fixtures/object-assign-to-object-spread/multiple/options.json
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/fixtures/object-assign-to-object-spread/multiple/output.js
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/fixtures/object-assign-to-object-spread/single-non-object/input.js
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/fixtures/object-assign-to-object-spread/single-non-object/options.json
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/fixtures/object-assign-to-object-spread/single-non-object/output.js
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/fixtures/object-assign-to-object-spread/single/input.js
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/fixtures/object-assign-to-object-spread/single/options.json
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/fixtures/object-assign-to-object-spread/single/output.js
  codemods/babel-plugin-codemod-object-assign-to-object-spread/test/index.js
  codemods/babel-plugin-codemod-optional-catch-binding/package.json
  codemods/babel-plugin-codemod-optional-catch-binding/src/index.js
  packages/babel-cli/src/babel/util.js
  packages/babel-code-frame/src/index.js
  packages/babel-core/src/config/config-chain.js
  packages/babel-core/src/config/full.js
  packages/babel-core/src/transform-file-sync.js
  packages/babel-core/src/transform-file.js
  packages/babel-core/src/transformation/normalize-opts.js
  packages/babel-helper-member-expression-to-functions/src/index.js
  packages/babel-helper-module-imports/src/import-injector.js
  packages/babel-helper-plugin-utils/src/index.js
  packages/babel-preset-env/src/index.js
  packages/babel-preset-env/src/normalize-options.js
  packages/babel-register/src/node.js
  packages/babel-template/src/options.js
  packages/babel-template/src/parse.js
  packages/babel-types/src/clone/cloneNode.js
  packages/babylon/src/index.js
  scripts/test.sh
Labels: PR: Polish :nail_care:

#7792 Fix indent in .travis.yml
  .travis.yml
Labels: PR: Internal :house:

#7790 update targets [skip ci]
  packages/babel-preset-env/README.md
Labels: PR: Docs :memo:

#7794 add loose to object spread
  .babelrc.js
Labels: PR: Internal :house:

#7807 Update shippedProposals in preset-env docs [skip ci]
  packages/babel-preset-env/README.md
Labels: PR: Docs :memo:

#7761 Reimplement input sourcemap merging using range matching instead of closest-position matching
  lib/third-party-libs.js.flow
  packages/babel-cli/test/fixtures/babel/filename-sourcemap --out-file --source-maps inline/out-files/script2.js
  packages/babel-core/src/transformation/file/generate.js
  packages/babel-core/src/transformation/file/merge-map.js
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-complex/input-source-map.json
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-complex/input.mjs
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-complex/options.json
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-complex/output.js
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-complex/source-map.json
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-complex/source-mappings.json
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map/source-map.json
  packages/babel-helper-fixtures/src/index.js
  packages/babel-helper-transform-fixture-test-runner/src/index.js
Labels: PR: Bug Fix :bug:, area: sourcemaps

#7813 Class Props: Don't rename constructor collisions with static props
  packages/babel-plugin-proposal-class-properties/src/index.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/constructor-collision/input.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/constructor-collision/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/constructor-collision/input.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/constructor-collision/output.js
Labels: PR: Polish :nail_care:

#7819 fix(preset-stage-3): pass along loose flag to proposal-object-rest-spread
  packages/babel-preset-stage-3/src/index.js
Labels: PR: Bug Fix :bug:

#7814 Don't fold class property calls
  packages/babel-plugin-proposal-class-properties/src/index.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/compile-to-class/constructor-collision-ignores-types/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/computed/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/super-with-collision/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/6153/output.js
Labels: PR: Internal :house:

#7803 Fix configuration of lerna-changelog
  .gitignore
  Makefile
  lerna.json
Labels: PR: Internal :house:

#7764 Fix default sourceFileName.
  packages/babel-core/src/transformation/normalize-opts.js
  packages/babel-core/test/api.js
Labels: area: sourcemaps, pkg: core

#7784 Upgrade Babel to self-host with beta.46
  .babelignore
  Gulpfile.js
  babel.config.js
  package.json
  packages/babel-core/test/api.js
  packages/babel-core/test/config-chain.js
  packages/babel-core/test/option-manager.js
  packages/babel-core/test/parse.js
  packages/babel-core/test/path.js
  packages/babel-helper-module-imports/test/index.js
  packages/babel-helper-transform-fixture-test-runner/src/index.js
  packages/babel-plugin-transform-modules-commonjs/test/copied-nodes.js
  packages/babel-plugin-transform-modules-commonjs/test/esmodule-flag.js
  packages/babel-preset-es2015/test/index.js
  scripts/gulp-tasks.js
  yarn.lock
Labels: PR: Internal :house:

#7828 [skip ci] Use queries according Browserslist Best Practices
  packages/babel-preset-env/README.md
Labels: PR: Docs :memo:, pkg: preset-env

#7835 Change babel-preset-env docs according Browserslist best practices
  packages/babel-preset-env/README.md
Labels: PR: Docs :memo:, pkg: preset-env
