Repository babel/babel, pull requests merged in 2018-03, with the labels that each got.

#7443 Update README for Babel TypeScript Plugin
  packages/babel-plugin-transform-typescript/README.md
Labels: PR: Docs :memo:, area: typescript

#7455 Use jest
  .babelrc.js
  .circleci/config.yml
  .eslintrc
  .travis.yml
  Makefile
  package.json
  packages/babel-cli/test/index.js
  packages/babel-code-frame/src/index.js
  packages/babel-core/test/api.js
  packages/babel-core/test/config-chain.js
  packages/babel-core/test/resolution.js
  packages/babel-helper-transform-fixture-test-runner/package.json
  packages/babel-helper-transform-fixture-test-runner/src/index.js
  packages/babel-preset-env-standalone/package.json
  packages/babel-preset-env-standalone/test/babel-preset-env.js
  packages/babel-preset-env/test/targets-parser.spec.js
  packages/babel-register/test/cache.js
  packages/babel-register/test/index.js
  packages/babel-standalone/test/babel.js
  packages/babel-traverse/test/replacement.js
  packages/babel-types/test/cloning.js
  packages/babel-types/test/converters.js
  packages/babel-types/test/validators.js
  scripts/_get-test-directories.sh
  scripts/test-cov.sh
  scripts/test.sh
  test/mocha.opts
  test/testSetupFile.js
  yarn.lock
Labels: PR: Internal :house:

#7479 Also run coverage with node: current
  .babelrc.js
Labels: area: tests

#7473 Remove broken check in checkFunctionNameAndParams
  packages/babylon/src/parser/expression.js
Labels: PR: Bug Fix :bug:, pkg: babylon

#7474 [Doc] [skip-ci] Remove build-babylon from contributing
  CONTRIBUTING.md
Labels: PR: Docs :memo:

#7490 Give helpful errors if the wrong sourceType is detected
  packages/babel-core/src/transformation/normalize-file.js
  packages/babel-plugin-transform-modules-commonjs/src/index.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/module-exports/output.js
  packages/babylon/src/parser/expression.js
  packages/babylon/src/parser/location.js
  packages/babylon/src/parser/statement.js
  packages/babylon/src/parser/util.js
Labels: PR: Polish :nail_care:

#7191 Add eslint plugin to disallow `t.clone` and `t.cloneDeep`
  .eslintrc
  scripts/eslint_rules/no-deprecated-clone.js
Labels: PR: Internal :house:

#7392 Spec Violation: Fix var initializer in for-in loop
  packages/babylon/src/parser/statement.js
  packages/babylon/test/fixtures/es2015/for-in/bare-initializer/input.js
  packages/babylon/test/fixtures/es2015/for-in/bare-initializer/output.json
  packages/babylon/test/fixtures/es2015/for-in/const-initializer/input.js
  packages/babylon/test/fixtures/es2015/for-in/const-initializer/options.json
  packages/babylon/test/fixtures/es2015/for-in/let-initializer/input.js
  packages/babylon/test/fixtures/es2015/for-in/let-initializer/options.json
  packages/babylon/test/fixtures/es2015/for-in/nonstrict-initializer/input.js
  packages/babylon/test/fixtures/es2015/for-in/nonstrict-initializer/output.json
  packages/babylon/test/fixtures/es2015/for-in/strict-initializer/input.js
  packages/babylon/test/fixtures/es2015/for-in/strict-initializer/options.json
  packages/babylon/test/fixtures/es2015/for-in/var-arraybindingpattern-initializer/input.js
  packages/babylon/test/fixtures/es2015/for-in/var-arraybindingpattern-initializer/options.json
  packages/babylon/test/fixtures/es2015/for-in/var-objectbindingpattern-initializer/input.js
  packages/babylon/test/fixtures/es2015/for-in/var-objectbindingpattern-initializer/options.json
  scripts/tests/test262/test262_whitelist.txt
Labels: PR: Bug Fix :bug:, PR: Spec Compliancy :eyeglasses:

#7446 Always transform for-await in async functions[rebase of #6953].
  packages/babel-helper-remap-async-to-generator/src/index.js
  packages/babel-plugin-proposal-async-generator-functions/package.json
  packages/babel-plugin-proposal-async-generator-functions/src/for-await.js
  packages/babel-plugin-proposal-async-generator-functions/src/index.js
  packages/babel-plugin-proposal-async-generator-functions/test/fixtures/for-await/async-function-no-transform/input.js
  packages/babel-plugin-proposal-async-generator-functions/test/fixtures/for-await/async-function-no-transform/options.json
  packages/babel-plugin-proposal-async-generator-functions/test/fixtures/for-await/async-function-no-transform/output.js
  packages/babel-plugin-proposal-async-generator-functions/test/fixtures/regression/5880/input.js
  packages/babel-plugin-proposal-async-generator-functions/test/fixtures/regression/5880/options.json
  packages/babel-plugin-proposal-async-generator-functions/test/fixtures/regression/5880/output.js
  packages/babel-plugin-transform-async-to-generator/src/index.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/regression/5880/options.json
  packages/babel-preset-env/test/fixtures/preset-options/shippedProposals-use-builtins-entry/output.js
  packages/babel-preset-env/test/fixtures/preset-options/shippedProposals-use-builtins-usage/output.js
  packages/babel-preset-env/test/fixtures/preset-options/shippedProposals/output.js
Labels: PR: Breaking Change :boom:, PR: Bug Fix :bug:, Spec: Async Generators

#7487 Enable and fix babel-register tests
  packages/babel-register/test/__data__/.babelrc
  packages/babel-register/test/__data__/gen_error.js
  packages/babel-register/test/cache.js
  packages/babel-register/test/index.js
Labels: PR: Internal :house:

#7496 Docs: Use namespace packages in all links
  packages/README.md
Labels: PR: Docs :memo:

#7494 Fix reseting modules in jest and config
  package.json
  packages/babel-register/test/cache.js
  packages/babel-register/test/index.js
Labels: PR: Internal :house:, area: tests

#7493 Reuse the `assertThisInitialized` helper in `possibleConstructorReturn`
  packages/babel-helpers/src/helpers.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/6154/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/regression/7030/output.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/spec/output.js
  packages/babel-plugin-transform-classes/test/fixtures/regression/T7537/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/super-reference-before-bare-super-inline/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/super-reference-before-bare-super/output.js
  packages/babel-plugin-transform-parameters/test/fixtures/regression/6057-expanded/output.js
Labels: PR: Polish :nail_care:

#7495 Raise minimum version for debug to only allow secure version.
  packages/babel-core/package.json
  packages/babel-traverse/package.json
Labels: PR: Dependency ⬆️

#7499 Wmertens add prettier config
  .babelrc.js
  .eslintignore
  .eslintrc.json
  .prettierrc
  Makefile
  lerna.json
  package.json
  test/warning.js
  yarn.lock
Labels: PR: Internal :house:

#7511 Restore passing SIGINT signals to spawned child processes
  packages/babel-node/src/babel-node.js
Labels: PR: Bug Fix :bug:

#7520 Show a more useful diff when comparing fixture files.
  packages/babel-helper-transform-fixture-test-runner/package.json
  packages/babel-helper-transform-fixture-test-runner/src/index.js
Labels: PR: Internal :house:

#7515 Update README.md and add test
  packages/babel-plugin-transform-block-scoped-functions/README.md
  packages/babel-plugin-transform-block-scoped-functions/test/fixtures/block-scoped-functions/basic/input.js
  packages/babel-plugin-transform-block-scoped-functions/test/fixtures/block-scoped-functions/basic/options.json
  packages/babel-plugin-transform-block-scoped-functions/test/fixtures/block-scoped-functions/basic/output.js
  packages/babel-plugin-transform-block-scoped-functions/test/index.js
Labels: area: tests

#7421 Add Number.parseFloat/parseInt mappins for preset-env 'usage'
  packages/babel-preset-env/src/built-in-definitions.js
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/number-ie11/input.js
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/number-ie11/options.json
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/number-ie11/output.js
Labels: PR: Bug Fix :bug:, pkg: preset-env

#7503 Update test262 test script and a few keyword escape fixes
  Makefile
  package.json
  packages/babylon/src/parser/expression.js
  packages/babylon/src/parser/statement.js
  packages/babylon/src/parser/util.js
  scripts/tests/test262/run_babylon_test262.js
  scripts/tests/test262/run_babylon_test262_utils.js
  scripts/tests/test262/test262_whitelist.txt
  yarn.lock
Labels: PR: Spec Compliancy :eyeglasses:, pkg: babylon

#7491 Explicitly throw if the array rest/spread items are not iterable.
  packages/babel-helpers/src/helpers.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression/T7199/output.js
  packages/babel-traverse/src/scope/index.js
Labels: PR: Breaking Change :boom:, PR: Bug Fix :bug:

#7530 Run build-no-bundle in the watcher to get the right files.
  Makefile
Labels: PR: Internal :house:

#7531 Fix flowtype errors introduced in #7503.
  packages/babylon/src/plugins/estree.js
  packages/babylon/src/plugins/flow.js
Labels: i: bug

#7333 Assign another temp var when parsing assignment patterns in destructuring
  packages/babel-plugin-transform-destructuring/src/index.js
  packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/const/exec.js
  packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/const/input.js
  packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/const/options.json
  packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/const/output.js
Labels: PR: Bug Fix :bug:

#7535 Add `exact` Param To ObjectTypeAnnotations
  packages/babel-generator/test/index.js
  packages/babel-types/README.md
  packages/babel-types/src/definitions/flow.js
Labels: pkg: types

#7500 Remove the sourceMapTarget option from core and implement it in babel-cli.
  packages/babel-cli/src/babel/dir.js
  packages/babel-cli/src/babel/file.js
  packages/babel-cli/src/babel/index.js
  packages/babel-cli/test/fixtures/babel/dir --out-dir --source-maps inline/out-files/lib/bar/bar.js
  packages/babel-cli/test/fixtures/babel/dir --out-dir --source-maps inline/out-files/lib/foo.js
  packages/babel-cli/test/fixtures/babel/dir --out-dir --source-maps/out-files/lib/bar/bar.js.map
  packages/babel-cli/test/fixtures/babel/dir --out-dir --source-maps/out-files/lib/foo.js.map
  packages/babel-core/README.md
  packages/babel-core/src/config/validation/options.js
  packages/babel-core/src/config/validation/removed.js
  packages/babel-core/src/transformation/normalize-opts.js
  packages/babel-core/test/fixtures/transformation/source-maps/full/source-map.json
  packages/babel-core/test/fixtures/transformation/source-maps/inline/output.js
  packages/babel-generator/README.md
  packages/babel-generator/src/source-map.js
  packages/babel-helper-transform-fixture-test-runner/src/index.js
Labels: PR: Breaking Change :boom:

#7538 Make 'sourceType:unambiguous' use 'module' when import.meta is used.
  packages/babylon/src/index.js
  packages/babylon/src/parser/base.js
  packages/babylon/src/parser/expression.js
  packages/babylon/src/parser/statement.js
  packages/babylon/test/fixtures/core/sourcetype-unambiguous/import-meta/input.js
  packages/babylon/test/fixtures/core/sourcetype-unambiguous/import-meta/options.json
  packages/babylon/test/fixtures/core/sourcetype-unambiguous/import-meta/output.json
Labels: PR: Bug Fix :bug:, PR: Polish :nail_care:

#7513 Migrate babel-core tests to use jest-expect
  packages/babel-core/test/api.js
  packages/babel-core/test/browserify.js
  packages/babel-core/test/caching-api.js
  packages/babel-core/test/config-chain.js
  packages/babel-core/test/config-loading.js
  packages/babel-core/test/evaluation.js
  packages/babel-core/test/fixtures/parse/output.json
  packages/babel-core/test/fixtures/plugins/nested-if-alternate/exec.js
  packages/babel-core/test/fixtures/transformation/misc/regression-7064/exec.js
  packages/babel-core/test/fixtures/transformation/regenerator/default-parameters/exec.js
  packages/babel-core/test/fixtures/transformation/regenerator/destructuring-parameters/exec.js
  packages/babel-core/test/fixtures/transformation/regenerator/destructuring/exec.js
  packages/babel-core/test/fixtures/transformation/regenerator/rest-parameters/exec.js
  packages/babel-core/test/option-manager.js
  packages/babel-core/test/parse.js
  packages/babel-core/test/path.js
  packages/babel-core/test/resolution.js
  packages/babel-helper-transform-fixture-test-runner/src/index.js
Labels: PR: Internal :house:, area: tests

#7547 Fix "ran" to "run" for monorepo.md
  doc/design/monorepo.md
Labels: PR: Docs :memo:

#7548 preset-env - add Symbol.asyncIterator to shippedProposals builtIns
  packages/babel-preset-env/README.md
  packages/babel-preset-env/data/built-ins.json
  packages/babel-preset-env/data/shipped-proposals.js
  packages/babel-preset-env/src/built-in-definitions.js
  packages/babel-preset-env/test/debug-fixtures/shippedProposals-chrome60/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/shippedProposals/stdout.txt
  packages/babel-preset-env/test/fixtures/preset-options/shippedProposals-use-builtins-usage/output.js
Labels: PR: Bug Fix :bug:, pkg: preset-env

#7550 Replace lodash/map with array equivalent
  packages/babel-generator/src/node/whitespace.js
Labels: PR: Polish :nail_care:

#7556 Re-add TEST_ONLY and use Jest's -t for TEST_GREP.
  scripts/test.sh
Labels: PR: Internal :house:

#7543 update preset-env after build-data
  packages/babel-preset-env/data/built-in-modules.json
  packages/babel-preset-env/data/plugins.json
  packages/babel-preset-env/test/targets-parser.spec.js
Labels: PR: Internal :house:, pkg: preset-env

#7560 Run node 9 on circleci and remove from travis
  .circleci/config.yml
  .travis.yml
Labels: PR: Internal :house:

#7561 Fix import of type ConfigItem
  packages/babel-core/src/config/validation/options.js
Labels: PR: Bug Fix :bug:

#7570 Fix incorrect value of _cache in _wrapNativeSuper
  packages/babel-helpers/src/helpers.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/loose/output.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/spec/output.js
  packages/babel-preset-env/test/fixtures/plugins-integration/issue-7527/output.js
Labels: PR: Bug Fix :bug:

#7188 Wrap wrapNativeSuper helpers in redefining functions for better tree-…
  packages/babel-helpers/src/helpers.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/loose/output.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/spec/output.js
  packages/babel-preset-env/test/fixtures/plugins-integration/issue-7527/output.js
Labels: PR: Polish :nail_care:

#7575 Fix "Module build failed: Error: Cannot find module '@babel/types'"
  packages/babel-plugin-proposal-async-generator-functions/package.json
  packages/babel-plugin-proposal-async-generator-functions/src/for-await.js
Labels: PR: Bug Fix :bug:

#7580 Ensure that the backward-compat logic for plugin-utils copies over the version API properly.
  packages/babel-core/src/config/full.js
  packages/babel-helper-plugin-utils/src/index.js
Labels: 7.x: regression, PR: Bug Fix :bug:

#7571 Remove outdated spec deviation note
  packages/babylon/README.md
Labels: PR: Docs :memo:

#7545 Make `import`s in `.mjs` files use node-like behavior where 'exports' is '.default' only.
  packages/babel-helper-module-transforms/src/index.js
  packages/babel-helper-module-transforms/src/normalize-and-load-metadata.js
  packages/babel-plugin-transform-classes/test/fixtures/regression/2775/output.js
  packages/babel-plugin-transform-modules-commonjs/src/index.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/auxiliary-comment/overview/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop-loose/imports-glob/input.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop-loose/imports-hoisting/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop-loose/imports-mixing/input.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop-loose/options.json
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop-loose/overview/input.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop/imports-glob/input.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop/imports-hoisting/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop/imports-mixing/input.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop/options.json
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop/overview/input.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-dep/import-namespace/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-dep/reexport-namespace/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-local/import-namespace/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-local/reexport-namespace/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-whitelist/import-namespace/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-whitelist/reexport-namespace/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/copy-getters-setters-star/options.json
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/copy-getters-setters/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/import-const-throw/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/reference-source-map/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression/lazy-7176/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/strict/options.json
Labels: PR: Breaking Change :boom:, PR: New Feature :rocket:, area: modules, i: enhancement

#7242 Add regexp support to include/exclude
  packages/babel-preset-env/README.md
  packages/babel-preset-env/src/normalize-options.js
  packages/babel-preset-env/test/normalize-options.spec.js
Labels: PR: New Feature :rocket:, pkg: preset-env

#7444 Refactor inheritance in babel-plugin-transform-classes
  packages/babel-plugin-transform-classes/src/index.js
  packages/babel-plugin-transform-classes/src/loose.js
  packages/babel-plugin-transform-classes/src/transformClass.js
  packages/babel-plugin-transform-classes/src/vanilla.js
Labels: PR: Internal :house:

#7586 Tweak es2015-related plugin order in preset-env
  packages/babel-preset-env/data/plugin-features.js
  packages/babel-preset-env/data/plugins.json
  packages/babel-preset-env/test/debug-fixtures/android/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins-no-import/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins-uglify/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/electron/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/force-all-transforms/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/plugins-only/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/shippedProposals/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/specific-targets/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/usage-none/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/usage/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/versions-decimals/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/versions-strings/stdout.txt
  packages/babel-preset-env/test/fixtures/sanity/block-scoping-for-of/input.js
  packages/babel-preset-env/test/fixtures/sanity/block-scoping-for-of/options.json
  packages/babel-preset-env/test/fixtures/sanity/block-scoping-for-of/output.js
Labels: PR: Bug Fix :bug:, pkg: preset-env

#7599 Centralize Babel's own compilation config to make it easier to follow.
  .babelrc.js
  .babelrc.rollup.js
  Gulpfile.js
  Makefile
  package.json
  scripts/gulp-tasks.js
Labels: PR: Internal :house:

#7602 Remove obsolete max-len eslint rule and reformat some stuff to fit
  packages/babel-cli/src/babel/index.js
  packages/babel-core/src/config/files/plugins.js
  packages/babel-core/src/config/validation/removed.js
  packages/babel-core/test/resolution.js
  packages/babel-helpers/src/helpers.js
  packages/babel-node/src/_babel-node.js
  packages/babel-plugin-transform-for-of/src/index.js
  packages/babel-preset-env/src/index.js
  packages/babylon/src/parser/comments.js
  packages/babylon/src/parser/expression.js
  packages/babylon/src/parser/statement.js
  packages/babylon/src/plugins/flow.js
  packages/babylon/src/tokenizer/index.js
  packages/babylon/src/tokenizer/state.js
Labels: PR: Internal :house:

#7604 Logical Assignment: ensure computed key isn't recomputed
  packages/babel-plugin-proposal-logical-assignment-operators/src/index.js
  packages/babel-plugin-proposal-logical-assignment-operators/test/fixtures/logical-assignment/general-semantics/exec.js
  packages/babel-plugin-proposal-logical-assignment-operators/test/fixtures/logical-assignment/general-semantics/input.js
  packages/babel-plugin-proposal-logical-assignment-operators/test/fixtures/logical-assignment/general-semantics/output.js
Labels: PR: Spec Compliancy :eyeglasses:

#7605 Disable flow on transformClass, fix preset-env errors
  packages/babel-plugin-transform-classes/src/transformClass.js
  packages/babel-preset-env/src/normalize-options.js
  packages/babel-preset-env/src/types.js
Labels: PR: Internal :house:

#7609 Update to beta.42
  package.json
Labels: PR: Internal :house:

#7617 Prevent duplicate regex flags
  packages/babylon/src/tokenizer/index.js
  packages/babylon/test/fixtures/core/uncategorised/108/options.json
  packages/babylon/test/fixtures/core/uncategorised/366/options.json
  packages/babylon/test/fixtures/es2015/regex/duplicate-flags/input.js
  packages/babylon/test/fixtures/es2015/regex/duplicate-flags/options.json
  scripts/tests/test262/test262_whitelist.txt
Labels: PR: Bug Fix :bug:, pkg: babylon

#7583 Allow placeholders in JSXElements when parsing templates
  packages/babel-template/src/parse.js
  packages/babel-template/test/index.js
Labels: PR: New Feature :rocket:, pkg: template

#7615 clean makefile a bit
  Makefile
Labels: PR: Polish :nail_care:

#7639 Allow StringLiteral and NumericLiteral as ObjectTypeProperty.key
  packages/babel-types/README.md
  packages/babel-types/src/definitions/flow.js
Labels: PR: Bug Fix :bug:, pkg: types

#7637 Add options.allowAwaitOutsideFunction.
  packages/babylon/README.md
  packages/babylon/src/options.js
  packages/babylon/src/parser/expression.js
  packages/babylon/test/fixtures/es2017/async-functions/allow-await-outside-function-throw/input.js
  packages/babylon/test/fixtures/es2017/async-functions/allow-await-outside-function-throw/options.json
  packages/babylon/test/fixtures/es2017/async-functions/allow-await-outside-function/input.js
  packages/babylon/test/fixtures/es2017/async-functions/allow-await-outside-function/options.json
  packages/babylon/test/fixtures/es2017/async-functions/allow-await-outside-function/output.json
Labels: i: enhancement
