Repository babel/babel, pull requests merged in 2018-07, with the labels that each got.

#8256 upgrade flow to v0.75.0
  package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#8238 Typescript: Avoid stripping class properties when a decorator is set
  packages/babel-plugin-transform-typescript/src/index.js
  packages/babel-plugin-transform-typescript/test/fixtures/class/properties/input.js
  packages/babel-plugin-transform-typescript/test/fixtures/class/properties/options.json
  packages/babel-plugin-transform-typescript/test/fixtures/class/properties/output.js
Labels: PR: Bug Fix :bug:, area: typescript

#8198 Prefer explicit object maps, and properly load relative maps.
  lib/third-party-libs.js.flow
  packages/babel-core/src/transformation/normalize-file.js
Labels: PR: Breaking Change :boom:, PR: Bug Fix :bug:, pkg: core

#8208 Ensure that we don't get unexpected output files for tests that throw.
  packages/babel-helper-fixtures/src/index.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/native-classes/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/non-block-arrow-func/output.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/reevaluated/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/static-export/output.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/static-infer-name/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/static-inherited/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/static-undefined/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/static/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/native-classes/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/non-block-arrow-func/output.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/reevaluated/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/regression-T2983/output.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/regression-T6719/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/static-export/output.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/static-infer-name/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/static-inherited/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/static-undefined/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/static/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/super-call-only-allowed-in-derived-constructor/output.js
Labels: PR: Internal :house:

#8259 upgrades eslint v5 (major), babel-eslint, eslint-plugin-flowtype, eslint-plugin-prettier
  Makefile
  package.json
  packages/babel-core/src/config/files/index-browser.js
  packages/babel-parser/src/parser/expression.js
  packages/babel-parser/src/plugins/typescript.js
  yarn.lock
Labels: PR: Dependency ⬆️

#8267 Optimize async to generator
  packages/babel-core/test/fixtures/transformation/misc/regression-2892/output.js
  packages/babel-helpers/src/helpers.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/shadowed-promise-import/output.mjs
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/shadowed-promise-nested/output.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/shadowed-promise/output.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/regression/4943/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/async-function/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/regenerator-used-async/output.mjs
Labels: area: perf

#8273 Add visitor key for Flow typeArguments in call expressions
  packages/babel-types/src/definitions/core.js
  packages/babel-types/src/definitions/experimental.js
Labels: PR: Bug Fix :bug:

#8165 [babel-types] Fix isNodesEquivalent() behavior for TemplateElements
  packages/babel-types/src/validators/isNodesEquivalent.js
  packages/babel-types/test/validators.js
Labels: PR: Bug Fix :bug:, pkg: types

#8187 Invoke Jest main file directly
  scripts/test.sh
Labels: PR: Internal :house:

#8282 Compile against beta 52
  package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#8279 Improve error messages around pipeline option
  packages/babel-plugin-syntax-pipeline-operator/src/index.js
  packages/babel-preset-stage-0/src/index.js
  packages/babel-preset-stage-1/src/index.js
Labels: PR: Polish :nail_care:

#8283 Upgrade upath to avoid yarn failure on node 10
  yarn.lock
Labels: PR: Internal :house:

#8264 Remove unused bindings when excluding keys with rest in loose mode
  packages/babel-plugin-proposal-object-rest-spread/src/index.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/remove-unused-excluded-keys-loose/input.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/remove-unused-excluded-keys-loose/options.json
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/remove-unused-excluded-keys-loose/output.js
Labels: PR: New Feature :rocket:

#8287 Fixed fixture tests after merge
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/remove-unused-excluded-keys-loose/output.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-spread/loose-mode/output.js
Labels: PR: Internal :house:, area: tests

#8286 Move v4-v6 changelog to another file and all prerelease 7.0 logs [ski…
  .github/CHANGELOG-v4.md
  .github/CHANGELOG-v5.md
  .github/CHANGELOG-v6.md
  CHANGELOG.md
Labels: PR: Docs :memo:

#8291 Support pipeline proposal flag in `@babel/parser`
  packages/babel-parser/src/plugin-utils.js
  packages/babel-parser/test/fixtures/experimental/nullish-coalescing-operator/with-pipeline/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/arrow-requires-parens-with-parend-args/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/arrow-requires-parens/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/await-requires-parens/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/base/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/chain/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/invalid-proposal/input.js
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/invalid-proposal/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/multiline/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/precedence/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-arrow-requires-parens-with-parend-args/input.js
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-arrow-requires-parens-with-parend-args/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-arrow-requires-parens/input.js
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-arrow-requires-parens/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-await-requires-parens/input.js
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-await-requires-parens/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-await-requires-parens/output.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-ban-await-f/input.js
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-ban-await-f/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-ban-await/input.js
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-ban-await/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-base/input.js
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-base/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-base/output.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-chain/input.js
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-chain/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-chain/output.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-multiline/input.js
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-multiline/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-multiline/output.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-precedence/input.js
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-precedence/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-precedence/output.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-with-arrow-parend-params/input.js
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-with-arrow-parend-params/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-with-arrow-parend-params/output.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-with-arrow/input.js
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-with-arrow/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/proposal-minimal-with-arrow/output.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/with-arrow-parend-params/options.json
  packages/babel-parser/test/fixtures/experimental/pipeline-operator/with-arrow/options.json
Labels: pkg: babylon

#7799 TypeScript: Support type arguments on JSX opening and self-closing tags
  packages/babel-generator/src/generators/jsx.js
  packages/babel-generator/test/fixtures/typescript/type-arguments-tsx/input.js
  packages/babel-generator/test/fixtures/typescript/type-arguments-tsx/options.json
  packages/babel-generator/test/fixtures/typescript/type-arguments-tsx/output.js
  packages/babel-parser/src/parser/index.js
  packages/babel-parser/src/plugins/jsx/index.js
  packages/babel-parser/src/plugins/typescript.js
  packages/babel-parser/src/tokenizer/index.js
  packages/babel-parser/src/types.js
  packages/babel-parser/test/fixtures/typescript/type-arguments/tsx/input.js
  packages/babel-parser/test/fixtures/typescript/type-arguments/tsx/options.json
  packages/babel-parser/test/fixtures/typescript/type-arguments/tsx/output.json
  packages/babel-plugin-transform-typescript/src/index.js
  packages/babel-plugin-transform-typescript/test/fixtures/type-arguments/tsx/input.js
  packages/babel-plugin-transform-typescript/test/fixtures/type-arguments/tsx/options.json
  packages/babel-plugin-transform-typescript/test/fixtures/type-arguments/tsx/output.js
  packages/babel-types/src/definitions/jsx.js
Labels: PR: New Feature :rocket:, area: typescript

#8299 Make env preset build-data scripts reproducible
  packages/babel-preset-env/package.json
  packages/babel-preset-env/scripts/build-modules-support.js
Labels: PR: Internal :house:, pkg: preset-env

#8308 Update pirates to 4.0
  packages/babel-register/package.json
Labels: PR: Dependency ⬆️, pkg: register

#8315 Remove option-filtering options from the final options results.
  packages/babel-core/src/config/config-chain.js
  packages/babel-core/test/config-chain.js
Labels: PR: Bug Fix :bug:

#8314 [6.x] Properly verify that decorators actually exist.
  packages/babel-plugin-transform-decorators/src/index.js
Labels: PR: Bug Fix :bug:

#8320 Add link to audio version of song
  README.md
  SONG.md
Labels: PR: Docs :memo:

#8316 Ensure that the wildcard interop is used with re-export + default.
  packages/babel-helper-module-transforms/src/normalize-and-load-metadata.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop/export-all/input.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop/export-all/output.js
Labels: PR: Bug Fix :bug:

#8317 Fix stage-0/1 import of pipeline proposals array
  packages/babel-preset-stage-0/src/index.js
  packages/babel-preset-stage-1/src/index.js
Labels: PR: Bug Fix :bug:

#8327 Treat string ignore/only/test/include/exclude values as paths with only basic pattern matching
  packages/babel-core/package.json
  packages/babel-core/src/config/config-chain.js
  packages/babel-core/src/config/files/configuration.js
  packages/babel-core/src/config/files/types.js
  packages/babel-core/src/config/pattern-to-regex.js
  packages/babel-core/src/config/validation/option-assertions.js
  packages/babel-core/src/config/validation/options.js
  packages/babel-core/test/api.js
  packages/babel-register/src/node.js
  packages/babel-register/test/index.js
  packages/babel-traverse/package.json
  packages/babel-traverse/src/path/index.js
Labels: PR: Breaking Change :boom:, PR: Bug Fix :bug:

#8333 Backport #5830: Fix parens issues with exponentiation in generator
  packages/babel-generator/src/node/parentheses.js
  packages/babel-generator/test/fixtures/parentheses/exponentiation/actual.js
  packages/babel-generator/test/fixtures/parentheses/exponentiation/expected.js
Labels: 6.x: backport, PR: Bug Fix :bug:

#8337 updates eslint, babel-eslint, eslint-plugin-flowtype, eslint-plugin-prettier
  package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#8338 bump flow
  package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#8339 bump prettier
  package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#8341 update jest (major), babel-jest (major)
  package.json
  packages/babel-generator/test/index.js
  packages/babel-helper-transform-fixture-test-runner/src/index.js
  yarn.lock
Labels: PR: Dependency ⬆️

#8342 Do not mutate ast
  packages/babel-core/src/transformation/normalize-file.js
  packages/babel-core/test/api.js
Labels: PR: Bug Fix :bug:

#8293 Remove Stage presets
  packages/babel-core/test/fixtures/transformation/misc/regression-4855/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/foobar/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/foobar/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/foobar/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/6154/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-regression/7030/options.json
  packages/babel-preset-stage-0/README.md
  packages/babel-preset-stage-0/package.json
  packages/babel-preset-stage-0/src/index.js
  packages/babel-preset-stage-1/README.md
  packages/babel-preset-stage-1/package.json
  packages/babel-preset-stage-1/src/index.js
  packages/babel-preset-stage-2/README.md
  packages/babel-preset-stage-2/package.json
  packages/babel-preset-stage-2/src/index.js
  packages/babel-preset-stage-3/README.md
  packages/babel-preset-stage-3/package.json
  packages/babel-preset-stage-3/src/index.js
  packages/babel-standalone/src/index.js
  packages/babel-standalone/src/preset-es2015.js
  packages/babel-standalone/src/preset-stage-0.js
  packages/babel-standalone/src/preset-stage-1.js
  packages/babel-standalone/src/preset-stage-2.js
  packages/babel-standalone/src/preset-stage-3.js
  scripts/generators/readmes.js
Labels: PR: Breaking Change :boom:, Priority: High

#8377 Bumped lodash to 4.17.10
  package.json
  packages/babel-cli/package.json
  packages/babel-core/package.json
  packages/babel-generator/package.json
  packages/babel-helper-define-map/package.json
  packages/babel-helper-fixtures/package.json
  packages/babel-helper-module-imports/package.json
  packages/babel-helper-module-transforms/package.json
  packages/babel-helper-regex/package.json
  packages/babel-helper-simple-access/package.json
  packages/babel-helper-transform-fixture-test-runner/package.json
  packages/babel-node/package.json
  packages/babel-plugin-transform-block-scoping/package.json
  packages/babel-register/package.json
  packages/babel-template/package.json
  packages/babel-traverse/package.json
  packages/babel-types/package.json
Labels: PR: Internal :house:

#8381 Allow an Array for `babelrcRoots`.
  packages/babel-core/src/config/validation/option-assertions.js
Labels: PR: Bug Fix :bug:, PR: Internal :house:

#8383 Fix code generation for async generator methods for babel@6.x
  packages/babel-generator/src/generators/methods.js
  packages/babel-generator/test/fixtures/edgecase/async-generator/actual.js
  packages/babel-generator/test/fixtures/edgecase/async-generator/expected.js
  packages/babel-generator/test/fixtures/edgecase/async-generator/options.json
Labels: 6.x: backport

#7754 TypeScript: Support type arguments on tagged templates
  packages/babel-generator/src/generators/template-literals.js
  packages/babel-generator/test/fixtures/typescript/type-arguments-tagged-template/input.js
  packages/babel-generator/test/fixtures/typescript/type-arguments-tagged-template/output.js
  packages/babel-parser/src/parser/expression.js
  packages/babel-parser/src/plugins/typescript.js
  packages/babel-parser/src/types.js
  packages/babel-parser/test/fixtures/typescript/type-arguments/tagged-template-no-asi/input.js
  packages/babel-parser/test/fixtures/typescript/type-arguments/tagged-template-no-asi/output.json
  packages/babel-parser/test/fixtures/typescript/type-arguments/tagged-template/input.js
  packages/babel-parser/test/fixtures/typescript/type-arguments/tagged-template/output.json
  packages/babel-plugin-transform-typescript/src/index.js
  packages/babel-plugin-transform-typescript/test/fixtures/type-arguments/tagged-template/input.js
  packages/babel-plugin-transform-typescript/test/fixtures/type-arguments/tagged-template/output.js
  packages/babel-types/src/definitions/es2015.js
Labels: PR: New Feature :rocket:, area: typescript

#8391 Ensure preset-env doesn't clobber browserslist defaults
  packages/babel-preset-env/src/targets-parser.js
  packages/babel-preset-env/test/targets-parser.spec.js
Labels: PR: Bug Fix :bug:, pkg: preset-env

#8024 Run transform-runtime on the standalone bundle so it stays ES5-compatible.
  babel.config.js
  package.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#8403 Ensure esmodule targets are parsed by browserslist
  packages/babel-preset-env/src/targets-parser.js
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/browserslist-config-ignore/browserslist
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/browserslist-config-ignore/input.mjs
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/browserslist-config-ignore/options.json
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/browserslist-config-ignore/output.mjs
Labels: PR: Bug Fix :bug:, pkg: preset-env
