Repository babel/babel, pull requests merged in 2018-02, with the labels that each got.

#7366 Fix CLI compilation callback calling
  packages/babel-cli/src/babel/util.js
Labels: PR: Bug Fix, pkg: cli

#7313 Added babel-helper-split-export-declaration
  packages/babel-helper-module-transforms/package.json
  packages/babel-helper-module-transforms/src/normalize-and-load-metadata.js
  packages/babel-helper-module-transforms/src/rewrite-live-references.js
  packages/babel-helper-split-export-declaration/.npmignore
  packages/babel-helper-split-export-declaration/README.md
  packages/babel-helper-split-export-declaration/package.json
  packages/babel-helper-split-export-declaration/src/index.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/general/regression-T2983/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/T2983/output.js
  packages/babel-plugin-transform-classes/package.json
  packages/babel-plugin-transform-classes/src/index.js
  packages/babel-plugin-transform-classes/test/fixtures/regression/2941/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/export-super-class/output.js
  packages/babel-plugin-transform-function-name/test/fixtures/function-name/export/output.js
  packages/babel-plugin-transform-function-name/test/fixtures/function-name/modules-4/output.js
  packages/babel-traverse/package.json
  packages/babel-traverse/src/scope/index.js
  packages/babel-traverse/src/scope/lib/renamer.js
Labels: PR: Internal

#7378 Preserve import binding locations during module rewriting
  packages/babel-helper-module-transforms/src/rewrite-live-references.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/auxiliary-comment/overview/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/reference-source-map/input.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/reference-source-map/options.json
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/reference-source-map/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/reference-source-map/source-mappings.json
Labels: PR: Bug Fix

#7034 Fix object spread according to spec
  packages/babel-helpers/src/helpers.js
  packages/babel-plugin-proposal-object-rest-spread/README.md
  packages/babel-plugin-proposal-object-rest-spread/src/index.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-spread/assignment/output.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-spread/expression/input.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-spread/expression/output.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-spread/loose-mode-builtins/input.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-spread/loose-mode-builtins/options.json
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-spread/loose-mode-builtins/output.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-spread/loose-mode/input.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-spread/loose-mode/options.json
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-spread/loose-mode/output.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-spread/no-object-assign-exec/exec.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-spread/variable-declaration/output.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/useBuiltIns/assignment-invalid-option/input.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/useBuiltIns/assignment-invalid-option/options.json
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/useBuiltIns/assignment-true/input.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/useBuiltIns/assignment-true/output.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/useBuiltIns/options.json
  packages/babel-preset-env/test/fixtures/preset-options/shippedProposals-use-builtins-entry/output.js
  packages/babel-preset-env/test/fixtures/preset-options/shippedProposals-use-builtins-usage/output.js
  packages/babel-preset-env/test/fixtures/preset-options/shippedProposals/output.js
Labels: PR: Bug Fix, PR: Needs Review, Spec: Object Rest/Spread

#7364 Don't extract rest elements from nested expressions
  packages/babel-plugin-proposal-object-rest-spread/src/index.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/nested-computed-key/input.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/nested-computed-key/output.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/nested-default-value/input.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/nested-default-value/output.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/nested-order/exec.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/nested-order/input.js
  packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/nested-order/output.js
Labels: PR: Bug Fix, Spec: Object Rest/Spread

#7379 Solves Tagged template literal size optimization
  packages/babel-helpers/src/helpers.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop-loose/imports-hoisting/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop/imports-hoisting/output.js
  packages/babel-plugin-transform-template-literals/src/index.js
  packages/babel-plugin-transform-template-literals/test/fixtures/default/simple-tag/input.js
  packages/babel-plugin-transform-template-literals/test/fixtures/default/simple-tag/output.js
  packages/babel-plugin-transform-template-literals/test/fixtures/default/tag/output.js
  packages/babel-plugin-transform-template-literals/test/fixtures/default/template-revision/output.js
  packages/babel-plugin-transform-template-literals/test/fixtures/loose/tag/output.js
  packages/babel-plugin-transform-template-literals/test/fixtures/loose/template-revision/output.js
Labels: PR: Polish

#7403 Remove istanbul hacks
  .babelrc.js
  package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#7372 Mark hoisted react constant elements as #__PURE__
  packages/babel-plugin-transform-async-to-generator/test/fixtures/regression/7178/output.js
  packages/babel-plugin-transform-react-constant-elements/package.json
  packages/babel-plugin-transform-react-constant-elements/src/index.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/append-to-end-when-declared-in-scope-2/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/append-to-end-when-declared-in-scope-3/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/append-to-end-when-declared-in-scope-4/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/append-to-end-when-declared-in-scope/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/children/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/class-assign-unreferenced-param-deopt/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/compound-assignment/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/constructor/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/deep-constant-violation/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/dont-hoist-before-class/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/dont-hoist-before-declaration/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/dont-hoist-before-default-params-2/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/dont-hoist-before-default-params/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/dont-hoist-before-hoc/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/function-parameter/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/global-reference/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/html-element/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/inline-elements/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/inner-declaration/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/member-expression-constant/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/member-expression-this/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/member-expression/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/param-and-var/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/parameter-destructure-multi/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/parameter-destructure-rest/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/parameter-destructure/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/parameter-reference/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/pure-expression-2/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/pure-expression-3/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/pure-expression-whitelist-member/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/pure-expression-whitelist/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/pure-expression/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/reassignment/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/regression-node-type-export-default/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/regression-node-type-export/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/text-children/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/var/output.js
  packages/babel-plugin-transform-react-jsx/test/fixtures/react/optimisation.react.constant-elements/output.js
  packages/babel-traverse/src/path/lib/hoister.js
Labels: PR: Polish, area: perf

#7418 Avoid re-traversing inserted references to the namespace binding.
  packages/babel-helper-module-transforms/src/rewrite-live-references.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression/lazy-7176/input.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression/lazy-7176/options.json
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression/lazy-7176/output.js
Labels: PR: Bug Fix :bug:

#7413 Update babel to beta.40
  package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#7400 Add missing promise polyfill deps for preset-env's useBuiltIns: usage
  packages/babel-preset-env/src/built-in-definitions.js
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/promise-all/input.js
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/promise-all/options.json
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/promise-all/output.js
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/promise-race/input.js
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/promise-race/options.json
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/promise-race/output.js
Labels: PR: Bug Fix :bug:, pkg: preset-env

#7401 Bump compat-table and regen preset-env data
  .prettierignore
  packages/babel-preset-env/data/built-ins.json
  packages/babel-preset-env/data/plugins.json
  packages/babel-preset-env/package.json
  packages/babel-preset-env/scripts/build-modules-support.js
Labels: PR: Internal :house:, pkg: preset-env

#7416 Replace instead of merging babel-register options, and resolve cwd up front
  packages/babel-register/src/node.js
Labels: PR: Breaking Change :boom:

#7423 Reinstate `--inspect-brk`, lost when making babel-node standalone
  packages/babel-node/src/babel-node.js
Labels: 7.x: regression, PR: Bug Fix :bug:

#7404 TypeScript: Support conditional types syntax
  packages/babel-generator/src/generators/typescript.js
  packages/babel-generator/test/fixtures/typescript/types-conditional-infer/input.js
  packages/babel-generator/test/fixtures/typescript/types-conditional-infer/output.js
  packages/babel-generator/test/fixtures/typescript/types-conditional/input.js
  packages/babel-generator/test/fixtures/typescript/types-conditional/output.js
  packages/babel-types/README.md
  packages/babel-types/src/asserts/generated/index.js
  packages/babel-types/src/builders/generated/index.js
  packages/babel-types/src/definitions/typescript.js
  packages/babel-types/src/validators/generated/index.js
  packages/babylon/src/plugins/typescript.js
  packages/babylon/src/types.js
  packages/babylon/test/fixtures/typescript/types/conditional-infer/input.js
  packages/babylon/test/fixtures/typescript/types/conditional-infer/output.json
  packages/babylon/test/fixtures/typescript/types/conditional/input.js
  packages/babylon/test/fixtures/typescript/types/conditional/output.json
Labels: PR: New Feature :rocket:, area: typescript

#7159 typescript: Support definite assignment assertion
  packages/babel-generator/src/generators/classes.js
  packages/babel-generator/src/generators/statements.js
  packages/babel-generator/test/fixtures/typescript/class-properties/input.js
  packages/babel-generator/test/fixtures/typescript/class-properties/output.js
  packages/babel-generator/test/fixtures/typescript/variable-declarator-exclamation/actual.js
  packages/babel-generator/test/fixtures/typescript/variable-declarator-exclamation/expected.js
  packages/babel-plugin-transform-typescript/src/index.js
  packages/babel-plugin-transform-typescript/test/fixtures/class/properties/input.js
  packages/babel-plugin-transform-typescript/test/fixtures/class/properties/output.js
  packages/babel-plugin-transform-typescript/test/fixtures/variable-declaration/exclamation/actual.js
  packages/babel-plugin-transform-typescript/test/fixtures/variable-declaration/exclamation/expected.js
  packages/babel-types/src/definitions/core.js
  packages/babel-types/src/definitions/experimental.js
  packages/babylon/src/plugins/typescript.js
  packages/babylon/src/types.js
  packages/babylon/test/fixtures/typescript/class/properties/input.js
  packages/babylon/test/fixtures/typescript/class/properties/output.json
  packages/babylon/test/fixtures/typescript/class/property-optional-definite-assignment-not-allowed/input.js
  packages/babylon/test/fixtures/typescript/class/property-optional-definite-assignment-not-allowed/options.json
  packages/babylon/test/fixtures/typescript/variable-declarator/definite-assignment-not-allowed/input.js
  packages/babylon/test/fixtures/typescript/variable-declarator/definite-assignment-not-allowed/options.json
  packages/babylon/test/fixtures/typescript/variable-declarator/definite-assignment/input.js
  packages/babylon/test/fixtures/typescript/variable-declarator/definite-assignment/output.json
Labels: PR: New Feature :rocket:, area: typescript

#7227 Fix up flow errors
  .flowconfig
  package.json
  packages/babel-template/src/formatters.js
  packages/babel-types/src/definitions/utils.js
  packages/babylon/package.json
  packages/babylon/src/parser/expression.js
  packages/babylon/src/plugins/flow.js
  packages/babylon/src/plugins/typescript.js
  packages/babylon/src/tokenizer/index.js
  packages/babylon/src/tokenizer/state.js
  packages/babylon/src/types.js
  yarn.lock
Labels: PR: Internal :house:

#7441 Fix CONTRIBUTING.md
  CONTRIBUTING.md
Labels: i: docs

#7438 Ensure babel-preset-env targets input object is not mutated
  packages/babel-preset-env/src/normalize-options.js
Labels: PR: Bug Fix :bug:, pkg: preset-env

#7436 Default to `ast:false` and do less work when loading core
  packages/babel-core/src/config/index.js
  packages/babel-core/src/tools/build-external-helpers.js
  packages/babel-core/src/transformation/index.js
  packages/babel-core/test/api.js
  packages/babel-helpers/src/helpers.js
  packages/babel-plugin-transform-modules-commonjs/test/copied-nodes.js
Labels: PR: Breaking Change :boom:

#7417 Rely entirely on sourceType for module vs script differentiation.
  packages/babel-core/test/api.js
  packages/babel-helper-module-imports/src/import-injector.js
  packages/babel-helper-module-imports/src/is-module.js
  packages/babel-helper-transform-fixture-test-runner/src/index.js
  packages/babel-plugin-transform-modules-amd/test/fixtures/amd/get-module-name-option/options.json
  packages/babel-plugin-transform-modules-amd/test/fixtures/amd/module-name/options.json
  packages/babel-plugin-transform-modules-amd/test/fixtures/loose/get-module-name-option/options.json
  packages/babel-plugin-transform-modules-amd/test/fixtures/loose/module-name/options.json
  packages/babel-plugin-transform-modules-commonjs/src/index.js
  packages/babel-plugin-transform-modules-umd/test/fixtures/loose/get-module-name-option/options.json
  packages/babel-plugin-transform-modules-umd/test/fixtures/loose/module-id/options.json
  packages/babel-plugin-transform-modules-umd/test/fixtures/loose/module-name/options.json
  packages/babel-plugin-transform-modules-umd/test/fixtures/umd/get-module-name-option/options.json
  packages/babel-plugin-transform-modules-umd/test/fixtures/umd/module-id/options.json
  packages/babel-plugin-transform-modules-umd/test/fixtures/umd/module-name/options.json
  packages/babel-preset-env-standalone/test/babel-preset-env.js
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/test-modules-tranform/options.json
  packages/babel-preset-env/test/fixtures/preset-options/shippedProposals-use-builtins-usage/options.json
  packages/babel-standalone/test/babel.js
Labels: PR: Breaking Change :boom:

#7453 Install peerDependencies and remove unused async dependency
  package.json
  yarn.lock
Labels: PR: Internal :house:

#7451 Update to circleci v2
  .circleci/config.yml
  circle.yml
Labels: PR: Internal :house:

#7454 Dependency cleanup
  package.json
  scripts/tests/test262/run_babylon_test262_utils.js
  yarn.lock
Labels: PR: Internal :house:
