Repository babel/babel, pull requests merged in 2018-06, with the labels that each got.

#8074 nit: fix folder name
  packages/babel-parser/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-true-decorator-after-export/input.mjs
  packages/babel-parser/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-true-decorator-after-export/options.json
Labels: PR: Polish :nail_care:

#8037 Remove parser support for decorators optional parentheses
  packages/babel-core/test/fixtures/parse/output.json
  packages/babel-generator/src/generators/expressions.js
  packages/babel-parser/src/parser/statement.js
  packages/babel-parser/test/fixtures/experimental/decorators-2/class-decorator-call-expr/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/class-decorator/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/class-expression/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/class-generator/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/class-property/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/complex-expr/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/compued-property/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export-default-decorated-expression-with-parens/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export-default/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/export-decorated-class/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/export-default-decorated-class/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/get-decorator/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/nested-class-decorator-parameters/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/nested-class-decorator/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/nested-method-decorator-parameters/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/nested-method-decorator/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/on-computed-name-method/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/parenthesized/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/private-property/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/set-decorator/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/static-method/output.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/static-property/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/class-decorator-assignment/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/class-decorator-call-expr/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/class-decorator-getter/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/class-decorator-same-line/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/class-decorator-setter/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/class-decorator/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/class-decorators-multiple/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/class-method-parameter/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/computed-member-expr-on-prop/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/computed-member-expression/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/export-decorators-on-class/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/export-default-declaration-function-declaration-parameter/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/export-default-decorators-on-class/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/export-default-with-nested-class/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/function-declaration-parameter/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/function-expression-parameter/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/method-decorator/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/object-decorator/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/object-method-parameter/output.json
  packages/babel-parser/test/fixtures/experimental/uncategorised/40/output.json
  packages/babel-parser/test/fixtures/experimental/uncategorised/47/output.json
  packages/babel-parser/test/fixtures/experimental/uncategorised/48/output.json
  packages/babel-parser/test/fixtures/experimental/uncategorised/49/output.json
  packages/babel-parser/test/fixtures/experimental/uncategorised/62/output.json
  packages/babel-parser/test/fixtures/typescript/class/parameter-properties-with-decorators/output.json
  packages/babel-parser/test/fixtures/typescript/decorators/abstract-class/output.json
  packages/babel-plugin-proposal-decorators/src/transformer-legacy.js
  packages/babel-types/README.md
  packages/babel-types/src/definitions/experimental.js
Labels: PR: Breaking Change :boom:, PR: Spec Compliancy :eyeglasses:, Spec: Decorators

#8100 Fix ReferenceError in the wrapNativeSuper helper
  packages/babel-helpers/README.md
  packages/babel-helpers/src/helpers.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/overwritten-null/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/super-called/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/wrap-native-super/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/wrap-native-super/options.json
Labels: PR: Bug Fix :bug:

#8113 Change decoratorsBeforeExport default to false
  packages/babel-generator/src/index.js
  packages/babel-generator/test/fixtures/types/Decorator/output.js
  packages/babel-parser/src/parser/statement.js
  packages/babel-parser/test/fixtures/experimental/decorators-2/no-export-decorators-on-class/options.json
  packages/babel-plugin-syntax-decorators/src/index.js
  packages/babel-plugin-syntax-decorators/test/index.js
Labels: PR: Breaking Change :boom:, Spec: Decorators, pkg: babylon, pkg: generator

#7908 Test on node 10
  .circleci/config.yml
  .travis.yml
  packages/babel-node/package.json
Labels: PR: Dependency ⬆️, PR: Internal :house:, area: tests

#8112 Feat add issues link in readmes
  packages/babel-cli/README.md
  packages/babel-core/README.md
  packages/babel-parser/README.md
  packages/babel-polyfill/README.md
  packages/babel-preset-env/README.md
  packages/babel-preset-flow/README.md
  packages/babel-preset-react/README.md
  packages/babel-preset-typescript/README.md
  packages/babel-traverse/README.md
  packages/babel-types/README.md
  scripts/generators/readmes.js
Labels: i: docs

#8125 Update identifier parsing per Unicode v11
  packages/babel-parser/package.json
  packages/babel-parser/scripts/generate-identifier-regex.js
  packages/babel-parser/src/util/identifier.js
Labels: PR: Dependency ⬆️, PR: Spec Compliancy :eyeglasses:

#8127 Update plugin-proposal-unicode-property-regex for Unicode v11
  packages/babel-plugin-proposal-unicode-property-regex/package.json
  packages/babel-plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-11/input.js
  packages/babel-plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-11/output.js
  packages/babel-plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-11/input.js
  packages/babel-plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-11/output.js
Labels: PR: Dependency ⬆️, PR: Spec Compliancy :eyeglasses:

#8123 [class-properties] Remove unnecessary return and temp variable
  packages/babel-plugin-proposal-class-properties/src/index.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/derived/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/derived/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/super-call/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/derived/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/super-call/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/derived/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/super-call/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/6154/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/super-call-only-allowed-in-derived-constructor/output.js
  packages/babel-plugin-transform-parameters/test/fixtures/regression/6057-expanded/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/class-assign-unreferenced-param-deopt/output.mjs
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/member-expression-this/output.js
  packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/member-expression/output.js
Labels: PR: Polish :nail_care:, Spec: Class Fields

#8031 Validate @babel/preset-env options
  lib/third-party-libs.js.flow
  packages/babel-preset-env/package.json
  packages/babel-preset-env/src/normalize-options.js
  packages/babel-preset-env/src/options.js
  packages/babel-preset-env/src/targets-parser.js
  packages/babel-preset-env/src/types.js
  packages/babel-preset-env/src/utils.js
  packages/babel-preset-env/test/normalize-options.spec.js
  packages/babel-preset-env/test/targets-parser.spec.js
  packages/babel-preset-env/test/utils.spec.js
Labels: PR: New Feature :rocket:, pkg: preset-env

#8139 Bump test262-stream and update test262 tests
  Makefile
  package.json
  scripts/tests/test262/run_babel_parser_test262_utils.js
  scripts/tests/test262/test262_whitelist.txt
  yarn.lock
Labels: PR: Internal :house:

#8144 Add Labels to READMEs Generator & Update README's w. Links To Open Issues (for some pkg's)
  packages/babel-generator/README.md
  packages/babel-node/README.md
  packages/babel-standalone/README.md
  packages/babel-template/README.md
  scripts/generators/readmes.js
Labels: PR: Internal :house:, i: docs

#8138 Ensure regex-dot-all runs before unicode-regex in preset-env
  packages/babel-preset-env/data/built-in-modules.json
  packages/babel-preset-env/data/plugin-features.js
  packages/babel-preset-env/data/plugins.json
  packages/babel-preset-env/test/debug-fixtures/android/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins-no-import/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins-uglify/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/electron/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/force-all-transforms/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/plugins-only/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/shippedProposals-chrome60/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/shippedProposals/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/specific-targets/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/usage-none/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/usage-with-import/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/usage/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/versions-decimals/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/versions-strings/stdout.txt
  packages/babel-preset-env/test/fixtures/sanity/regex-dot-all/exec.js
  packages/babel-preset-env/test/fixtures/sanity/regex-dot-all/input.js
  packages/babel-preset-env/test/fixtures/sanity/regex-dot-all/options.json
  packages/babel-preset-env/test/fixtures/sanity/regex-dot-all/output.js
Labels: PR: Bug Fix :bug:, pkg: preset-env

#8132 Fix Safari TP and regular versions comparison
  packages/babel-preset-env/src/targets-parser.js
  packages/babel-preset-env/test/targets-parser.spec.js
Labels: PR: Bug Fix :bug:, pkg: preset-env

#8030 Allow ts modifier names to be used as function argument names
  packages/babel-parser/src/plugins/typescript.js
  packages/babel-parser/test/fixtures/typescript/class/constructor-with-modifier-names/input.js
  packages/babel-parser/test/fixtures/typescript/class/constructor-with-modifier-names/output.json
Labels: PR: Bug Fix :bug:, area: typescript, pkg: babylon

#8007 Fix 'Missing class properties transform' error when parsing class properties with Typescript syntax
  packages/babel-plugin-proposal-class-properties/test/fixtures/compile-to-class/constructor-collision-ignores-types-loose/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/compile-to-class/constructor-collision-ignores-types/output.js
  packages/babel-plugin-transform-typescript/src/index.js
Labels: PR: Bug Fix :bug:

#7996 Adds JSXFragment to plugin-transform-typescript check for the presence of jsx
  packages/babel-plugin-transform-typescript/src/index.js
  packages/babel-plugin-transform-typescript/test/fixtures/imports/elide-react-no-3/input.mjs
  packages/babel-plugin-transform-typescript/test/fixtures/imports/elide-react-no-3/options.json
  packages/babel-plugin-transform-typescript/test/fixtures/imports/elide-react-no-3/output.mjs
Labels: PR: Bug Fix :bug:, area: typescript

#8122 isConstantExpression should return true for immuable bindings
  packages/babel-plugin-proposal-class-properties/src/index.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/computed/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/computed/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/8110/input.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/8110/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/8110/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz-edgest-case/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz-general/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz-loose/exec.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz-loose/input.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz-loose/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz/edgest-case/exec.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz/edgest-case/input.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz/edgest-case/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz/edgest-case/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz/general/exec.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz/general/input.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz/general/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz/general/output.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz/loose/exec.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz/loose/input.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz/loose/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/static-property-tdz/loose/output.js
  packages/babel-traverse/src/path/introspection.js
Labels: PR: Bug Fix :bug:, pkg: traverse

#8051 Don't split an exported class when renaming an inner binding
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/7951/input.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/7951/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/regression/7951/output.mjs
  packages/babel-traverse/src/scope/lib/renamer.js
Labels: PR: Bug Fix :bug:, pkg: traverse (scope)

#8154 Update regenerator-transform to latest version (0.13.0).
  packages/babel-plugin-transform-regenerator/package.json
Labels: PR: Dependency ⬆️

#8161 fix flow typeof refinement
  packages/babel-preset-env/src/utils.js
Labels: PR: Internal :house:

#8162 bump flow to v0.74.0
  package.json
Labels: PR: Dependency ⬆️

#8177 babel/parser: remove dead code: constant condition
  packages/babel-parser/src/plugins/flow.js
Labels: PR: Internal :house:, pkg: babylon

#8176 babel/parser: use charCodes throughout for improved sourcecode readability in tokenizer/parser.
  packages/babel-parser/src/plugins/flow.js
  packages/babel-parser/src/util/identifier.js
Labels: PR: Internal :house:, pkg: babylon

#8178 babel/parser: test helpers: write expected throw message to options.json ~ complete `jest -u` functionality
  packages/babel-parser/test/helpers/runFixtureTests.js
Labels: PR: Internal :house:, area: tests

#8158 Compile against beta 51
  package.json
  yarn.lock
Labels: PR: Internal :house:

#8197 Allow @foo/babel-plugin as an unexpanded plugin name, and @foo as a shorthand for it.
  packages/babel-core/src/config/files/plugins.js
  packages/babel-core/test/fixtures/resolution/foo-org-paths/node_modules/@foo/babel-plugin/index.js
  packages/babel-core/test/fixtures/resolution/foo-org-paths/node_modules/@foo/babel-preset/index.js
  packages/babel-core/test/resolution.js
Labels: PR: Bug Fix :bug:, pkg: core

#8220 Remove regenerator hacks in checkDuplicatedNodes
  packages/babel-helper-transform-fixture-test-runner/src/index.js
Labels: PR: Internal :house:, area: tests

#6578 Fixes #6577
  packages/babel-core/src/transformation/file/index.js
Labels: 6.x: backport, PR: Bug Fix :bug:

#8196 Require proposal flag for pipeline plugin
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/foobar/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/foobar/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/foobar/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-regression/7030/options.json
  packages/babel-plugin-proposal-pipeline-operator/test/fixtures/pipeline-operator/options.json
  packages/babel-plugin-syntax-pipeline-operator/src/index.js
  packages/babel-preset-stage-0/src/index.js
  packages/babel-preset-stage-1/src/index.js
Labels: PR: Breaking Change :boom:, Spec: Pipeline Operator
