Repository babel/babel, pull requests merged in 2018-05, with the labels that each got.

#7839 add lock bot for closed issues [skip ci]
  .github/lock.yml
Labels: PR: Internal :house:

#7844 Improve README's for several plugins. [skip ci]
  packages/babel-plugin-transform-destructuring/README.md
  packages/babel-plugin-transform-exponentiation-operator/README.md
  packages/babel-plugin-transform-property-mutators/README.md
  packages/babel-plugin-transform-proto-to-assign/README.md
  packages/babel-plugin-transform-reserved-words/README.md
  packages/babel-plugin-transform-spread/README.md
Labels: PR: Docs :memo:

#7825 Unify `main` property in package.json [ci skip]
  packages/babel-core/package.json
  packages/babel-plugin-proposal-logical-assignment-operators/package.json
  packages/babel-plugin-proposal-nullish-coalescing-operator/package.json
  packages/babel-plugin-syntax-logical-assignment-operators/package.json
  packages/babel-plugin-syntax-nullish-coalescing-operator/package.json
Labels: PR: Internal :house:

#7850 Allow parsing of decorators with TypeScript abstract classes
  packages/babylon/src/parser/statement.js
  packages/babylon/src/plugins/typescript.js
  packages/babylon/test/fixtures/typescript/decorators/abstract-class/input.js
  packages/babylon/test/fixtures/typescript/decorators/abstract-class/options.json
  packages/babylon/test/fixtures/typescript/decorators/abstract-class/output.json
Labels: area: typescript, pkg: babylon

#7810 Improve useBuiltIns: usage mappins in preset-env
  packages/babel-preset-env/src/built-in-definitions.js
  packages/babel-preset-env/test/debug-fixtures/usage/stdout.txt
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/builtins-used-evaluated-class-methods/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/builtins-used-instance-methods-native-support/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/builtins-used-instance-methods/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/builtins-used-native-support/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/builtins-used/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/promise-all/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/promise-race/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/shippedProposals-use-builtins-usage/output.js
Labels: PR: Bug Fix :bug:, pkg: preset-env

#7884 Fix bug with handling minor versions when parsing compat-data
  packages/babel-preset-env/data/built-ins.json
  packages/babel-preset-env/data/plugins.json
  packages/babel-preset-env/package.json
  packages/babel-preset-env/scripts/build-data.js
Labels: PR: Bug Fix :bug:, pkg: preset-env

#7888 TypeScript: Allow non-null and type assertions as lvalues. (Fixes #7638)
  packages/babel-plugin-transform-typescript/test/fixtures/lvalues/as-expression/input.js
  packages/babel-plugin-transform-typescript/test/fixtures/lvalues/as-expression/output.js
  packages/babel-plugin-transform-typescript/test/fixtures/lvalues/non-null/input.js
  packages/babel-plugin-transform-typescript/test/fixtures/lvalues/non-null/output.js
  packages/babel-plugin-transform-typescript/test/fixtures/lvalues/type-assertion/input.js
  packages/babel-plugin-transform-typescript/test/fixtures/lvalues/type-assertion/output.js
  packages/babylon/src/plugins/typescript.js
  packages/babylon/test/fixtures/typescript/cast/null-assertion-and-assign/input.js
  packages/babylon/test/fixtures/typescript/cast/null-assertion-and-assign/output.json
  packages/babylon/test/fixtures/typescript/cast/type-assertion-and-assign/input.js
  packages/babylon/test/fixtures/typescript/cast/type-assertion-and-assign/output.json
Labels: PR: Bug Fix :bug:, area: typescript

#7895 Bumped lodash version
  package.json
  packages/babel-cli/package.json
  packages/babel-core/package.json
  packages/babel-generator/package.json
  packages/babel-helper-define-map/package.json
  packages/babel-helper-fixtures/package.json
  packages/babel-helper-module-imports/package.json
  packages/babel-helper-module-transforms/package.json
  packages/babel-helper-regex/package.json
  packages/babel-helper-simple-access/package.json
  packages/babel-helper-transform-fixture-test-runner/package.json
  packages/babel-node/package.json
  packages/babel-plugin-transform-block-scoping/package.json
  packages/babel-register/package.json
  packages/babel-template/package.json
  packages/babel-traverse/package.json
  packages/babel-types/package.json
Labels: PR: Dependency ⬆️

#7809 Clean up and add some additional polyfill mappings in preset-env
  .prettierignore
  packages/babel-preset-env/data/built-in-features.js
  packages/babel-preset-env/data/built-ins.json
  packages/babel-preset-env/test/debug-fixtures/android/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins-uglify/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/electron/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/force-all-transforms/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/shippedProposals-chrome60/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/shippedProposals/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/specific-targets/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/versions-decimals/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/versions-strings/stdout.txt
  packages/babel-preset-env/test/fixtures/preset-options-add-used-built-ins/number-ie11/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/core-js/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/electron/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/exclude-include/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/exclude-regenerator/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/force-all-transforms/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/ie-11-built-ins/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/include-built-ins/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/shippedProposals-use-builtins-usage/output.js
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-all/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-chrome-48/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-chrome-49/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-ie-9/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-import/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-node-web/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-node/output.mjs
  packages/babel-preset-env/test/fixtures/preset-options/use-builtins-require/output.js
Labels: PR: Bug Fix :bug:, pkg: preset-env

#7821 Rename decorators&decorators2 plugins to decorators-legacy&decorators.
  packages/babel-generator/test/fixtures/types/Decorator/options.json
  packages/babel-generator/test/fixtures/typescript/class-parameter-properties-with-decorators/options.json
  packages/babel-plugin-syntax-decorators/src/index.js
  packages/babylon/src/index.js
  packages/babylon/src/parser/expression.js
  packages/babylon/src/parser/lval.js
  packages/babylon/src/parser/statement.js
  packages/babylon/test/fixtures/experimental/_no-plugin/decorators/options.json
  packages/babylon/test/fixtures/experimental/decorators-2/class-property/options.json
  packages/babylon/test/fixtures/experimental/decorators-2/compued-property/options.json
  packages/babylon/test/fixtures/experimental/decorators-2/export-decorated-class-without-plugin/options.json
  packages/babylon/test/fixtures/experimental/decorators-2/options.json
  packages/babylon/test/fixtures/experimental/decorators-2/plugin-conflict/options.json
  packages/babylon/test/fixtures/experimental/decorators-2/private-property/options.json
  packages/babylon/test/fixtures/experimental/decorators-2/static-property/options.json
  packages/babylon/test/fixtures/experimental/decorators/computed-member-expr-on-prop/options.json
  packages/babylon/test/fixtures/experimental/decorators/options.json
  packages/babylon/test/fixtures/experimental/uncategorised/40/options.json
  packages/babylon/test/fixtures/experimental/uncategorised/41/options.json
  packages/babylon/test/fixtures/experimental/uncategorised/42/options.json
  packages/babylon/test/fixtures/experimental/uncategorised/47/options.json
  packages/babylon/test/fixtures/experimental/uncategorised/48/options.json
  packages/babylon/test/fixtures/experimental/uncategorised/49/options.json
  packages/babylon/test/fixtures/experimental/uncategorised/62/options.json
  packages/babylon/test/fixtures/typescript/class/parameter-properties-with-decorators/options.json
  scripts/tests/flow/run_babylon_flow_tests.js
Labels: PR: Breaking Change :boom:, pkg: babylon

#7855 Lazy load tagged template literal strings
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop-loose/imports-hoisting/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop/imports-hoisting/output.js
  packages/babel-plugin-transform-template-literals/src/index.js
  packages/babel-plugin-transform-template-literals/test/fixtures/default/cache-revision/output.js
  packages/babel-plugin-transform-template-literals/test/fixtures/default/simple-tag/output.js
  packages/babel-plugin-transform-template-literals/test/fixtures/default/tag/output.js
  packages/babel-plugin-transform-template-literals/test/fixtures/default/template-revision/output.js
  packages/babel-plugin-transform-template-literals/test/fixtures/loose/tag/output.js
  packages/babel-plugin-transform-template-literals/test/fixtures/loose/template-revision/output.js
Labels: PR: Polish :nail_care:

#7904 Fix typescript decorator test
  packages/babel-core/test/fixtures/parse/.babelrc
  packages/babylon/test/fixtures/typescript/decorators/abstract-class/options.json
Labels: PR: Internal :house:

#7916 Use the correct Babylon plugins for Test262 tests
  scripts/tests/test262/run_babylon_test262.js
  scripts/tests/test262/run_babylon_test262_utils.js
  scripts/tests/test262/test262_whitelist.txt
Labels: PR: Internal :house:, area: test262, pkg: babylon

#7875 Fix watch bug with output-dir paths.
  packages/babel-cli/src/babel/dir.js
Labels: PR: Bug Fix :bug:, pkg: cli

#7925 Update test262 and flow tests
  Makefile
  scripts/tests/flow/flow_tests_whitelist.txt
  scripts/tests/flow/run_babylon_flow_tests.js
  scripts/tests/test262/run_babylon_test262_utils.js
  scripts/tests/test262/test262_whitelist.txt
Labels: PR: Internal :house:, area: test262, area: tests

#7911 Allow 'babelrc' and 'babelrcRoots' in config files (but not .babelrc/extends)
  packages/babel-core/src/config/config-chain.js
  packages/babel-core/src/config/partial.js
  packages/babel-core/src/config/validation/options.js
  packages/babel-core/test/config-chain.js
Labels: PR: Bug Fix :bug:, PR: New Feature :rocket:

#7854 remove @babel/preset-latest from docs
  packages/babel-preset-env/README.md
Labels: PR: Docs :memo:, pkg: preset-env

#7931 Test running bug fixing for Node 10
  packages/babel-helper-transform-fixture-test-runner/src/index.js
  packages/babel-helper-transform-fixture-test-runner/test/index.js
Labels: PR: Internal :house:

#7930 Ensure that calling register() fully resets the extension state.
  packages/babel-register/src/node.js
Labels: PR: Bug Fix :bug:

#7869 Add an option to Babylon to have decorators before export
  packages/babylon/src/index.js
  packages/babylon/src/parser/base.js
  packages/babylon/src/parser/index.js
  packages/babylon/src/parser/statement.js
  packages/babylon/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export-default-decorated-expression-with-parens/input.mjs
  packages/babylon/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export-default-decorated-expression-with-parens/options.json
  packages/babylon/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export-default-decorated-expression-with-parens/output.json
  packages/babylon/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export-default-decorated-expression-without-parens/input.mjs
  packages/babylon/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export-default-decorated-expression-without-parens/options.json
  packages/babylon/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export-default/input.mjs
  packages/babylon/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export-default/options.json
  packages/babylon/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export-default/output.json
  packages/babylon/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export/input.mjs
  packages/babylon/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export/options.json
  packages/babylon/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export/output.json
  packages/babylon/test/fixtures/experimental/decorators-2/export-decorated-class-without-plugin/options.json
  packages/babylon/test/fixtures/experimental/decorators-2/plugin-conflict/options.json
Labels: PR: New Feature :rocket:, Spec: Decorators, pkg: babylon

#7946 update core-js in babel-polyfill to 2.5.6
  packages/babel-polyfill/package.json
Labels: PR: Dependency ⬆️, pkg: polyfill

#7929 Refactor babel-cli to use async functions for async handling, and centralize option loading
  babel.config.js
  package.json
  packages/babel-cli/src/babel/dir.js
  packages/babel-cli/src/babel/file.js
  packages/babel-cli/src/babel/index.js
  packages/babel-cli/src/babel/options.js
  packages/babel-cli/src/babel/util.js
  packages/babel-cli/test/fixtures/babel/empty dir --out-dir/stdout.txt
  packages/babel-core/package.json
Labels: PR: Internal :house:, pkg: cli

#7533 Fix bugs in the _wrapNativeSuper helper
  packages/babel-helpers/src/helpers.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/loose/output.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/overwritten-null/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/overwritten-null/options.json
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/spec/output.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/super-called/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/extend-builtins/super-called/options.json
  packages/babel-preset-env/test/fixtures/plugins-integration/issue-7527/exec.js
  packages/babel-preset-env/test/fixtures/plugins-integration/issue-7527/output.js
Labels: PR: Bug Fix :bug:

#7975 Add "legacy" prefix to legacy decorators tests
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-constructors/mutate-existing-constructor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-constructors/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-constructors/return-new-constructor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-export-default/exec.mjs
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-export-default/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-ordering/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-ordering/order/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-ordering/reverse-order/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-prototype-methods/mutate-descriptor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-prototype-methods/numeric-props/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-prototype-methods/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-prototype-methods/return-descriptor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-prototype-methods/string-props/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-prototype-properties/child-classes-properties/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-prototype-properties/mutate-descriptor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-prototype-properties/mutate-initialzer/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-prototype-properties/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-prototype-properties/properties-without-initializer/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-prototype-properties/return-descriptor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-static-methods/mutate-descriptor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-static-methods/numeric-props/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-static-methods/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-static-methods/return-descriptor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-static-methods/string-props/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-static-properties/mutate-descriptor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-static-properties/mutate-initialzer/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-static-properties/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-static-properties/properties-without-initializer/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-class-static-properties/return-descriptor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-decl-to-expression/class-decorators/input.mjs
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-decl-to-expression/class-decorators/output.mjs
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-decl-to-expression/method-decorators/input.mjs
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-decl-to-expression/method-decorators/output.mjs
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-decl-to-expression/no-decorators/input.mjs
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-decl-to-expression/no-decorators/output.mjs
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-decl-to-expression/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-methods/mutate-descriptor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-methods/numeric-props/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-methods/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-methods/return-descriptor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-methods/string-props/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-ordering/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-ordering/order/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-ordering/reverse-order/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-properties/mutate-descriptor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-properties/mutate-initialzer/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-properties/numeric-props/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-properties/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-properties/return-descriptor/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-object-properties/string-props/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-regression/7030/input.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-regression/7030/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-regression/7030/output.js
Labels: PR: Internal :house:, area: tests

#7934 Add support for explicit type arguments in new and call expressions
  packages/babel-generator/src/generators/expressions.js
  packages/babel-generator/test/fixtures/flow/typeapp-call/input.js
  packages/babel-generator/test/fixtures/flow/typeapp-call/options.json
  packages/babel-generator/test/fixtures/flow/typeapp-call/output.js
  packages/babel-plugin-syntax-flow/src/index.js
  packages/babel-plugin-transform-flow-strip-types/src/index.js
  packages/babel-plugin-transform-flow-strip-types/test/fixtures/strip-types/strip-typeapp-call/input.js
  packages/babel-plugin-transform-flow-strip-types/test/fixtures/strip-types/strip-typeapp-call/options.json
  packages/babel-plugin-transform-flow-strip-types/test/fixtures/strip-types/strip-typeapp-call/output.js
  packages/babel-types/README.md
  packages/babel-types/src/definitions/core.js
  packages/babel-types/src/definitions/experimental.js
  packages/babylon/src/parser/expression.js
  packages/babylon/src/parser/util.js
  packages/babylon/src/plugins/flow.js
  packages/babylon/test/fixtures/flow/typeapp-call/async-call/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/async-call/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/async-generic-arrow/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/async-generic-arrow/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/disabled-ambiguous-call/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/disabled-ambiguous-call/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/disabled-ambiguous-new/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/disabled-ambiguous-new/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/function-call-chain/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/function-call-chain/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/function-call-optional/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/function-call-optional/options.json
  packages/babylon/test/fixtures/flow/typeapp-call/function-call-optional/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/function-call/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/function-call/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/method-call-computed/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/method-call-computed/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/method-call-optional/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/method-call-optional/options.json
  packages/babylon/test/fixtures/flow/typeapp-call/method-call-optional/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/method-call-optional2/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/method-call-optional2/options.json
  packages/babylon/test/fixtures/flow/typeapp-call/method-call-optional2/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/method-call/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/method-call/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/new-noparens/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/new-noparens/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/new/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/new/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/rollback-computed/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/rollback-computed/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/rollback-dot/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/rollback-dot/output.json
  packages/babylon/test/fixtures/flow/typeapp-call/rollback-jsx/input.js
  packages/babylon/test/fixtures/flow/typeapp-call/rollback-jsx/output.json
  scripts/tests/flow/flow_tests_whitelist.txt
  scripts/tests/flow/run_babylon_flow_tests.js
Labels: PR: New Feature :rocket:, area: flow

#7977 Update babel-types (flow internal slots)
  packages/babel-types/README.md
  packages/babel-types/src/asserts/generated/index.js
  packages/babel-types/src/builders/generated/index.js
  packages/babel-types/src/validators/generated/index.js
Labels: pkg: types

#7967 TypeScript: Fix TSInferType .typeParameter type.
  packages/babel-types/README.md
  packages/babel-types/src/definitions/typescript.js
  packages/babylon/src/plugins/typescript.js
  packages/babylon/test/fixtures/typescript/types/conditional-infer/output.json
Labels: area: typescript

#7982 Build InterfaceTypeAnnotation generated type code
  packages/babel-types/src/asserts/generated/index.js
  packages/babel-types/src/builders/generated/index.js
  packages/babel-types/src/validators/generated/index.js
Labels: PR: Bug Fix :bug:

#7985 Subsume json
  packages/babel-parser/src/tokenizer/index.js
  packages/babel-parser/test/fixtures/experimental/json-strings/directive-line-separator/input.js
  packages/babel-parser/test/fixtures/experimental/json-strings/directive-line-separator/output.json
  packages/babel-parser/test/fixtures/experimental/json-strings/directive-paragraph-separator/input.js
  packages/babel-parser/test/fixtures/experimental/json-strings/directive-paragraph-separator/output.json
  packages/babel-parser/test/fixtures/experimental/json-strings/options.json
  packages/babel-parser/test/fixtures/experimental/json-strings/string-line-separator/input.js
  packages/babel-parser/test/fixtures/experimental/json-strings/string-line-separator/output.json
  packages/babel-parser/test/fixtures/experimental/json-strings/string-paragraph-separator/input.js
  packages/babel-parser/test/fixtures/experimental/json-strings/string-paragraph-separator/output.json
  packages/babel-plugin-proposal-json-strings/.npmignore
  packages/babel-plugin-proposal-json-strings/README.md
  packages/babel-plugin-proposal-json-strings/package.json
  packages/babel-plugin-proposal-json-strings/src/index.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/json-strings/directive-line-separator/exec.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/json-strings/directive-line-separator/input.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/json-strings/directive-line-separator/output.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/json-strings/directive-paragraph-separator/exec.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/json-strings/directive-paragraph-separator/input.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/json-strings/directive-paragraph-separator/output.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/json-strings/string-line-separator/exec.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/json-strings/string-line-separator/input.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/json-strings/string-line-separator/output.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/json-strings/string-paragraph-separator/exec.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/json-strings/string-paragraph-separator/input.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/json-strings/string-paragraph-separator/output.js
  packages/babel-plugin-proposal-json-strings/test/fixtures/options.json
  packages/babel-plugin-proposal-json-strings/test/index.js
  packages/babel-plugin-syntax-json-strings/.npmignore
  packages/babel-plugin-syntax-json-strings/README.md
  packages/babel-plugin-syntax-json-strings/package.json
  packages/babel-plugin-syntax-json-strings/src/index.js
  packages/babel-preset-stage-3/package.json
  packages/babel-preset-stage-3/src/index.js
Labels: PR: New Feature :rocket:, PR: Spec Compliancy :eyeglasses:

#7990 passes the jsxPragma options from preset-typescript to plugin-transform-typescript
  packages/babel-preset-typescript/README.md
  packages/babel-preset-typescript/src/index.js
Labels: PR: Bug Fix :bug:

#7956 Make the filename option, as exposed to the plugins, consistently relative to the working directory
  packages/babel-cli/test/index.js
  packages/babel-core/src/config/config-chain.js
  packages/babel-core/src/config/partial.js
  packages/babel-core/src/transformation/plugin-pass.js
  packages/babel-core/test/config-chain.js
  packages/babel-plugin-transform-react-jsx-source/test/fixtures/react-source/basic-sample/exec.js
  packages/babel-preset-react/test/fixtures/preset-options/development/exec.js
Labels: PR: Breaking Change :boom:, PR: Bug Fix :bug:

#8002 Fix some flow issues in @babel/parser flow plugin
  packages/babel-parser/src/plugins/flow.js
  packages/babel-parser/src/types.js
Labels: PR: Internal :house:, pkg: babylon

#8006 Bigint Support (no transform)
  packages/babel-generator/src/generators/types.js
  packages/babel-generator/test/fixtures/types/BigIntLiteral/input.js
  packages/babel-generator/test/fixtures/types/BigIntLiteral/options.json
  packages/babel-generator/test/fixtures/types/BigIntLiteral/output.js
  packages/babel-plugin-syntax-bigint/.npmignore
  packages/babel-plugin-syntax-bigint/README.md
  packages/babel-plugin-syntax-bigint/package.json
  packages/babel-plugin-syntax-bigint/src/index.js
  packages/babel-types/src/definitions/experimental.js
Labels: PR: Bug Fix :bug:

#8005 Handle Infinity, -Infinity, NaN, and -0 in t.valueToNode().
  packages/babel-types/src/converters/valueToNode.js
  packages/babel-types/test/converters.js
Labels: PR: Bug Fix :bug:

#7955 Verify that files are .ts/.tsx before treating as Typescript files.
  packages/babel-core/src/config/validation/options.js
  packages/babel-helper-fixtures/src/index.js
  packages/babel-helper-transform-fixture-test-runner/src/index.js
  packages/babel-plugin-syntax-flow/src/index.js
  packages/babel-plugin-syntax-jsx/src/index.js
  packages/babel-plugin-syntax-typescript/src/index.js
  packages/babel-plugin-transform-typescript/test/fixtures/imports/elide-preact-no/options.json
  packages/babel-plugin-transform-typescript/test/fixtures/imports/elide-react-no-2/options.json
  packages/babel-plugin-transform-typescript/test/fixtures/imports/elide-react-no/options.json
  packages/babel-preset-react/package.json
  packages/babel-preset-react/src/index.js
  packages/babel-preset-typescript/package.json
  packages/babel-preset-typescript/src/index.js
  packages/babel-preset-typescript/test/fixtures/flow-compat/js-invalid/input.js
  packages/babel-preset-typescript/test/fixtures/flow-compat/js-invalid/options.json
  packages/babel-preset-typescript/test/fixtures/flow-compat/js-valid/input.js
  packages/babel-preset-typescript/test/fixtures/flow-compat/js-valid/output.js
  packages/babel-preset-typescript/test/fixtures/flow-compat/options.json
  packages/babel-preset-typescript/test/fixtures/flow-compat/ts-invalid/input.ts
  packages/babel-preset-typescript/test/fixtures/flow-compat/ts-invalid/options.json
  packages/babel-preset-typescript/test/fixtures/flow-compat/ts-valid/input.ts
  packages/babel-preset-typescript/test/fixtures/flow-compat/ts-valid/output.js
  packages/babel-preset-typescript/test/fixtures/flow-compat/tsx-invalid/input.tsx
  packages/babel-preset-typescript/test/fixtures/flow-compat/tsx-invalid/options.json
  packages/babel-preset-typescript/test/fixtures/flow-compat/tsx-valid/input.tsx
  packages/babel-preset-typescript/test/fixtures/flow-compat/tsx-valid/output.js
  packages/babel-preset-typescript/test/fixtures/jsx-compat/js-valid/input.js
  packages/babel-preset-typescript/test/fixtures/jsx-compat/js-valid/output.js
  packages/babel-preset-typescript/test/fixtures/jsx-compat/options.json
  packages/babel-preset-typescript/test/fixtures/jsx-compat/ts-invalid/input.ts
  packages/babel-preset-typescript/test/fixtures/jsx-compat/ts-invalid/options.json
  packages/babel-preset-typescript/test/fixtures/jsx-compat/tsx-valid/input.tsx
  packages/babel-preset-typescript/test/fixtures/jsx-compat/tsx-valid/output.js
  packages/babel-preset-typescript/test/index.js
  packages/babel-standalone/test/babel.js
Labels: PR: Breaking Change :boom:

#5621 Add no-babelrc option in babel-node
  packages/babel-cli/test/index.js
  packages/babel-node/src/_babel-node.js
  packages/babel-node/test/fixtures/babel-node/--no-babelrc/.babelrc
  packages/babel-node/test/fixtures/babel-node/--no-babelrc/in-files/index.js
  packages/babel-node/test/fixtures/babel-node/--no-babelrc/in-files/logPlugin.js
  packages/babel-node/test/fixtures/babel-node/--no-babelrc/options.json
  packages/babel-node/test/fixtures/babel-node/--no-babelrc/stdout.txt
Labels: PR: New Feature :rocket:

#8010 Add more of babel-cli's options to babel-node too for consistency.
  packages/babel-node/src/_babel-node.js
Labels: PR: New Feature :rocket:

#7986 Better error message for invalid decorators syntax
  packages/babel-parser/src/parser/statement.js
  packages/babel-parser/test/fixtures/experimental/decorators-2/decoratorsBeforeExport-export-default-decorated-expression-without-parens/options.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/decoratorsBeforeExpoty-true-decorator-after-export/input.mjs
  packages/babel-parser/test/fixtures/experimental/decorators-2/decoratorsBeforeExpoty-true-decorator-after-export/options.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/export-after-expression-decorator/input.js
  packages/babel-parser/test/fixtures/experimental/decorators-2/export-after-expression-decorator/options.json
  packages/babel-parser/test/fixtures/experimental/decorators-2/no-export-decorators-on-class/options.json
Labels: Spec: Decorators, area: errors, pkg: babylon

#7999 [babylon] Refactor mixin plugins handling & validation
  packages/babel-parser/src/index.js
  packages/babel-parser/src/options.js
  packages/babel-parser/src/parser/base.js
  packages/babel-parser/src/parser/index.js
  packages/babel-parser/src/plugin-utils.js
Labels: PR: Internal :house:, pkg: babylon

#7968 Set exprAllowed to false when parsing TSNonNullExpression
  packages/babel-parser/src/plugins/typescript.js
  packages/babel-parser/test/fixtures/typescript/cast/null-assertion-2/input.js
  packages/babel-parser/test/fixtures/typescript/cast/null-assertion-2/output.json
  packages/babel-parser/test/fixtures/typescript/cast/null-assertion-3/input.js
  packages/babel-parser/test/fixtures/typescript/cast/null-assertion-3/output.json
  packages/babel-parser/test/fixtures/typescript/cast/null-assertion-and-assign-2/input.js
  packages/babel-parser/test/fixtures/typescript/cast/null-assertion-and-assign-2/output.json
Labels: PR: Bug Fix :bug:, area: typescript, pkg: babylon

#7994 [Babylon] Take the first set of options for plugins
  packages/babel-parser/README.md
  packages/babel-parser/src/parser/index.js
  packages/babel-parser/test/plugin-options.js
Labels: pkg: babylon

#8023 Add a promise-returning *Async version of the transform and parse fns
  packages/babel-core/package.json
  packages/babel-core/src/config/index.js
  packages/babel-core/src/index.js
  packages/babel-core/src/parse.js
  packages/babel-core/src/transform-ast-sync.js
  packages/babel-core/src/transform-ast.js
  packages/babel-core/src/transform-file-sync.js
  packages/babel-core/src/transform-file.js
  packages/babel-core/src/transform-sync.js
  packages/babel-core/src/transform.js
Labels: PR: New Feature :rocket:, pkg: core

#8044 Expose all filenames as absolute paths, rather than relative.
  packages/babel-cli/test/fixtures/babel/stdin --filename/stderr.txt
  packages/babel-cli/test/index.js
  packages/babel-core/src/config/partial.js
  packages/babel-core/test/config-chain.js
  packages/babel-plugin-transform-react-jsx-source/test/fixtures/react-source/basic-sample/exec.js
  packages/babel-preset-env/test/debug-fixtures.js
  packages/babel-preset-env/test/debug-fixtures/android/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins-no-import/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins-uglify/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/builtins/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/electron/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/force-all-transforms/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/plugins-only/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/shippedProposals-chrome60/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/shippedProposals/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/specific-targets/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/usage-none/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/usage-with-import/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/usage/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/versions-decimals/stdout.txt
  packages/babel-preset-env/test/debug-fixtures/versions-strings/stdout.txt
  packages/babel-preset-react/test/fixtures/preset-options/development/exec.js
Labels: PR: Bug Fix :bug:

#8047 Transform decorated classes from the export visitor
  packages/babel-plugin-proposal-decorators/src/transformer-legacy.js
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-regression/8041/input.mjs
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-regression/8041/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/legacy-regression/8041/output.mjs
Labels: 7.x: regression, PR: Bug Fix :bug:

#8046 Handle kebab-case args in babel-node.
  packages/babel-node/src/_babel-node.js
  packages/babel-node/test/fixtures/babel-node/--config-file/in-files/configFile.js
  packages/babel-node/test/fixtures/babel-node/--config-file/in-files/index.js
  packages/babel-node/test/fixtures/babel-node/--config-file/options.json
  packages/babel-node/test/fixtures/babel-node/--config-file/stdout.txt
  packages/babel-node/test/fixtures/babel-node/--env-name/.babelrc
  packages/babel-node/test/fixtures/babel-node/--env-name/in-files/index.js
  packages/babel-node/test/fixtures/babel-node/--env-name/in-files/logPlugin.js
  packages/babel-node/test/fixtures/babel-node/--env-name/options.json
  packages/babel-node/test/fixtures/babel-node/--env-name/stdout.txt
Labels: PR: Bug Fix :bug:

#8032 Bump flow version
  package.json
  packages/babel-core/src/config/files/configuration.js
  packages/babel-parser/src/plugins/flow.js
  packages/babel-parser/src/tokenizer/state.js
  packages/babel-preset-env/src/normalize-options.js
  packages/babel-types/src/definitions/index.js
  yarn.lock
Labels: PR: Dependency ⬆️

#7948 Add "decoratorsBeforeExport" option to @babel/generator
  packages/babel-generator/src/generators/classes.js
  packages/babel-generator/src/generators/modules.js
  packages/babel-generator/src/index.js
  packages/babel-generator/src/printer.js
  packages/babel-generator/test/fixtures/decoratorsBeforeExport/false-to-false/input.js
  packages/babel-generator/test/fixtures/decoratorsBeforeExport/false-to-false/options.json
  packages/babel-generator/test/fixtures/decoratorsBeforeExport/false-to-false/output.js
  packages/babel-generator/test/fixtures/decoratorsBeforeExport/false-to-true/input.js
  packages/babel-generator/test/fixtures/decoratorsBeforeExport/false-to-true/options.json
  packages/babel-generator/test/fixtures/decoratorsBeforeExport/false-to-true/output.js
  packages/babel-generator/test/fixtures/decoratorsBeforeExport/true-to-false/input.js
  packages/babel-generator/test/fixtures/decoratorsBeforeExport/true-to-false/options.json
  packages/babel-generator/test/fixtures/decoratorsBeforeExport/true-to-false/output.js
  packages/babel-generator/test/fixtures/decoratorsBeforeExport/true-to-true/input.js
  packages/babel-generator/test/fixtures/decoratorsBeforeExport/true-to-true/options.json
  packages/babel-generator/test/fixtures/decoratorsBeforeExport/true-to-true/output.js
  packages/babel-plugin-proposal-decorators/README.md
  packages/babel-plugin-proposal-decorators/src/index.js
Labels: PR: New Feature :rocket:, Spec: Decorators, pkg: generator

#8064 Update package.json
  packages/babel-polyfill/package.json
  packages/babel-register/package.json
  packages/babel-runtime/package.json
Labels: PR: Dependency ⬆️, pkg: polyfill

#8072 Update regenerator version and test retain lines fixture
  packages/babel-plugin-transform-regenerator/package.json
  packages/babel-plugin-transform-regenerator/test/fixtures/variable-renaming/retain-lines/output.js
Labels: PR: Dependency ⬆️

#8082 Avoid a race condition in CLI directory creation.
  packages/babel-cli/src/babel/dir.js
Labels: PR: Bug Fix :bug:, pkg: cli

#7938 Update syntax-decorators options
  packages/babel-core/test/fixtures/option-manager/presets/es2015_default_function.js
  packages/babel-core/test/fixtures/option-manager/presets/es2015_default_object.js
  packages/babel-core/test/fixtures/option-manager/presets/es5_function.js
  packages/babel-core/test/fixtures/option-manager/presets/es5_object.js
  packages/babel-plugin-syntax-decorators/README.md
  packages/babel-plugin-syntax-decorators/src/index.js
  packages/babel-plugin-syntax-decorators/test/index.js
Labels: PR: Breaking Change :boom:, PR: New Feature :rocket:, Spec: Decorators

#8060 make isReferenced() recognise ObjectTypeProperty
  packages/babel-types/src/validators/isReferenced.js
  packages/babel-types/test/validators.js
Labels: PR: Bug Fix :bug:, area: flow
