Repository babel/babel, pull requests merged in 2022-12, with the labels that each got.

#15223 fix: Deleting super property should throw
  packages/babel-helper-member-expression-to-functions/src/index.ts
  packages/babel-helper-replace-supers/package.json
  packages/babel-helper-replace-supers/src/index.ts
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/delete-super-property/exec.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/delete-super-property/input.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/delete-super-property/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/delete-super-property-to-property-key/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/delete-super-property-to-property-key/input.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/delete-super-property-to-property-key/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/delete-super-property/exec.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/delete-super-property/input.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/delete-super-property/output.js
  yarn.lock
Labels: PR: Spec Compliance :eyeglasses:, PR: Bug Fix :bug:

#15232 fix: Computed properties should keep original definition order
  Makefile
  packages/babel-core/src/transformation/file/file.ts
  packages/babel-helpers/src/helpers-generated.ts
  packages/babel-helpers/src/helpers/defineAccessor.js
  packages/babel-plugin-transform-computed-properties/package.json
  packages/babel-plugin-transform-computed-properties/src/index.ts
  packages/babel-plugin-transform-computed-properties/test/fixtures/assumption-setComputedProperties/accessors/output.js
  packages/babel-plugin-transform-computed-properties/test/fixtures/assumption-setComputedProperties/single-accessor/input.js
  packages/babel-plugin-transform-computed-properties/test/fixtures/assumption-setComputedProperties/single-accessor/output.js
  packages/babel-plugin-transform-computed-properties/test/fixtures/assumption-setComputedProperties/symbol/output.js
  packages/babel-plugin-transform-computed-properties/test/fixtures/spec/accessors/output.js
  packages/babel-plugin-transform-computed-properties/test/fixtures/spec/definition-order/exec.js
  packages/babel-plugin-transform-computed-properties/test/fixtures/spec/definition-order/input.js
  packages/babel-plugin-transform-computed-properties/test/fixtures/spec/definition-order/options.json
  packages/babel-plugin-transform-computed-properties/test/fixtures/spec/definition-order/output.js
  packages/babel-plugin-transform-computed-properties/test/fixtures/spec/single-accessor/input.js
  packages/babel-plugin-transform-computed-properties/test/fixtures/spec/single-accessor/output.js
  packages/babel-plugin-transform-computed-properties/test/fixtures/spec/symbol/output.js
  packages/babel-runtime-corejs2/package.json
  packages/babel-runtime-corejs3/package.json
  packages/babel-runtime/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#15233 fix: Emit correct sourcemap ranges for `JSXText`
  packages/babel-plugin-transform-react-jsx/test/fixtures/sourcemaps/JSXText/input.js
  packages/babel-plugin-transform-react-jsx/test/fixtures/sourcemaps/JSXText/options.json
  packages/babel-plugin-transform-react-jsx/test/fixtures/sourcemaps/JSXText/output.mjs
  packages/babel-plugin-transform-react-jsx/test/fixtures/sourcemaps/JSXText/source-map.json
  packages/babel-types/src/utils/react/cleanJSXElementLiteralChild.ts
Labels: PR: Bug Fix :bug:, area: sourcemaps, area: jsx

#15258 fix: Correctly generate `(a ?? b) as T`
  packages/babel-generator/src/node/parentheses.ts
  packages/babel-generator/test/fixtures/typescript/cast-need-parentheses/input.js
  packages/babel-generator/test/fixtures/typescript/cast-need-parentheses/output.js
  packages/babel-plugin-proposal-optional-chaining/test/fixtures/transparent-expr-wrappers/ts-as-in-conditional/output.js
Labels: PR: Bug Fix :bug:, pkg: generator, area: typescript

#15274 Inline & simplify `@babel/helper-define-map`
  packages/babel-helper-define-map/.npmignore
  packages/babel-helper-define-map/README.md
  packages/babel-helper-define-map/package.json
  packages/babel-helper-define-map/src/index.ts
  packages/babel-plugin-transform-property-mutators/package.json
  packages/babel-plugin-transform-property-mutators/src/define-map.ts
  packages/babel-plugin-transform-property-mutators/src/index.ts
  tsconfig.json
  yarn.lock
Labels: PR: Internal :house:

#15235 fix: Transform `for await` with shadowed variables
  packages/babel-plugin-proposal-async-generator-functions/src/index.ts
  packages/babel-preset-env/test/fixtures/plugins-integration/issue-11610/exec.js
  packages/babel-preset-env/test/fixtures/plugins-integration/issue-11610/input.js
  packages/babel-preset-env/test/fixtures/plugins-integration/issue-11610/options.json
  packages/babel-preset-env/test/fixtures/plugins-integration/issue-11610/output.js
Labels: PR: Bug Fix :bug:

#15275 Improve relative execution tracking in fn exprs
  packages/babel-plugin-transform-block-scoping/test/fixtures/tdz/function-expression/input.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/tdz/function-expression/output.js
  packages/babel-traverse/src/path/introspection.ts
  packages/babel-traverse/test/introspection.js
Labels: PR: Polish :nail_care:

#15277 fix: A test on main
  packages/babel-plugin-transform-block-scoping/test/fixtures/tdz/function-expression/output.js
Labels: PR: Fixes failing main

#15252 chore: Clean up `parser` comments
  packages/babel-parser/src/parser/comments.ts
  packages/babel-parser/src/parser/lval.ts
  packages/babel-parser/src/parser/statement.ts
  packages/babel-parser/src/parser/util.ts
  packages/babel-parser/src/plugins/placeholders.ts
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/src/tokenizer/index.ts
  packages/babel-parser/src/util/expression-scope.ts
  packages/babel-parser/src/util/location.ts
Labels: pkg: parser

#15278 Fix tdz analysis for reassigned captured for bindings
  packages/babel-plugin-transform-block-scoping/src/validation.ts
  packages/babel-plugin-transform-block-scoping/test/fixtures/regression/updated-for-binding-with-tdz-enabled/input.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/regression/updated-for-binding-with-tdz-enabled/options.json
  packages/babel-plugin-transform-block-scoping/test/fixtures/regression/updated-for-binding-with-tdz-enabled/output.js
Labels: PR: Bug Fix :bug:, i: regression

#15284 fix: Ts import type and func with duplicate name
  packages/babel-plugin-transform-typescript/test/fixtures/imports/import-type-func-with-duplicate-name/input.ts
  packages/babel-plugin-transform-typescript/test/fixtures/imports/import-type-func-with-duplicate-name/output.mjs
  packages/babel-traverse/src/scope/index.ts
  packages/babel-traverse/test/scope.js
Labels: PR: Bug Fix :bug:, area: typescript, pkg: traverse (scope)

#15287 Fix `.parentPath` after rename in `SwitchCase`
  packages/babel-traverse/src/scope/index.ts
  packages/babel-traverse/src/scope/lib/renamer.ts
  packages/babel-traverse/test/scope.js
Labels: PR: Bug Fix :bug:, pkg: traverse

#15209 fix: Support auto accessors with TypeScript annotations
  packages/babel-parser/src/parse-error/standard-errors.ts
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/test/fixtures/core/object/invalid-setter/output.json
  packages/babel-parser/test/fixtures/es2015/class-methods/getter-signature/output.json
  packages/babel-parser/test/fixtures/es2015/uncategorised/347/output.json
  packages/babel-parser/test/fixtures/esprima/invalid-syntax/migrated_0075/output.json
  packages/babel-parser/test/fixtures/esprima/rest-parameter/invalid-setter-rest/output.json
  packages/babel-parser/test/fixtures/estree/object-method/invalid-setter/output.json
  packages/babel-parser/test/fixtures/estree/typescript/getter-setter/output.json
  packages/babel-parser/test/fixtures/flow/object-types/invalid-getter-param-count-rest/output.json
  packages/babel-parser/test/fixtures/flow/object-types/invalid-getter-param-count/output.json
  packages/babel-parser/test/fixtures/flow/object-types/invalid-setter-param-count/output.json
  packages/babel-parser/test/fixtures/flow/object-types/invalid-setter-param-type/output.json
  packages/babel-parser/test/fixtures/flow/this-annotation/this-getter/output.json
  packages/babel-parser/test/fixtures/flow/this-annotation/this-setter-type/output.json
  packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/input.ts
  packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/options.json
  packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/output.json
  packages/babel-parser/test/fixtures/typescript/class/accessor/input.ts
  packages/babel-parser/test/fixtures/typescript/class/accessor/options.json
  packages/babel-parser/test/fixtures/typescript/class/accessor/output.json
  packages/babel-parser/test/fixtures/typescript/interface/get-set-invalid-parameters-babel-7/output.json
  packages/babel-parser/test/fixtures/typescript/interface/get-set-invalid-parameters/output.json
  packages/babel-parser/test/fixtures/typescript/interface/get-set-invalid-this-parameters-babel-7/output.json
  packages/babel-parser/test/fixtures/typescript/interface/get-set-invalid-this-parameters/output.json
  packages/babel-plugin-transform-typescript/src/index.ts
  packages/babel-plugin-transform-typescript/test/fixtures/class/accessor-allowDeclareFields-false/input.ts
  packages/babel-plugin-transform-typescript/test/fixtures/class/accessor-allowDeclareFields-false/options.json
  packages/babel-plugin-transform-typescript/test/fixtures/class/accessor-allowDeclareFields-false/output.js
  packages/babel-plugin-transform-typescript/test/fixtures/class/accessor-allowDeclareFields-true-babel-7/input.ts
  packages/babel-plugin-transform-typescript/test/fixtures/class/accessor-allowDeclareFields-true-babel-7/options.json
  packages/babel-plugin-transform-typescript/test/fixtures/class/accessor-allowDeclareFields-true-babel-7/output.js
  packages/babel-plugin-transform-typescript/test/fixtures/class/accessor-allowDeclareFields-true/input.ts
  packages/babel-plugin-transform-typescript/test/fixtures/class/accessor-allowDeclareFields-true/options.json
  packages/babel-plugin-transform-typescript/test/fixtures/class/accessor-allowDeclareFields-true/output.js
Labels: PR: Bug Fix :bug:, Priority: High, pkg: parser, area: typescript

#15294 Properly transpile exported classes that shadowed builtins
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/class-shadow-builtins/input.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/class-shadow-builtins/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/class-shadow-builtins/output.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/class-shadow-builtins/input.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/class-shadow-builtins/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/private/class-shadow-builtins/output.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/class-shadow-builtins/input.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/class-shadow-builtins/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/public-loose/class-shadow-builtins/output.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/class-shadow-builtins/input.mjs
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/class-shadow-builtins/options.json
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/class-shadow-builtins/output.mjs
  packages/babel-traverse/src/path/modification.ts
Labels: PR: Bug Fix :bug:

#15301 fix: `transform-block-scoping` accesses properties of `null`
  packages/babel-plugin-transform-block-scoping/src/validation.ts
Labels: PR: Bug Fix :bug:, i: regression

#15303 fix: Do not throw exceptions when scope information is corrupted
  packages/babel-plugin-transform-block-scoping/src/index.ts
Labels: PR: Bug Fix :bug:, i: regression

#15305 fix: `guessExecutionStatusRelativeTo` exception
  packages/babel-traverse/src/path/introspection.ts
Labels: PR: Bug Fix :bug:, pkg: traverse, i: regression

#15309 Fix for binding shadowing outer var with loop closure
  packages/babel-plugin-transform-block-scoping/src/index.ts
  packages/babel-plugin-transform-block-scoping/src/loop.ts
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/for-variable-update-different-captured/exec.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/for-variable-update-different-captured/input.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/for-variable-update-different-captured/output.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-15308-for-variable-shadow-and-capture/exec.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-15308-for-variable-shadow-and-capture/input.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-15308-for-variable-shadow-and-capture/output.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-15308-for-variable-shadow-and-update/exec.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-15308-for-variable-shadow-and-update/input.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-15308-for-variable-shadow-and-update/output.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-15308-for-variable-shadow-original-sibling-scope/exec.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-15308-for-variable-shadow-original-sibling-scope/input.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-15308-for-variable-shadow-original-sibling-scope/output.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-15308-for-variable-shadow/exec.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-15308-for-variable-shadow/input.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-15308-for-variable-shadow/output.js
Labels: PR: Bug Fix :bug:, i: regression

#15316 fix: prototype pollution from json5
  packages/babel-core/package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#15312 fix: `delete this` in static class properties initialization
  packages/babel-helper-create-class-features-plugin/package.json
  packages/babel-helper-create-class-features-plugin/src/fields.ts
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/delete-this/exec.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/delete-this/input.js
  packages/babel-plugin-proposal-class-properties/test/fixtures/public/delete-this/output.js
  yarn.lock
Labels: PR: Bug Fix :bug:
