Repository babel/babel, pull requests merged in 2022-04, with the labels that each got.

#14419 Use `jest-light-runner` from npm
  jest.config.js
  package.json
  test/jest-light-runner/package.json
  test/jest-light-runner/src/global-setup.js
  test/jest-light-runner/src/index.js
  test/jest-light-runner/src/worker-runner.js
  yarn.lock
Labels: PR: Internal :house:

#14427 Restore numeric seaprators support in `@babel/standalone`
  packages/babel-parser/src/tokenizer/index.js
  packages/babel-standalone/test/babel.js
Labels: PR: Bug Fix :bug:, pkg: standalone, i: regression

#14424 Update detection of pure nodes (`Scope#isPure`)
  packages/babel-plugin-proposal-pipeline-operator/test/fixtures/hack-caret/pipe-body-with-arrow-function-and-nested-pipe/output.js
  packages/babel-plugin-proposal-pipeline-operator/test/fixtures/hack-caret/pipe-body-with-nested-pipe/output.js
  packages/babel-plugin-proposal-pipeline-operator/test/fixtures/hack-double-at/pipe-body-with-arrow-function-and-nested-pipe/output.js
  packages/babel-plugin-proposal-pipeline-operator/test/fixtures/hack-double-at/pipe-body-with-nested-pipe/output.js
  packages/babel-plugin-proposal-pipeline-operator/test/fixtures/hack-double-caret/pipe-body-with-arrow-function-and-nested-pipe/output.js
  packages/babel-plugin-proposal-pipeline-operator/test/fixtures/hack-double-caret/pipe-body-with-nested-pipe/output.js
  packages/babel-plugin-proposal-pipeline-operator/test/fixtures/hack-hash/pipe-body-with-arrow-function-and-nested-pipe/output.js
  packages/babel-plugin-proposal-pipeline-operator/test/fixtures/hack-hash/pipe-body-with-nested-pipe/output.js
  packages/babel-plugin-proposal-pipeline-operator/test/fixtures/hack-percent/pipe-body-with-arrow-function-and-nested-pipe/output.js
  packages/babel-plugin-proposal-pipeline-operator/test/fixtures/hack-percent/pipe-body-with-nested-pipe/output.js
  packages/babel-traverse/scripts/generators/validators.js
  packages/babel-traverse/src/path/generated/validators.ts
  packages/babel-traverse/src/path/lib/virtual-types.ts
  packages/babel-traverse/src/scope/index.ts
  packages/babel-traverse/test/path/isPure.js
  packages/babel-traverse/test/scope.js
Labels: PR: Polish :nail_care:, pkg: traverse

#14462 fix: build standalone on windows
  Gulpfile.mjs
Labels: PR: Internal :house:, os: windows

#14475 chore: update compat-data
  package.json
  packages/babel-compat-data/data/plugins.json
  packages/babel-compat-data/package.json
  packages/babel-compat-data/scripts/download-compat-table.sh
  packages/babel-helper-compilation-targets/package.json
  packages/babel-preset-env/package.json
  packages/babel-preset-env/test/fixtures/debug-babel-7/browserslists-defaults-not-ie/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/browserslists-defaults/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/browserslists-last-2-versions-not-ie/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs2-electron/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs2-versions-decimals/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs3-electron/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs3-versions-decimals/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/browserslists-defaults-not-ie/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/browserslists-defaults/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/browserslists-last-2-versions-not-ie/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/entry-corejs2-electron/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/entry-corejs2-versions-decimals/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/entry-corejs3-electron/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/entry-corejs3-versions-decimals/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs2-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs2-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs2-none-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs2-none-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs2-proposals-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs2-proposals-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs2-shippedProposals-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs2-shippedProposals-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-none-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-none-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-proposals-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-proposals-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-shippedProposals-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-shippedProposals-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-versions-strings-minor-3.0-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-versions-strings-minor-3.0-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-versions-strings-minor-3.1-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-versions-strings-minor-3.1-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-no-corejs-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-no-corejs-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-no-corejs-none-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-no-corejs-none-2/stdout.txt
  yarn.lock
Labels: PR: Fixes failing main

#14464 [babel 8] Remove `selfClosing` from `jsxElement` builder
  packages/babel-types/src/definitions/jsx.ts
Labels: pkg: types, babel-8-dev → main

#14463 Build ci on windows
  .github/workflows/ci.yml
Labels: area: tests

#14479 [cli] Avoid `SourceMapGenerator` for simple map concatenation
  packages/babel-cli/package.json
  packages/babel-cli/src/babel/file.ts
  packages/babel-cli/test/fixtures/babel/filename --out-file --source-maps inline/out-files/script2.js
  packages/babel-cli/test/fixtures/babel/filename-sourcemap --out-file --source-maps inline/out-files/script2.js
  packages/babel-cli/test/fixtures/babel/filenames --out-file --source-maps inline/out-files/script3.js
  packages/babel-cli/test/fixtures/babel/filenames --out-file --source-maps/out-files/script3.js.map
  packages/babel-cli/test/fixtures/babel/stdin --out-file --source-maps/out-files/test.js.map
  packages/babel-cli/test/fixtures/babel/stdin --source-maps inline/stdout.txt
  packages/babel-core/package.json
  packages/babel-generator/package.json
  packages/babel-helper-transform-fixture-test-runner/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:, area: sourcemaps

#14003 Update rollup packages
  .yarn/patches/@rollup__plugin-commonjs.patch
  Gulpfile.mjs
  package.json
  packages/babel-standalone/src/dynamic-require-entrypoint.cjs
  packages/babel-standalone/src/index.ts
  test/runtime-integration/rollup/package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#14465 [babel 8] `ObjectTypeAnnotation` fields must always be arrays
  packages/babel-generator/test/index.js
  packages/babel-types/src/definitions/flow.ts
Labels: pkg: types, babel-8-dev → main

#14506 Do not add sourcemap markings for indentation
  packages/babel-cli/test/fixtures/babel/dir --out-dir --source-maps inline/out-files/lib/bar/bar.js
  packages/babel-cli/test/fixtures/babel/dir --out-dir --source-maps inline/out-files/lib/foo.js
  packages/babel-cli/test/fixtures/babel/dir --out-dir --source-maps/out-files/lib/bar/bar.js.map
  packages/babel-cli/test/fixtures/babel/dir --out-dir --source-maps/out-files/lib/foo.js.map
  packages/babel-cli/test/fixtures/babel/dir --out-dir --watch --verbose with external dependencies/out-files/lib/index.js
  packages/babel-cli/test/fixtures/babel/dir --out-dir --watch --verbose with external dependencies/out-files/lib/main.js
  packages/babel-cli/test/fixtures/babel/filename --out-file --source-maps inline/out-files/script2.js
  packages/babel-cli/test/fixtures/babel/filename-sourcemap --out-file --source-maps inline/out-files/script2.js
  packages/babel-cli/test/fixtures/babel/filenames --out-file --source-maps inline/out-files/script3.js
  packages/babel-cli/test/fixtures/babel/filenames --out-file --source-maps/out-files/script3.js.map
  packages/babel-cli/test/fixtures/babel/stdin --out-file --source-maps/out-files/test.js.map
  packages/babel-cli/test/fixtures/babel/stdin --source-maps inline/stdout.txt
  packages/babel-cli/test/index.js
  packages/babel-core/test/fixtures/transformation/source-maps/full/source-map.json
  packages/babel-core/test/fixtures/transformation/source-maps/inline/output.js
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-complex/source-map.json
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-complex/source-mappings.json
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-multiple-output-sources/source-map.json
  packages/babel-generator/src/buffer.ts
  packages/babel-generator/src/printer.ts
  packages/babel-generator/src/source-map.ts
  packages/babel-generator/test/fixtures/sourcemaps/call-identifiers/source-map.json
  packages/babel-generator/test/index.js
  packages/babel-helper-fixtures/src/index.ts
  packages/babel-helper-transform-fixture-test-runner/src/index.ts
Labels: PR: Polish :nail_care:, area: sourcemaps

#14509 fix: `@babel/runtime-corejs2` should depend on core-js 2
  packages/babel-runtime-corejs2/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:, i: regression

#14510 Use `maybeAddMapping` to add sourcemap markings
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-multiple-output-sources-complete-replace/source-map.json
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-multiple-output-sources/source-map.json
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-sources-complete-replace/source-map.json
  packages/babel-generator/package.json
  packages/babel-generator/src/buffer.ts
  packages/babel-generator/src/source-map.ts
  yarn.lock
Labels: area: sourcemaps
