Repository babel/babel, pull requests merged in 2022-06, with the labels that each got.

#14248 chore: automate compat-data update
  .github/workflows/update-compat-data.yml
  .github/workflows/update-parser-tests.yml
  scripts/update-compat-table/bump-compat-table-commit.sh
  scripts/update-compat-table/get-last-commit.sh
Labels: PR: Internal :house:, repo automation :robot:

#14332 docs: eslint-parser requireConfigFile behaviour
  eslint/babel-eslint-parser/README.md
Labels: PR: Docs :memo:, area: eslint

#12695 [babel 8] Disallow synchronous usage of `babel.*` callback methods
  packages/babel-core/src/config/full.ts
  packages/babel-core/src/index.ts
  packages/babel-core/src/parse.ts
  packages/babel-core/src/transform-ast.ts
  packages/babel-core/src/transform.ts
  packages/babel-core/test/api.js
  packages/babel-core/test/parse.js
  packages/babel-core/test/path.js
  packages/babel-core/test/resolution.js
  packages/babel-helper-module-imports/test/index.js
  packages/babel-helper-transform-fixture-test-runner/src/index.ts
  packages/babel-node/src/_babel-node.ts
  packages/babel-plugin-proposal-class-static-block/test/plugin-ordering.test.js
  packages/babel-plugin-syntax-decorators/test/index.js
  packages/babel-plugin-transform-modules-commonjs/test/copied-nodes.js
  packages/babel-plugin-transform-modules-commonjs/test/esmodule-flag.js
  packages/babel-plugin-transform-runtime/scripts/build-dist.js
  packages/babel-standalone/examples/example.htm
  packages/babel-standalone/src/index.ts
Labels: babel-8-dev → main

#14645 Improve `@babel/types` typings
  packages/babel-types/package.json
  packages/babel-types/scripts/generators/ast-types.js
  packages/babel-types/src/ast-types/generated/index.ts
  packages/babel-types/src/builders/validateNode.ts
  packages/babel-types/src/clone/cloneNode.ts
  packages/babel-types/src/comments/addComments.ts
  packages/babel-types/src/constants/index.ts
  packages/babel-types/src/converters/Scope.ts
  packages/babel-types/src/converters/ensureBlock.ts
  packages/babel-types/src/converters/gatherSequenceExpressions.ts
  packages/babel-types/src/converters/toBlock.ts
  packages/babel-types/src/converters/toSequenceExpression.ts
  packages/babel-types/src/converters/toStatement.ts
  packages/babel-types/src/converters/valueToNode.ts
  packages/babel-types/src/definitions/core.ts
  packages/babel-types/src/definitions/flow.ts
  packages/babel-types/src/definitions/index.ts
  packages/babel-types/src/definitions/typescript.ts
  packages/babel-types/src/definitions/utils.ts
  packages/babel-types/src/modifications/flow/removeTypeDuplicates.ts
  packages/babel-types/src/modifications/inherits.ts
  packages/babel-types/src/modifications/removeProperties.ts
  packages/babel-types/src/modifications/typescript/removeTypeDuplicates.ts
  packages/babel-types/src/retrievers/getBindingIdentifiers.ts
  packages/babel-types/src/traverse/traverseFast.ts
  packages/babel-types/src/utils/inherit.ts
  packages/babel-types/src/utils/shallowEqual.ts
  packages/babel-types/src/validators/isBinding.ts
  packages/babel-types/src/validators/isLet.ts
  packages/babel-types/src/validators/isNodesEquivalent.ts
  packages/babel-types/src/validators/isVar.ts
  packages/babel-types/src/validators/validate.ts
  scripts/generators/tsconfig.js
  tsconfig.json
  yarn.lock
Labels: PR: Internal :house:

#14641 Change limit of source map 3MB
  packages/babel-core/src/transformation/normalize-file.ts
Labels: PR: Internal :house:

#14655 fix(@babel/plugin-transform-modules-systemjs): export named from dest…
  packages/babel-plugin-transform-modules-systemjs/src/index.ts
  packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/export-named-destructuring-object/input.mjs
  packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/export-named-destructuring-object/output.mjs
Labels: PR: Bug Fix :bug:, area: modules

#14573 Fix: Temporary files created by the test are not removed.
  packages/babel-core/package.json
  packages/babel-core/test/config-chain.js
  yarn.lock
Labels: area: tests

#14611 fix: `new.target` with shadowed class name
  packages/babel-plugin-transform-new-target/src/index.ts
  packages/babel-plugin-transform-new-target/test/fixtures/general/class-properties-loose/output.js
  packages/babel-plugin-transform-new-target/test/fixtures/general/class-properties/output.js
  packages/babel-plugin-transform-new-target/test/fixtures/general/function-duplicate-name/input.js
  packages/babel-plugin-transform-new-target/test/fixtures/general/function-duplicate-name/output.js
Labels: PR: Bug Fix :bug:

#14659 Run Babel asynchronously in fixtures
  packages/babel-core/src/config/files/module-types.ts
  packages/babel-helper-transform-fixture-test-runner/src/index.ts
  packages/babel-plugin-transform-destructuring/test/fixtures/allowArrayLike/options.json
  packages/babel-plugin-transform-destructuring/test/fixtures/assumption-arrayLikeIsIterable/options.json
  packages/babel-plugin-transform-destructuring/test/fixtures/assumption-iterableIsArray/options.json
  packages/babel-plugin-transform-destructuring/test/fixtures/assumption-objectRestNoSymbols/options.json
  packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/options.json
  packages/babel-plugin-transform-destructuring/test/helpers/checkScopeInfo.js
Labels: area: tests, PR: Internal :house:

#14636 [ts] Allow `...<...>` followed by newline or binary operator
  packages/babel-parser/src/plugins/typescript/index.js
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-asi/input.ts
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-asi/output.json
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-binary-operator/input.ts
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-binary-operator/output.json
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-false-positive-3/input.ts
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-false-positive-3/options.json
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-false-positive-3/output.json
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-false-positive/input.ts
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-false-positive/output.json
  packages/babel-parser/test/fixtures/typescript/type-arguments/new-false-positive-3/output.json
Labels: PR: Spec Compliance :eyeglasses:, pkg: parser, area: typescript

#14663 Fix `import { types } from "@babel/core"` with native ESM
  babel.config.js
  packages/babel-core/src/index.ts
  packages/babel-core/test/api.js
  packages/babel-core/test/config-chain.js
  packages/babel-core/test/fixtures/babel-compile-async.mjs
  packages/babel-core/test/fixtures/babel-compile-sync.mjs
  packages/babel-core/test/fixtures/babel-load-options-async.mjs
  packages/babel-helper-check-duplicate-nodes/test/index.js
  packages/babel-plugin-bugfix-safari-id-destructuring-collision-in-function-expression/test/util.skip-bundled.js
  packages/babel-plugin-bugfix-v8-spread-parameters-in-optional-chaining/test/util.skip-bundled.js
  packages/babel-plugin-proposal-destructuring-private/test/plugin-ordering.js
  packages/babel-plugin-proposal-destructuring-private/test/util.skip-bundled.js
  packages/babel-plugin-proposal-optional-chaining/test/util.skip-bundled.js
  packages/babel-plugin-transform-runtime/scripts/build-dist.js
Labels: PR: Bug Fix :bug:

#14673 Enforce `_foo.default || _foo` to import lib files in tests
  .eslintrc.cjs
  eslint/babel-eslint-plugin-development-internal/src/index.cjs
  eslint/babel-eslint-plugin-development-internal/src/rules/require-default-import-fallback.cjs
  packages/babel-code-frame/test/index.js
  packages/babel-core/package.json
  packages/babel-core/test/api.js
  packages/babel-core/test/config-chain.js
  packages/babel-core/test/config-loading.js
  packages/babel-core/test/evaluation.js
  packages/babel-core/test/merge-map.js
  packages/babel-core/test/path.js
  packages/babel-core/test/plugins.js
  packages/babel-core/test/transformation.js
  packages/babel-generator/test/arrow-functions.js
  packages/babel-generator/test/index.js
  packages/babel-helper-annotate-as-pure/test/index.js
  packages/babel-helper-check-duplicate-nodes/test/index.js
  packages/babel-helper-compilation-targets/test/browserslist-extends/browserslist-extends.spec.js
  packages/babel-helper-compilation-targets/test/custom-browserslist-env/custom-browserslist-env.spec.js
  packages/babel-helper-compilation-targets/test/load-browserslist-package-json/load-browserslist-package-json.spec.js
  packages/babel-helper-compilation-targets/test/load-browserslistrc/load-browserslistrc.spec.js
  packages/babel-helper-compilation-targets/test/targets-parser.spec.js
  packages/babel-helper-optimise-call-expression/test/index.js
  packages/babel-helper-plugin-test-runner/esm.mjs
  packages/babel-helper-simple-access/test/index.js
  packages/babel-highlight/test/index.js
  packages/babel-parser/test/helpers/run-fixture-tests.js
  packages/babel-plugin-proposal-object-rest-spread/test/hasMoreThanOneBinding.skip-bundled.js
  packages/babel-preset-env/test/get-option-specific-excludes.spec.js
  packages/babel-preset-env/test/index.spec.js
  packages/babel-preset-env/test/normalize-options.spec.js
  packages/babel-preset-flow/test/normalize-options.spec.js
  packages/babel-preset-react/test/normalize-options.skip-bundled.js
  packages/babel-preset-typescript/test/normalize-options.skip-bundled.js
  packages/babel-template/test/index.js
  packages/babel-traverse/test/ancestry.js
  packages/babel-traverse/test/arrow-transform.js
  packages/babel-traverse/test/conversion.js
  packages/babel-traverse/test/evaluation.js
  packages/babel-traverse/test/family.js
  packages/babel-traverse/test/inference.js
  packages/babel-traverse/test/introspection.js
  packages/babel-traverse/test/modification.js
  packages/babel-traverse/test/path/isPure.js
  packages/babel-traverse/test/removal.js
  packages/babel-traverse/test/replacement.js
  packages/babel-traverse/test/scope.js
  packages/babel-traverse/test/traverse.js
  packages/babel-types/test/converters.js
  yarn.lock
Labels: area: tests

#14583 fix: Memory leak when deep cloning in `babel-core`
  packages/babel-core/package.json
  packages/babel-core/src/transformation/util/clone-deep-browser.ts
  packages/babel-core/src/transformation/util/clone-deep.ts
  packages/babel-core/test/api.js
Labels: PR: Bug Fix :bug:, pkg: core

#14669 feat: Npm cache comments for issue bot
  .github/workflows/issue-triage.yml
Labels: repo automation :robot:

#14681 Update `babel-plugin-polyfill-*` packages
  packages/babel-plugin-proposal-async-generator-functions/package.json
  packages/babel-plugin-proposal-decorators/package.json
  packages/babel-plugin-transform-runtime/package.json
  packages/babel-preset-env/package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#14685 enable TS compiler option: strictBindCallApply
  packages/babel-generator/src/generators/flow.ts
  packages/babel-generator/src/generators/modules.ts
  packages/babel-types/src/converters/valueToNode.ts
  tsconfig.base.json
Labels: PR: Internal :house:

#14686 Update to TS 4.7
  package.json
  packages/babel-helper-replace-supers/src/index.ts
  yarn.lock
Labels: PR: Dependency ⬆️

#14687 chore: Update bench baselines
  benchmark/package.json
  benchmark/update-baselines.mjs
  yarn.lock
Labels: PR: Internal :house:

#14694 fix: preserve function params type if possible
  packages/babel-plugin-transform-parameters/src/params.ts
  packages/babel-plugin-transform-parameters/test/fixtures/parameters/preserve-types/input.ts
  packages/babel-plugin-transform-parameters/test/fixtures/parameters/preserve-types/output.js
Labels: PR: Bug Fix :bug:, area: typescript

#14650 [ts] Disallow property access after instantiation expression
  packages/babel-parser/src/plugins/typescript/index.js
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-optional-chain/input.ts
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-optional-chain/output.json
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-property-access/input.ts
  packages/babel-parser/test/fixtures/typescript/type-arguments/instantiation-expression-property-access/output.json
Labels: PR: Spec Compliance :eyeglasses:, pkg: parser, area: typescript

#14697 Add `proposal-unicode-sets-regex` to `@babel/standalone`
  packages/babel-standalone/package.json
  packages/babel-standalone/scripts/pluginConfig.json
  packages/babel-standalone/src/generated/plugins.ts
  packages/babel-standalone/src/preset-stage-3.ts
  packages/babel-standalone/test/preset-stage-1.test.js
  yarn.lock
Labels: PR: Internal :house:

#14698 Update `regexpu-core`
  packages/babel-helper-create-regexp-features-plugin/package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#14699 chore: bump `@jridgewell/gen-mapping`
  packages/babel-generator/package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#14706 fix: `@babel/types` exception in typescript project.
  packages/babel-types/src/converters/toSequenceExpression.ts
Labels: PR: Bug Fix :bug:, area: typescript, i: regression

#14700 chore: update dep `@typescript-eslint`
  package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#14708 Unshadow `cjs` exports when transforming mutations
  packages/babel-helper-module-transforms/src/rewrite-live-references.ts
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/local-exports-decl-top-level/input.mjs
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/local-exports-decl-top-level/options.json
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/local-exports-decl-top-level/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/local-exports-decl-with-esm-exports/input.mjs
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/local-exports-decl-with-esm-exports/options.json
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/local-exports-decl-with-esm-exports/output.js
Labels: PR: Bug Fix :bug:, area: modules
