Repository babel/babel, pull requests merged in 2023-09, with the labels that each got.

#15908 [babel 8] Update `v8flags`
  packages/babel-node/package.json
  packages/babel-node/src/babel-node.ts
  packages/babel-node/test/fixtures.js
  yarn.lock
Labels: PR: Dependency ⬆️

#15923 Only perform config loading re-entrancy check for cjs
  packages/babel-core/src/config/files/configuration.ts
  packages/babel-core/src/config/files/module-types.ts
  packages/babel-core/test/config-loading.js
  packages/babel-core/test/fixtures/config/config-files/babel-config-mjs-object/babel.config.mjs
Labels: PR: Bug Fix :bug:, i: regression, pkg: core

#15928 Do not run flaky cli tests locally by default
  .github/workflows/ci.yml
  CONTRIBUTING.md
  packages/babel-cli/test/fixtures/babel/dir --out-dir --watch multiple dir/options.json
  packages/babel-cli/test/index.js
Labels: area: tests, pkg: cli

#15935 fix: `__esModule` is missing from published `@babel/parser`
  Gulpfile.mjs
  packages/babel-parser/src/index.ts
  packages/babel-parser/test/commonjs.bundled.js
Labels: PR: Bug Fix :bug:, pkg: parser, i: regression

#15936 Skip deprecation warning tests when in a folder named `@babel`
  packages/babel-traverse/test/traverse.js
Labels: area: tests, PR: Internal :house:

#15937 Improve test coverage for export-default-from
  packages/babel-plugin-proposal-export-default-from/src/index.ts
  packages/babel-plugin-proposal-export-default-from/test/fixtures/export-default/mixed-with-ns/input.mjs
  packages/babel-plugin-proposal-export-default-from/test/fixtures/export-default/mixed-with-ns/output.mjs
  packages/babel-plugin-proposal-export-default-from/test/fixtures/other-exports/declaration/input.mjs
  packages/babel-plugin-proposal-export-default-from/test/fixtures/other-exports/declaration/output.mjs
  packages/babel-plugin-proposal-export-default-from/test/fixtures/other-exports/named/input.mjs
  packages/babel-plugin-proposal-export-default-from/test/fixtures/other-exports/named/output.mjs
  packages/babel-plugin-proposal-export-default-from/test/fixtures/other-exports/options.json
Labels: area: tests

#15941 Fix compiling duplicate ns imports to lazy CommonJS
  packages/babel-helper-module-transforms/src/index.ts
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-dep/import-namespace-and-named/input.mjs
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-dep/import-namespace-and-named/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-dep/import-namespace-multiple/input.mjs
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-dep/import-namespace-multiple/output.js
Labels: PR: Bug Fix :bug:, area: modules

#15947 Fix compatibility with Node.js 20.6
  .circleci/config.yml
  .github/workflows/ci.yml
  babel.config.js
  jest.config.js
  packages/babel-core/src/config/files/import-meta-resolve.ts
  packages/babel-core/src/config/files/plugins.ts
Labels: PR: Bug Fix :bug:, Priority: High

#15931 Visualize source maps in tests
  packages/babel-core/test/fixtures/transformation/source-maps/arrow-function/source-map-visual.txt
  packages/babel-core/test/fixtures/transformation/source-maps/class/source-map-visual.txt
  packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-complex/source-map-visual.txt
  packages/babel-core/test/fixtures/transformation/source-maps/interpreter-directive-prefix/source-map-visual.txt
  packages/babel-helper-fixtures/src/index.ts
  packages/babel-helper-transform-fixture-test-runner/package.json
  packages/babel-helper-transform-fixture-test-runner/src/index.ts
  packages/babel-helper-transform-fixture-test-runner/src/source-map-visualizer.ts
  packages/babel-plugin-transform-destructuring/test/fixtures/sourcemap/declaration-loc/source-map-visual.txt
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/reference-source-map/source-map-visual.txt
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/strict/import/source-map-visual.txt
  packages/babel-plugin-transform-react-jsx/test/fixtures/sourcemaps/JSXText/source-map-visual.txt
  packages/babel-traverse/test/fixtures/conversion/arguments-source-maps/source-map-visual.txt
  packages/babel-traverse/test/fixtures/conversion/this-source-maps/source-map-visual.txt
  yarn.lock
Labels: area: tests, area: sourcemaps

#15898 Fix transform of named import with shadowed namespace import
  packages/babel-helper-module-transforms/src/normalize-and-load-metadata.ts
  packages/babel-plugin-transform-modules-amd/test/fixtures/amd/overview/output.js
  packages/babel-plugin-transform-modules-amd/test/fixtures/loose/overview/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/lazy-dep/import-namespace-and-named/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression/lazy-7176/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/shadowed-namespace-import/options.json
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/shadowed-namespace-import/transformed-name/input.mjs
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/shadowed-namespace-import/transformed-name/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/strict/import/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/strict/import/source-map-visual.txt
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/strict/import/source-map.json
  packages/babel-plugin-transform-modules-umd/test/fixtures/loose/overview/output.js
  packages/babel-plugin-transform-modules-umd/test/fixtures/umd/overview/output.js
Labels: PR: Bug Fix :bug:, area: modules

#15956 [babel 8] Remove `-d`/`-gc` babel-node aliases
  packages/babel-node/src/babel-node.ts
  packages/babel-node/test/fixtures.js
  packages/babel-node/test/fixtures/cli/node_-gc_alias_--expose-gc/options.json
Labels: PR: Breaking Change :boom:, PR: Needs Docs

#15957 Update identifier name definitions to Unicode 15.1
  packages/babel-helper-validator-identifier/package.json
  packages/babel-helper-validator-identifier/scripts/generate-identifier-regex.js
  packages/babel-helper-validator-identifier/src/identifier.ts
  packages/babel-helper-validator-identifier/test/identifier.spec.js
  yarn.lock
Labels: PR: Bug Fix :bug:, pkg: parser

#15965 Revert Node.js 20.6.0 bug workaround
  babel.config.js
Labels: PR: Revert :leftwards_arrow_with_hook:

#15974 Update Unicode test fixtures
  packages/babel-plugin-transform-dotall-regex/test/fixtures/dotall-regex/with-unicode-property-escape/output.js
  yarn.lock
Labels: PR: Internal :house:, PR: Fixes failing main

#15973 Remove special-casing of U+200C and U+200D
  packages/babel-helper-validator-identifier/scripts/generate-identifier-regex.js
Labels: PR: Internal :house:

#15962 fix: `transform-block-scoping` captures the variables of the method in the loop
  packages/babel-plugin-transform-block-scoping/src/loop.ts
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/loop-closure-in-method/exec.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/loop-closure-in-method/input.js
  packages/babel-plugin-transform-block-scoping/test/fixtures/general/loop-closure-in-method/output.js
Labels: PR: Bug Fix :bug:, i: regression

#15909 Update `convert-source-map`
  packages/babel-cli/package.json
  packages/babel-cli/src/babel/options.ts
  packages/babel-core/package.json
  packages/babel-core/src/config/validation/options.ts
  packages/babel-core/src/transformation/normalize-file.ts
  packages/babel-core/test/api.js
  packages/babel-core/test/option-manager.js
  packages/babel-parser/src/util/identifier.ts
  packages/babel-standalone/src/index.ts
  yarn.lock
Labels: PR: Dependency ⬆️

#15878 Implement `import defer` proposal transform support
  packages/babel-helper-module-transforms/src/index.ts
  packages/babel-helper-module-transforms/src/lazy-modules.ts
  packages/babel-helper-module-transforms/src/normalize-and-load-metadata.ts
  packages/babel-helper-module-transforms/src/rewrite-live-references.ts
  packages/babel-helpers/src/helpers-generated.ts
  packages/babel-helpers/src/helpers/importDeferProxy.js
  packages/babel-plugin-proposal-import-defer/.npmignore
  packages/babel-plugin-proposal-import-defer/README.md
  packages/babel-plugin-proposal-import-defer/package.json
  packages/babel-plugin-proposal-import-defer/src/index.ts
  packages/babel-plugin-proposal-import-defer/test/fixtures/esm-to-commonjs-lazy/integration/input.mjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/esm-to-commonjs-lazy/integration/options.json
  packages/babel-plugin-proposal-import-defer/test/fixtures/esm-to-commonjs-lazy/integration/output.js
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/get-own-property-names/dep.cjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/get-own-property-names/exec.js
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/get-own-property-names/side-channel.cjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/not-referenced/dep.cjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/not-referenced/exec.js
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/not-referenced/side-channel.cjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/options.json
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/reference-plain-only/dep.cjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/reference-plain-only/exec.js
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/reference-plain-only/side-channel.cjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/reference-property-only/dep.cjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/reference-property-only/exec.js
  packages/babel-plugin-proposal-import-defer/test/fixtures/exec/reference-property-only/side-channel.cjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/not-referenced/input.mjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/not-referenced/output.js
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/options.json
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/reference-plain-and-property/input.mjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/reference-plain-and-property/output.js
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/reference-plain-only/input.mjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/reference-plain-only/output.js
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/reference-property-and-plain/input.mjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/reference-property-and-plain/output.js
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/reference-property-only/input.mjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/reference-property-only/output.js
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/with-full-import-after/input.mjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/with-full-import-after/output.js
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/with-full-import-before/input.mjs
  packages/babel-plugin-proposal-import-defer/test/fixtures/transform/with-full-import-before/output.js
  packages/babel-plugin-proposal-import-defer/test/index.js
  packages/babel-plugin-proposal-import-defer/test/package.json
  packages/babel-plugin-syntax-import-defer/README.md
  packages/babel-plugin-syntax-import-defer/package.json
  packages/babel-plugin-syntax-import-defer/src/index.ts
  packages/babel-plugin-transform-modules-commonjs/src/hooks.ts
  packages/babel-plugin-transform-modules-commonjs/src/index.ts
  packages/babel-plugin-transform-modules-commonjs/src/lazy.ts
  packages/babel-runtime-corejs2/package.json
  packages/babel-runtime-corejs3/package.json
  packages/babel-runtime/package.json
  packages/babel-standalone/package.json
  packages/babel-standalone/scripts/pluginConfig.json
  packages/babel-standalone/src/generated/plugins.ts
  tsconfig.json
  yarn.lock
Labels: PR: New Feature :rocket:, PR: Needs Docs, Spec: Deferred Module Evaluation

#15985 Improve source maps for blocks with `using` declarations
  packages/babel-plugin-proposal-explicit-resource-management/src/index.ts
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/block/input.js
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/block/output.js
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/block/source-map-visual.txt
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/block/source-map.json
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/for-of/input.js
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/for-of/output.js
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/for-of/source-map-visual.txt
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/for-of/source-map.json
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/options.json
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/top-level/input.mjs
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/top-level/output.mjs
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/top-level/source-map-visual.txt
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/top-level/source-map.json
Labels: PR: Polish :nail_care:, area: sourcemaps, Spec: Explicit Resource Management

#15896 Allow TS tuples to have both labeled and unlabeled elements
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/test/fixtures/typescript/types/tuple-labeled-after-unlabeled/output.json
  packages/babel-parser/test/fixtures/typescript/types/tuple-labeled-before-unlabeled/output.json
  packages/babel-parser/test/fixtures/typescript/types/tuple-unlabeled-spread-after-labeled/output.json
  packages/babel-parser/test/fixtures/typescript/types/tuple-unlabeled-spread-before-labeled/output.json
Labels: PR: New Feature :rocket:, pkg: parser, area: typescript, PR: Ready to be Merged

#15913 Add `rewriteImportExtensions` option to TS preset
  packages/babel-preset-typescript/src/index.ts
  packages/babel-preset-typescript/src/normalize-options.ts
  packages/babel-preset-typescript/src/plugin-rewrite-ts-imports.ts
  packages/babel-preset-typescript/test/fixtures/opts/rewriteImportExtensions/input.ts
  packages/babel-preset-typescript/test/fixtures/opts/rewriteImportExtensions/options.json
  packages/babel-preset-typescript/test/fixtures/opts/rewriteImportExtensions/output.mjs
  packages/babel-preset-typescript/test/normalize-options.skip-bundled.js
Labels: PR: New Feature :rocket:, area: typescript, PR: Ready to be Merged

#15797 Expand evaluation of global built-ins in `@babel/traverse`
  packages/babel-traverse/src/path/evaluation.ts
  packages/babel-traverse/test/evaluation.js
Labels: PR: Polish :nail_care:, pkg: traverse, PR: Ready to be Merged

#15893 Add `t.buildUndefinedNode`
  packages/babel-traverse/src/scope/index.ts
  packages/babel-types/src/builders/productions.ts
  packages/babel-types/src/index.ts
Labels: PR: New Feature :rocket:

#15895 Implement the "decorator metadata" proposal
  packages/babel-helpers/src/helpers-generated.ts
  packages/babel-helpers/src/helpers/applyDecs2305.js
  packages/babel-plugin-proposal-decorators/src/transformer-2023-05.ts
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-assumption-constantSuper/super-in-nested-constructor-expression/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-assumption-constantSuper/super-in-private-accessor/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-assumption-constantSuper/super-in-private-method/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-classes--to-es2015/expressions-static-blocks/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-classes--to-es2015/expressions/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-classes--to-es2015/inheritance/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-classes--to-es2015/initializers/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-classes/expressions-static-blocks/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-classes/expressions/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-classes/inheritance/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-classes/initializers/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-misc--to-es2015/initProto-existing-derived-constructor/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-misc/initProto-existing-derived-constructor-multiple-super/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-misc/initProto-existing-derived-constructor/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-misc/super-in-nested-constructor-expression/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-misc/super-in-private-accessor/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-misc/super-in-private-method/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/metadata/class/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/metadata/element/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/metadata/no-decorators/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/metadata/options.json
  packages/babel-plugin-proposal-decorators/test/fixtures/metadata/subclass-no-super-decorators/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/metadata/subclass-super-decorators/exec.js
Labels: PR: New Feature :rocket:, Spec: Decorators, PR: Ready to be Merged

#15671 Pass through nonce to the transformed script element
  packages/babel-standalone/package.json
  packages/babel-standalone/src/transformScriptTags.ts
  packages/babel-standalone/test/transform-script-tags.test.js
  scripts/repo-utils/index.cjs
  scripts/repo-utils/index.d.ts
  yarn.lock
Labels: PR: New Feature :rocket:, pkg: standalone, PR: Ready to be Merged

#15996 Update `regexpu-core`
  packages/babel-helper-create-regexp-features-plugin/package.json
  packages/babel-helper-create-regexp-features-plugin/src/util.ts
  packages/babel-plugin-transform-unicode-regex/test/fixtures/unicode-regex/negated-set/output.js
  yarn.lock
Labels: PR: Dependency ⬆️
