Repository babel/babel, pull requests merged in 2023-08, with the labels that each got.

#15759 [babel 8] Reland "Use `NodePath#hub` as part of the paths cache key"
  .github/workflows/e2e-tests-breaking.yml
  packages/babel-core/src/transformation/index.ts
  packages/babel-traverse/package.json
  packages/babel-traverse/src/cache.ts
  packages/babel-traverse/src/index.ts
  packages/babel-traverse/src/path/index.ts
  packages/babel-traverse/src/path/modification.ts
  packages/babel-traverse/src/path/removal.ts
  packages/babel-traverse/src/path/replacement.ts
  packages/babel-traverse/src/traverse-node.ts
  packages/babel-traverse/test/hub.js
  yarn.lock
Labels: babel 8

#15831 Update Jest
  babel.config.js
  package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#15836 Enable Babel e2e test for Babel 8 with ESM
  .github/workflows/e2e-tests-breaking-esm.yml
  scripts/integration-tests/e2e-babel.sh
Labels: area: tests

#15837 Remove Babel 7 e2e ESM tests
  .github/workflows/e2e-tests-esm.yml
Labels: area: tests

#15842 Materialize conditional dependencies when bundling
  Gulpfile.mjs
  scripts/rollup-plugin-dependency-condition.js
Labels: pkg: standalone, i: regression

#15850 Support configuring cache in ESM configs
  packages/babel-core/src/config/files/configuration.ts
  packages/babel-core/test/async.js
  packages/babel-core/test/fixtures/async/config-file-async-function/babel.config.js
  packages/babel-core/test/fixtures/async/config-file-mjs-cache/babel.config.mjs
  packages/babel-core/test/fixtures/async/config-file-mjs-cache/plugin.js
Labels: PR: Bug Fix :bug:

#15847 Provide better error message when allowDeclareFields is enabled
  packages/babel-preset-typescript/src/normalize-options.ts
  packages/babel-preset-typescript/test/fixtures/opts/allowDeclareFields/input.ts
  packages/babel-preset-typescript/test/fixtures/opts/allowDeclareFields/options.json
Labels: PR: Polish (next major) :nail_care:

#15823 [babel 8] Do not use syntax plugins for syntax enabled by default
  codemods/babel-plugin-codemod-object-assign-to-object-spread/package.json
  codemods/babel-plugin-codemod-object-assign-to-object-spread/src/index.ts
  codemods/babel-plugin-codemod-optional-catch-binding/package.json
  codemods/babel-plugin-codemod-optional-catch-binding/src/index.ts
  packages/babel-helper-create-class-features-plugin/package.json
  packages/babel-helper-create-class-features-plugin/test/fixtures/missing-class-static-blocks-plugin/basic/options.json
  packages/babel-plugin-transform-async-generator-functions/package.json
  packages/babel-plugin-transform-async-generator-functions/src/index.ts
  packages/babel-plugin-transform-class-static-block/package.json
  packages/babel-plugin-transform-class-static-block/src/index.ts
  packages/babel-plugin-transform-dynamic-import/package.json
  packages/babel-plugin-transform-dynamic-import/src/index.ts
  packages/babel-plugin-transform-export-namespace-from/package.json
  packages/babel-plugin-transform-export-namespace-from/src/index.ts
  packages/babel-plugin-transform-json-strings/package.json
  packages/babel-plugin-transform-json-strings/src/index.ts
  packages/babel-plugin-transform-logical-assignment-operators/package.json
  packages/babel-plugin-transform-logical-assignment-operators/src/index.ts
  packages/babel-plugin-transform-modules-commonjs/package.json
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/class-static-block/options.json
  packages/babel-plugin-transform-modules-systemjs/package.json
  packages/babel-plugin-transform-nullish-coalescing-operator/package.json
  packages/babel-plugin-transform-nullish-coalescing-operator/src/index.ts
  packages/babel-plugin-transform-numeric-separator/package.json
  packages/babel-plugin-transform-numeric-separator/src/index.ts
  packages/babel-plugin-transform-object-rest-spread/package.json
  packages/babel-plugin-transform-object-rest-spread/src/index.ts
  packages/babel-plugin-transform-optional-catch-binding/package.json
  packages/babel-plugin-transform-optional-catch-binding/src/index.ts
  packages/babel-plugin-transform-optional-chaining/package.json
  packages/babel-plugin-transform-optional-chaining/src/index.ts
  packages/babel-plugin-transform-private-property-in-object/package.json
  packages/babel-plugin-transform-private-property-in-object/src/index.ts
  yarn.lock
Labels: PR: Internal (next major) :house:

#15853 Update Babel 8 release process
  .github/CHANGELOG-v8.md
  .github/workflows/release.yml
  Makefile
  Makefile.js
  Makefile.source.mjs
Labels: repo automation :robot:

#15858 fix(standalone): strip archived syntax plugins
  packages/babel-plugin-transform-async-generator-functions/src/index.ts
  packages/babel-plugin-transform-class-static-block/src/index.ts
  packages/babel-plugin-transform-dynamic-import/src/index.ts
  packages/babel-plugin-transform-export-namespace-from/src/index.ts
  packages/babel-plugin-transform-json-strings/src/index.ts
  packages/babel-plugin-transform-logical-assignment-operators/src/index.ts
  packages/babel-plugin-transform-nullish-coalescing-operator/src/index.ts
  packages/babel-plugin-transform-numeric-separator/src/index.ts
  packages/babel-plugin-transform-object-rest-spread/src/index.ts
  packages/babel-plugin-transform-optional-catch-binding/src/index.ts
  packages/babel-plugin-transform-optional-chaining/src/index.ts
  packages/babel-plugin-transform-private-property-in-object/src/index.ts
Labels: PR: Bug Fix :bug:, pkg: standalone, i: regression

#15846 Use Babel 8.0 alpha to build babel
  .github/workflows/ci.yml
  babel.config.js
  package.json
  yarn.lock
Labels: PR: Internal :house:

#15833 bump json5, terser and webpack, further minimize babel helpers
  Makefile.js
  packages/babel-core/package.json
  packages/babel-helpers/package.json
  packages/babel-helpers/scripts/generate-helpers.js
  packages/babel-helpers/src/helpers-generated.ts
  packages/babel-plugin-transform-async-generator-functions/test/fixtures/regression/13801/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression/T7199/output.js
  packages/babel-plugin-transform-regenerator/test/fixtures/misc/no-external-helpers/output.js
  packages/babel-preset-env/test/fixtures/corejs2-babel-7/usage-regenerator-used-async/output.mjs
  packages/babel-preset-env/test/fixtures/corejs2-babel-7/usage-regenerator-used-generator/output.mjs
  packages/babel-preset-env/test/fixtures/corejs2-babel-7/usage-shippedProposals/output.js
  packages/babel-preset-env/test/fixtures/corejs2/usage-shippedProposals/output.js
  packages/babel-preset-env/test/fixtures/corejs3-babel-7/usage-regenerator-used-async/output.mjs
  packages/babel-preset-env/test/fixtures/corejs3-babel-7/usage-regenerator-used-generator/output.mjs
  packages/babel-preset-env/test/regressions.js
  packages/babel-runtime-corejs2/helpers/typeof.js
  packages/babel-runtime-corejs3/helpers/dispose.js
  packages/babel-runtime/helpers/dispose.js
  packages/babel-runtime/helpers/typeof.js
  test/runtime-integration/webpack-5/package.json
  yarn.lock
Labels: PR: Internal :house:, PR: Dependency ⬆️

#15863 chore: Update deps
  Gulpfile.mjs
  package.json
  scripts/pack-script.js
  scripts/repo-utils/index.cjs
  yarn.lock
Labels: PR: Dependency ⬆️

#15867 fix: definition of TS function type params
  packages/babel-types/src/ast-types/generated/index.ts
  packages/babel-types/src/builders/generated/index.ts
  packages/babel-types/src/definitions/typescript.ts
Labels: PR: Bug Fix :bug:, area: typescript, pkg: types

#15038 Update to Rollup 3.2.3
  Gulpfile.mjs
  Makefile.js
  package.json
  packages/babel-traverse/src/scope/binding.ts
  yarn.lock
Labels: PR: Dependency ⬆️

#15829 Add parsing support for the "source phase imports" proposal
  packages/babel-generator/src/generators/modules.ts
  packages/babel-generator/test/fixtures/import-phases/options.json
  packages/babel-generator/test/fixtures/import-phases/source-declaration/input.js
  packages/babel-generator/test/fixtures/import-phases/source-declaration/output.js
  packages/babel-generator/test/fixtures/import-phases/source-expression/input.js
  packages/babel-generator/test/fixtures/import-phases/source-expression/output.js
  packages/babel-parser/data/schema.json
  packages/babel-parser/src/parse-error/standard-errors.ts
  packages/babel-parser/src/parser/expression.ts
  packages/babel-parser/src/parser/statement.ts
  packages/babel-parser/src/tokenizer/types.ts
  packages/babel-parser/src/types.d.ts
  packages/babel-parser/src/typings.d.ts
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/attributes-declaration/input.js
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/attributes-declaration/options.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/attributes-declaration/output.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/attributes-expression/input.js
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/attributes-expression/options.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/attributes-expression/output.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/dynamic-import-no-createImportExpressions/input.js
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/dynamic-import-no-createImportExpressions/options.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/dynamic-import/input.js
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/dynamic-import/options.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/dynamic-import/output.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/import-default-binding-source/input.js
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/import-default-binding-source/output.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/import-source-binding-from/input.js
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/import-source-binding-from/output.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/import-source-binding-source/input.js
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/import-source-binding-source/output.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/import-source/input.js
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/import-source/output.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/no-named/input.js
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/no-named/output.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/no-namespace/input.js
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/no-namespace/output.json
  packages/babel-parser/test/fixtures/experimental/source-phase-imports/options.json
  packages/babel-parser/typings/babel-parser.d.ts
  packages/babel-types/src/ast-types/generated/index.ts
  packages/babel-types/src/definitions/core.ts
Labels: PR: New Feature :rocket:, pkg: generator, pkg: parser, pkg: types, PR: Ready to be Merged, PR: Needs Docs

#15869 disallow createConfigItem,loadPartialConfig,loadOptions sync usage
  eslint/babel-eslint-parser/src/worker/babel-core.cjs
  eslint/babel-eslint-parser/src/worker/maybeParse.cjs
  packages/babel-core/src/config/index.ts
  packages/babel-core/src/config/partial.ts
  packages/babel-core/test/assumptions.js
  packages/babel-core/test/config-chain.js
  packages/babel-core/test/config-loading.js
  packages/babel-core/test/targets.js
Labels: PR: Breaking Change :boom:

#15871 Simplify `?.` output when chain result is ignored
  packages/babel-plugin-bugfix-v8-spread-parameters-in-optional-chaining/test/fixtures/assumption-noDocumentAll/basic/output.mjs
  packages/babel-plugin-bugfix-v8-spread-parameters-in-optional-chaining/test/fixtures/assumption-pureGetters/function-call/output.js
  packages/babel-plugin-bugfix-v8-spread-parameters-in-optional-chaining/test/fixtures/basic/basic-integration-optional-chaining/output.mjs
  packages/babel-plugin-bugfix-v8-spread-parameters-in-optional-chaining/test/fixtures/basic/basic/output.mjs
  packages/babel-plugin-transform-class-properties/test/fixtures/private-loose/optional-chain-member-optional-call-with-transform/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private/optional-chain-member-optional-call-with-transform/output.js
  packages/babel-plugin-transform-classes/test/fixtures/assumption-constantSuper/accessing-super-property-optional-chain/output.js
  packages/babel-plugin-transform-classes/test/fixtures/loose/accessing-super-property-optional-chain/output.js
  packages/babel-plugin-transform-classes/test/fixtures/spec/accessing-super-property-optional-chain/output.js
  packages/babel-plugin-transform-optional-chaining/src/transform.ts
  packages/babel-plugin-transform-optional-chaining/test/fixtures/assumption-noDocumentAll/memoize/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/assumption-noDocumentAll/optional-eval-call/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/assumption-pureGetters/function-call/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/assumption-pureGetters/memoize/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/general/function-call-loose/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/general/function-call-spread/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/general/function-call/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/general/member-access/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/general/memoize-loose/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/general/memoize/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/general/optional-eval-call-loose/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/general/optional-eval-call/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/regression/10959-transform-optional-chaining/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/regression/10959-transform-ts-and-optional-chaining/output.js
  packages/babel-preset-env/test/fixtures/bugfixes/v8-spread-parameters-in-optional-chaining-chrome-89-no-bugfixes/output.js
Labels: Spec: Optional Chaining, PR: Output optimization :microscope:

#15872 enable jest/no-standalone-expect
  eslint.config.js
  eslint/babel-eslint-parser/test/index.js
  eslint/babel-eslint-tests/test/integration/config-files.js
  eslint/babel-eslint-tests/test/integration/parser-override.js
  packages/babel-core/test/api.js
  packages/babel-core/test/async.js
  packages/babel-core/test/config-loading.js
  packages/babel-core/test/errors-stacks.js
  packages/babel-core/test/option-manager.js
  packages/babel-core/test/resolution.js
  packages/babel-helper-compilation-targets/test/targets-parser.spec.js
  packages/babel-parser/test/plugin-options.js
  packages/babel-plugin-proposal-destructuring-private/test/util.skip-bundled.js
  packages/babel-plugin-syntax-decorators/test/index.js
  packages/babel-preset-env/test/regressions.js
  packages/babel-preset-react/test/index.js
  packages/babel-register/test/index.js
  packages/babel-traverse/test/visitors.js
  packages/babel-types/test/regressions.js
  scripts/integration-tests/e2e-babel-old-version.sh
  scripts/repo-utils/index.cjs
Labels: area: tests, PR: Internal :house:

#15882 Fix: fully remove TS nested type-only exported namespaces
  packages/babel-plugin-transform-typescript/src/namespace.ts
  packages/babel-plugin-transform-typescript/test/fixtures/namespace/nested-namespace/input.ts
  packages/babel-plugin-transform-typescript/test/fixtures/namespace/nested-namespace/output.mjs
Labels: PR: Bug Fix :bug:, area: typescript

#15888 Fix optional chain optimization in sequence expression
  packages/babel-plugin-transform-optional-chaining/src/transform.ts
  packages/babel-plugin-transform-optional-chaining/test/fixtures/general/member-access/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/regression/15887/exec.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/regression/15887/input.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/regression/15887/output.js
Labels: PR: Bug Fix :bug:, i: regression

#15883 Update `jest-light-runner`, enable `source-map-support`
  jest.config.js
  package.json
  packages/babel-core/test/errors-stacks.js
  yarn.lock
Labels: PR: Dependency ⬆️

#15792 [babel 8] Use ESM-based `chalk@5`
  .github/workflows/ci.yml
  .yarn/plugins/@yarnpkg/plugin-conditions.cjs
  babel.config.js
  package.json
  packages/babel-code-frame/package.json
  packages/babel-code-frame/src/index.ts
  packages/babel-code-frame/test/index.js
  packages/babel-highlight/package.json
  packages/babel-highlight/src/index.ts
  packages/babel-highlight/test/index.js
  test/esm/package.json
  yarn.lock
Labels: PR: Dependency ⬆️, PR: Internal (next major) :house:

#15890 Improve helper-fixtures
  packages/babel-helper-fixtures/package.json
  packages/babel-helper-fixtures/src/index.ts
  packages/babel-plugin-proposal-function-bind/test/fixtures/function-bind/complex-call/exec.mjs
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/copy-getters-setters-star/exec.mjs
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/copy-getters-setters/exec.mjs
  packages/babel-preset-env/test/fixtures/plugins-integration/issue-7527/exec.mjs
  yarn.lock
Labels: area: tests, PR: Internal :house:

#15907 Avoid dynamic require call in preset-env
  babel.config.js
  packages/babel-preset-env/src/available-plugins.ts
Labels: PR: Bug Fix :bug:, i: regression, pkg: preset-env

#15902 extract more test helpers to repo-utils
  babel.config.js
  eslint/babel-eslint-parser/test/index.js
  eslint/babel-eslint-tests/test/integration/config-files.js
  packages/babel-core/test/api.js
  packages/babel-core/test/async.js
  packages/babel-core/test/config-loading.js
  packages/babel-core/test/esm-cjs-integration.js
  packages/babel-core/test/helpers/esm.js
  packages/babel-core/test/option-manager.js
  packages/babel-helper-compilation-targets/test/targets-parser.spec.js
  packages/babel-helper-simple-access/test/index.js
  packages/babel-parser/test/plugin-options.js
  packages/babel-plugin-syntax-decorators/test/index.js
  packages/babel-preset-env/test/import-meta.js
  packages/babel-preset-env/test/index.skip-bundled.js
  packages/babel-preset-env/test/normalize-options.skip-bundled.js
  packages/babel-preset-env/test/regressions.js
  packages/babel-preset-flow/test/normalize-options.skip-bundled.js
  packages/babel-preset-react/test/index.js
  packages/babel-preset-react/test/normalize-options.skip-bundled.js
  packages/babel-preset-typescript/test/normalize-options.skip-bundled.js
  packages/babel-traverse/test/arrow-transform.js
  packages/babel-traverse/test/hub.js
  packages/babel-traverse/test/visitors.js
  packages/babel-types/test/builders/core.js
  packages/babel-types/test/builders/typescript/tsTypeParameter.js
  packages/babel-types/test/regressions.js
  scripts/repo-utils/index.cjs
  scripts/repo-utils/index.d.ts
Labels: area: tests, PR: Internal :house:

#15910 Refine `LetInLexicalBinding` error message
  packages/babel-parser/src/parse-error/standard-errors.ts
  packages/babel-parser/test/fixtures/es2015/let/let-at-binding-list-fail-1/output.json
  packages/babel-parser/test/fixtures/es2015/let/let-at-binding-list-fail-10/output.json
  packages/babel-parser/test/fixtures/es2015/let/let-at-binding-list-fail-11/output.json
  packages/babel-parser/test/fixtures/es2015/let/let-at-binding-list-fail-12/output.json
  packages/babel-parser/test/fixtures/es2015/let/let-at-binding-list-fail-2/output.json
  packages/babel-parser/test/fixtures/es2015/let/let-at-binding-list-fail-3/output.json
  packages/babel-parser/test/fixtures/es2015/let/let-at-binding-list-fail-4/output.json
  packages/babel-parser/test/fixtures/es2015/let/let-at-binding-list-fail-5/output.json
  packages/babel-parser/test/fixtures/es2015/let/let-at-binding-list-fail-6/output.json
  packages/babel-parser/test/fixtures/es2015/let/let-at-binding-list-fail-7/output.json
  packages/babel-parser/test/fixtures/es2015/let/let-at-binding-list-fail-8/output.json
  packages/babel-parser/test/fixtures/es2015/let/let-at-binding-list-fail-9/output.json
  packages/babel-parser/test/fixtures/es2015/let/let-at-catch-block/output.json
  packages/babel-parser/test/fixtures/experimental/async-explicit-resource-management/invalid-using-binding-let/output.json
  packages/babel-parser/test/fixtures/experimental/explicit-resource-management/invalid-using-binding-let/output.json
Labels: pkg: parser, area: errors
