Repository babel/babel, pull requests merged in 2024-12, with the labels that each got.

#16959 perf: Reduce the use of temporary objects
  packages/babel-generator/src/generators/base.ts
  packages/babel-generator/src/generators/classes.ts
  packages/babel-generator/src/generators/expressions.ts
  packages/babel-generator/src/generators/flow.ts
  packages/babel-generator/src/generators/jsx.ts
  packages/babel-generator/src/generators/modules.ts
  packages/babel-generator/src/generators/statements.ts
  packages/babel-generator/src/generators/types.ts
  packages/babel-generator/src/generators/typescript.ts
  packages/babel-generator/src/printer.ts
Labels: pkg: generator, PR: Performance :running_woman:

#16927 [react] Only default to `development` when set through env
  packages/babel-preset-react/src/index.ts
  packages/babel-preset-react/src/normalize-options.ts
  packages/babel-preset-react/test/index.js
  packages/babel-preset-react/test/normalize-options.skip-bundled.js
  packages/babel-standalone/test/babel.js
Labels: PR: Needs Docs, PR: Bug Fix (next major) :bug:

#16995 Update tests for Node.js 22.12
  eslint.config.mjs
  packages/babel-core/test/async.js
  packages/babel-core/test/config-chain.js
  packages/babel-core/test/esm-cjs-integration.js
  packages/babel-helper-transform-fixture-test-runner/src/index.ts
  packages/babel-register/test/index.js
Labels: PR: Fixes failing main

#17005 Revert "perf: Improve scope information collection performance"
  packages/babel-traverse/src/path/context.ts
  packages/babel-traverse/src/path/lib/virtual-types.ts
  packages/babel-traverse/src/scope/index.ts
  packages/babel-traverse/src/scope/traverseForScope.ts
  packages/babel-traverse/src/visitors.ts
Labels: PR: Revert :leftwards_arrow_with_hook:

#17007 fix: migrate to dirent.parentPath
  packages/babel-cli/src/babel/util.ts
  packages/babel-helper-transform-fixture-test-runner/src/index.ts
Labels: PR: Internal (next major) :house:

#17010 fix: build updated babel-type helpers
  Gulpfile.mjs
  package.json
  yarn.lock
Labels: PR: Bug Fix (next major) :bug:

#16996 [estree] Adjust the start loc of class methods with type params
  packages/babel-parser/src/plugins/estree.ts
  packages/babel-parser/test/fixtures/estree/class-method/flow/output.json
  packages/babel-parser/test/fixtures/estree/class-method/typescript-type-param-babel-7/input.js
  packages/babel-parser/test/fixtures/estree/class-method/typescript-type-param-babel-7/options.json
  packages/babel-parser/test/fixtures/estree/class-method/typescript-type-param-babel-7/output.json
  packages/babel-parser/test/fixtures/estree/class-method/typescript-type-params/input.js
  packages/babel-parser/test/fixtures/estree/class-method/typescript-type-params/options.json
  packages/babel-parser/test/fixtures/estree/class-method/typescript-type-params/output.json
Labels: PR: Bug Fix :bug:, pkg: parser, area: estree

#17013 fix: Correctly set position for `@(a.b)()`
  packages/babel-parser/src/parser/statement.ts
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/test/fixtures/experimental/decorators/parenthesized-allowCallParenthesized-false-invalid/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/parenthesized-allowCallParenthesized-true/output.json
  packages/babel-parser/test/fixtures/experimental/decorators/parenthesized/output.json
Labels: PR: Bug Fix :bug:, pkg: parser, Spec: Decorators

#17017 [Babel 8]: rename `typeParameters` to `typeArguments` for `TSClassImplements` and `TSInterfaceHeritage`
  packages/babel-generator/src/generators/deprecated.ts
  packages/babel-generator/src/generators/typescript.ts
  packages/babel-generator/src/printer.ts
  packages/babel-generator/test/printer.skip-bundled.js
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/src/types.ts
  packages/babel-parser/test/fixtures/typescript/class/expression-extends-implements-babel-7/options.json
  packages/babel-parser/test/fixtures/typescript/class/expression-extends-implements/options.json
  packages/babel-parser/test/fixtures/typescript/class/expression-extends-implements/output.json
  packages/babel-parser/test/fixtures/typescript/class/expression-implements/output.json
  packages/babel-parser/test/fixtures/typescript/class/extends-implements-babel-7/options.json
  packages/babel-parser/test/fixtures/typescript/class/extends-implements/options.json
  packages/babel-parser/test/fixtures/typescript/class/extends-implements/output.json
  packages/babel-parser/test/fixtures/typescript/class/implements/output.json
  packages/babel-parser/test/fixtures/typescript/interface/extends/output.json
  packages/babel-parser/test/fixtures/typescript/type-arguments/empty-interface-extends/output.json
  packages/babel-parser/test/fixtures/typescript/type-arguments/empty-interface-implements/output.json
  packages/babel-parser/test/fixtures/typescript/types/variance-annotations-babel-7/options.json
  packages/babel-parser/test/fixtures/typescript/types/variance-annotations-with-jsx-babel-7/options.json
  packages/babel-parser/test/fixtures/typescript/types/variance-annotations-with-jsx/options.json
  packages/babel-parser/test/fixtures/typescript/types/variance-annotations-with-jsx/output.json
  packages/babel-parser/test/fixtures/typescript/types/variance-annotations/options.json
  packages/babel-parser/test/fixtures/typescript/types/variance-annotations/output.json
  packages/babel-types/src/definitions/typescript.ts
  scripts/generate-babel-7-tests.mjs
Labels: PR: Breaking Change :boom:

#17018 chore: Pack some parser options into a number
  packages/babel-parser/src/options.ts
  packages/babel-parser/src/parser/base.ts
  packages/babel-parser/src/parser/expression.ts
  packages/babel-parser/src/parser/index.ts
  packages/babel-parser/src/parser/node.ts
  packages/babel-parser/src/parser/statement.ts
  packages/babel-parser/src/plugins/estree.ts
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/src/tokenizer/index.ts
Labels: pkg: parser

#17019 Fix incomplete visitor keys
  packages/babel-generator/src/generators/typescript.ts
  packages/babel-generator/test/fixtures/typescript/types-import-type-with-options/input.js
  packages/babel-generator/test/fixtures/typescript/types-import-type-with-options/output.js
  packages/babel-parser/test/fixtures/estree/typescript/import-with-options/input.js
  packages/babel-parser/test/fixtures/estree/typescript/import-with-options/output.json
  packages/babel-types/src/definitions/core.ts
  packages/babel-types/src/definitions/flow.ts
  packages/babel-types/src/definitions/jsx.ts
  packages/babel-types/src/definitions/typescript.ts
  packages/babel-types/test/fields.js
Labels: PR: Bug Fix :bug:, pkg: generator, pkg: types

#17022 Fix failing CI due to Node.js 22.12
  .github/workflows/ci.yml
  .github/workflows/e2e-tests-breaking-esm.yml
  .github/workflows/e2e-tests.yml
  scripts/integration-tests/e2e-jest.sh
  test/runtime-integration/expected-cjs-22.11.txt
  test/runtime-integration/expected-cjs-absolute-22.11.txt
  test/runtime-integration/expected-esm-22.11.txt
  test/runtime-integration/node.cjs
Labels: PR: Fixes failing main
