Repository babel/babel, pull requests merged in 2024-05, with the labels that each got.

#16464 bump import-meta-resolve to 4.1.0
  package.json
  packages/babel-code-frame/package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#16469 add install step before building example project
  scripts/integration-tests/e2e-react-native.sh
Labels: PR: Fixes failing main

#16466 Migrate import assertions syntax
  scripts/generators/archived-libs-typings.js
  scripts/generators/tsconfig.js
  scripts/integration-tests/utils/bump-babel-dependencies.js
  scripts/parser-tests/test262/index.js
  scripts/rename-proposal-to-transform.js
  scripts/rollup-plugin-standalone-internals.js
Labels: PR: Internal :house:

#16476 fix: Correctly parse `cls.fn<C> = x`
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/test/fixtures/typescript/assign/TSTypeParameterInstantiation-babel-7/input.ts
  packages/babel-parser/test/fixtures/typescript/assign/TSTypeParameterInstantiation-babel-7/options.json
  packages/babel-parser/test/fixtures/typescript/assign/TSTypeParameterInstantiation-babel-7/output.json
  packages/babel-parser/test/fixtures/typescript/assign/TSTypeParameterInstantiation/input.ts
  packages/babel-parser/test/fixtures/typescript/assign/TSTypeParameterInstantiation/options.json
  packages/babel-parser/test/fixtures/typescript/assign/TSTypeParameterInstantiation/output.json
  packages/babel-plugin-transform-typescript/test/fixtures/lvalues/TSTypeParameterInstantiation/input.ts
  packages/babel-plugin-transform-typescript/test/fixtures/lvalues/TSTypeParameterInstantiation/options.json
  packages/babel-plugin-transform-typescript/test/fixtures/lvalues/TSTypeParameterInstantiation/output.mjs
Labels: PR: Bug Fix :bug:, pkg: parser, area: typescript

#16482 Statically generate boilerplate for bitfield accessors
  babel.config.js
  packages/babel-parser/src/tokenizer/state.ts
  packages/babel-traverse/src/path/index.ts
  scripts/babel-plugin-bit-decorator/plugin.cjs
  scripts/babel-plugin-bit-decorator/types.d.ts
Labels: PR: Internal :house:

#16483 Fix: throw TypeError if addInitializer is called after finished
  packages/babel-helpers/src/helpers-generated.ts
  packages/babel-helpers/src/helpers/applyDecs2311.ts
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-misc--to-es2015/leaked-context-addInitializer-throw-2/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-misc--to-es2015/leaked-context-addInitializer/exec.js
  packages/babel-runtime-corejs3/helpers/esm/applyDecs2311.js
Labels: PR: Bug Fix :bug:, Spec: Decorators

#16484 Fix decorator bare yield await
  packages/babel-helper-create-class-features-plugin/src/decorators.ts
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-misc/decorator-evaluation-new-target/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-misc/decorator-evaluation-this/exec.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-misc/decorator-evaluation-yield/exec.js
Labels: PR: Bug Fix :bug:, Spec: Decorators

#16479 Update eslint v9
  Makefile.js
  Makefile.source.mjs
  eslint.config.js
  eslint/babel-eslint-config-internal/index.js
  eslint/babel-eslint-parser/src/types.d.cts
  eslint/babel-eslint-plugin-development-internal/src/rules/require-default-import-fallback.cjs
  eslint/babel-eslint-plugin-development/src/rules/no-deprecated-clone.cjs
  eslint/babel-eslint-plugin-development/src/rules/no-undefined-identifier.cjs
  eslint/babel-eslint-plugin-development/src/rules/plugin-name.cjs
  package.json
  packages/babel-cli/src/babel/dir.ts
  packages/babel-core/src/config/files/module-types.ts
  packages/babel-core/src/errors/rewrite-stack-trace.ts
  packages/babel-helper-create-class-features-plugin/src/fields.ts
  packages/babel-helper-module-transforms/src/get-module-name.ts
  packages/babel-helpers/src/helpers/typeof.js
  packages/babel-helpers/src/helpers/usingCtx.ts
  packages/babel-parser/src/parser/expression.ts
  packages/babel-parser/src/parser/statement.ts
  packages/babel-parser/src/plugins/flow/index.ts
  packages/babel-parser/src/plugins/placeholders.ts
  packages/babel-parser/src/util/scopeflags.ts
  packages/babel-parser/test/helpers/run-fixture-tests.js
  packages/babel-plugin-transform-react-constant-elements/src/index.ts
  packages/babel-plugin-transform-runtime/scripts/build-dist.js
  packages/babel-traverse/src/path/family.ts
  packages/babel-traverse/src/scope/index.ts
  packages/babel-traverse/src/visitors.ts
  packages/babel-types/scripts/generators/flow.js
  packages/babel-types/scripts/generators/typescript-legacy.js
  yarn.lock
Labels: PR: Dependency ⬆️

#16485 Support undecorated static accessor in anonymous classes
  packages/babel-helper-create-class-features-plugin/src/decorators.ts
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-accessors/undecorated-static-private/input.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-accessors/undecorated-static-private/input.mjs
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-accessors/undecorated-static-private/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-accessors/undecorated-static-private/output.mjs
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-accessors/undecorated-static-public/input.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-accessors/undecorated-static-public/input.mjs
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-accessors/undecorated-static-public/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-accessors/undecorated-static-public/output.mjs
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-classes/expressions-named-evaluation/exec.js
Labels: PR: Bug Fix :bug:, Spec: Decorators

#16499 Add `tsconfig.json` for `@babel/helpers/src/helpers`
  Makefile.js
  Makefile.source.mjs
  packages/babel-helpers/scripts/generate-helpers.js
  packages/babel-helpers/src/helpers/tsconfig.json
  tsconfig.base.json
Labels: PR: Internal :house:

#16505 [helpers TS conversion] object
  packages/babel-helpers/src/helpers-generated.ts
  packages/babel-helpers/src/helpers/defaults.js
  packages/babel-helpers/src/helpers/defaults.ts
  packages/babel-helpers/src/helpers/extends.js
  packages/babel-helpers/src/helpers/extends.ts
  packages/babel-helpers/src/helpers/objectDestructuringEmpty.js
  packages/babel-helpers/src/helpers/objectDestructuringEmpty.ts
  packages/babel-helpers/src/helpers/objectSpread.js
  packages/babel-helpers/src/helpers/objectSpread.ts
  packages/babel-helpers/src/helpers/objectSpread2.ts
  packages/babel-helpers/src/helpers/objectWithoutProperties.js
  packages/babel-helpers/src/helpers/objectWithoutProperties.ts
  packages/babel-helpers/src/helpers/objectWithoutPropertiesLoose.js
  packages/babel-helpers/src/helpers/objectWithoutPropertiesLoose.ts
  packages/babel-runtime-corejs3/helpers/esm/extends.js
Labels: area: helpers

#16509 bump commander to 6.2.0
  packages/babel-cli/package.json
  packages/babel-cli/src/babel-external-helpers.ts
  packages/babel-cli/src/babel/options.ts
  packages/babel-node/package.json
  packages/babel-node/src/_babel-node.ts
  yarn.lock
Labels: PR: Dependency ⬆️

#16515 Fix source maps for template literals
  packages/babel-core/test/fixtures/transformation/source-maps/template-literal/input.js
  packages/babel-core/test/fixtures/transformation/source-maps/template-literal/options.json
  packages/babel-core/test/fixtures/transformation/source-maps/template-literal/output.js
  packages/babel-core/test/fixtures/transformation/source-maps/template-literal/source-map-visual.txt
  packages/babel-core/test/fixtures/transformation/source-maps/template-literal/source-map.json
  packages/babel-generator/src/generators/template-literals.ts
  packages/babel-generator/test/fixtures/sourcemaps/real-world-babel-file2/source-map.json
  packages/babel-generator/test/fixtures/sourcemaps/template-literal-newline/source-map.json
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/strict/import/source-map-visual.txt
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/strict/import/source-map.json
Labels: PR: Bug Fix :bug:, area: sourcemaps

#16514 Fix source maps for private member expressions
  packages/babel-helper-create-class-features-plugin/src/fields.ts
  packages/babel-plugin-transform-class-properties/test/fixtures/source-maps/options.json
  packages/babel-plugin-transform-class-properties/test/fixtures/source-maps/private-get/input.js
  packages/babel-plugin-transform-class-properties/test/fixtures/source-maps/private-get/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/source-maps/private-get/source-map-visual.txt
  packages/babel-plugin-transform-class-properties/test/fixtures/source-maps/private-get/source-map.json
  packages/babel-plugin-transform-class-properties/test/fixtures/source-maps/private-set/input.js
  packages/babel-plugin-transform-class-properties/test/fixtures/source-maps/private-set/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/source-maps/private-set/source-map-visual.txt
  packages/babel-plugin-transform-class-properties/test/fixtures/source-maps/private-set/source-map.json
Labels: PR: Bug Fix :bug:, area: sourcemaps

#16517 [Babel 8] Bump commander to 12.1.0
  lib/third-party-libs.d.ts
  packages/babel-cli/package.json
  packages/babel-cli/src/babel-external-helpers.ts
  packages/babel-cli/src/babel/options.ts
  packages/babel-node/package.json
  packages/babel-node/src/_babel-node.ts
  scripts/generators/tsconfig.js
  tsconfig.paths.json
  yarn.lock
Labels: PR: Dependency ⬆️, PR: Internal (next major) :house:

#16525 Delete unused array helpers
  packages/babel-helpers/src/helpers-generated.ts
  packages/babel-helpers/src/helpers/iterableToArrayLimitLoose.ts
  packages/babel-helpers/src/helpers/slicedToArrayLoose.ts
  packages/babel-runtime-corejs2/package.json
  packages/babel-runtime-corejs3/helpers/esm/iterableToArrayLimitLoose.js
  packages/babel-runtime-corejs3/helpers/esm/slicedToArrayLoose.js
  packages/babel-runtime-corejs3/package.json
  packages/babel-runtime/package.json
Labels: PR: Internal :house:

#16524 fix: Transform `using` in `switch` correctly
  packages/babel-helper-transform-fixture-test-runner/src/index.ts
  packages/babel-plugin-proposal-explicit-resource-management/src/index.ts
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/switch/input.js
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/switch/output.js
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/switch/source-map-visual.txt
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/source-maps/switch/source-map.json
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/transform-await/switch/input.js
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/transform-await/switch/output.mjs
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/transform-sync/switch/input.js
  packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/transform-sync/switch/output.js
Labels: PR: Bug Fix :bug:, Spec: Explicit Resource Management
