Repository babel/babel, pull requests merged in 2024-10, with the labels that each got.

#16876 Fix prettier Babel 8 test
  scripts/integration-tests/e2e-prettier.sh
Labels: PR: Fixes failing main

#16883 chore: Update lint deps
  .yarn/patches/eslint-plugin-import-npm-2.30.0-4fd74d3ee6.patch
  eslint/babel-eslint-parser/src/worker/configuration.cts
  eslint/babel-eslint-tests/test/integration/eslint-plugin-import.js
  package.json
  yarn.lock
Labels: PR: Dependency ⬆️, PR: Fixes failing main

#16890 Cleanup prettier e2e test
  scripts/integration-tests/e2e-prettier.sh
Labels: PR: Fixes failing main

#16888 Restore public API of `resolvePlugin`/`resolvePreset`
  packages/babel-core/src/index.ts
  packages/babel-core/test/resolution.js
Labels: PR: Bug Fix :bug:, i: regression, pkg: core

#16884 Analyze `ClassAccessorProperty` to prevent the `no-undef` rule
  eslint/babel-eslint-parser/src/analyze-scope.cts
  eslint/babel-eslint-tests/test/integration/eslint/verify.js
Labels: PR: Bug Fix :bug:, area: eslint

#16907 fix: support BROWSERSLIST{,_CONFIG} env
  packages/babel-helper-compilation-targets/src/index.ts
  packages/babel-helper-compilation-targets/test/targets-parser.spec.js
  packages/babel-preset-env/test/index.skip-bundled.js
Labels: PR: Bug Fix :bug:, i: regression

#16905 fix: Keep type annotations in `syntacticPlaceholders` mode
  packages/babel-parser/test/fixtures/placeholders/typescript/options.json
  packages/babel-parser/test/fixtures/placeholders/typescript/typeAnnotation/input.ts
  packages/babel-parser/test/fixtures/placeholders/typescript/typeAnnotation/output.json
  packages/babel-template/src/populate.ts
  packages/babel-template/test/index.js
  packages/babel-types/src/ast-types/generated/index.ts
  packages/babel-types/src/definitions/misc.ts
Labels: PR: Bug Fix :bug:, pkg: types, pkg: template

#16914 remove test options flaky
  .github/workflows/ci.yml
  CONTRIBUTING.md
  packages/babel-helper-transform-fixture-test-runner/src/index.ts
Labels: PR: Internal :house:

#16882 perf: Improve module transforms
  packages/babel-helper-module-transforms/package.json
  packages/babel-helper-module-transforms/src/rewrite-live-references.ts
  packages/babel-helper-module-transforms/tsconfig.json
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/export-var-and-modify/input.mjs
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/export-var-and-modify/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/import-const-throw/output.js
  yarn.lock
Labels: area: modules, PR: Performance :running_woman:

#16708 Add experimental format-preserving mode to `@babel/generator`
  packages/babel-generator/package.json
  packages/babel-generator/src/buffer.ts
  packages/babel-generator/src/generators/classes.ts
  packages/babel-generator/src/generators/expressions.ts
  packages/babel-generator/src/generators/flow.ts
  packages/babel-generator/src/generators/jsx.ts
  packages/babel-generator/src/generators/methods.ts
  packages/babel-generator/src/generators/modules.ts
  packages/babel-generator/src/generators/statements.ts
  packages/babel-generator/src/generators/template-literals.ts
  packages/babel-generator/src/generators/types.ts
  packages/babel-generator/src/generators/typescript.ts
  packages/babel-generator/src/index.ts
  packages/babel-generator/src/node/index.ts
  packages/babel-generator/src/node/parentheses.ts
  packages/babel-generator/src/printer.ts
  packages/babel-generator/src/token-map.ts
  packages/babel-generator/test/fixtures/preserveFormat-edgecases/class-body-semicolons/input.js
  packages/babel-generator/test/fixtures/preserveFormat-edgecases/class-body-semicolons/output.js
  packages/babel-generator/test/fixtures/preserveFormat-edgecases/ts-interface-mixed-delimiters/input.ts
  packages/babel-generator/test/fixtures/preserveFormat-edgecases/ts-interface-mixed-delimiters/options.json
  packages/babel-generator/test/fixtures/preserveFormat-edgecases/ts-interface-mixed-delimiters/output.js
  packages/babel-generator/test/fixtures/recordAndTuple/default/input.js
  packages/babel-generator/test/fixtures/recordAndTuple/default/output.js
  packages/babel-generator/test/fixtures/recordAndTupleSyntaxType-babel-7/default/input.js
  packages/babel-generator/test/fixtures/recordAndTupleSyntaxType-babel-7/default/output.js
  packages/babel-generator/test/fixtures/sourcemaps/real-world-babel-file1/source-map.json
  packages/babel-generator/test/fixtures/sourcemaps/real-world-babel-file2/source-map.json
  packages/babel-generator/test/preserve-format.js
  packages/babel-generator/tsconfig.json
  packages/babel-parser/src/index.ts
  yarn.lock
Labels: PR: New Feature :rocket:, pkg: generator, PR: Ready to be Merged

#16794 Support `import()` in `rewriteImportExtensions`
  packages/babel-helpers/src/helpers-generated.ts
  packages/babel-helpers/src/helpers/superPropGet.ts
  packages/babel-helpers/src/helpers/superPropSet.ts
  packages/babel-preset-typescript/src/plugin-rewrite-ts-imports.ts
  packages/babel-preset-typescript/test/fixtures/opts/rewriteImportExtensions-createImportExpressions/input.ts
  packages/babel-preset-typescript/test/fixtures/opts/rewriteImportExtensions-createImportExpressions/options.json
  packages/babel-preset-typescript/test/fixtures/opts/rewriteImportExtensions-createImportExpressions/output.mjs
  packages/babel-preset-typescript/test/fixtures/opts/rewriteImportExtensions/input.ts
  packages/babel-preset-typescript/test/fixtures/opts/rewriteImportExtensions/output.mjs
  packages/babel-runtime-corejs3/helpers/esm/superPropGet.js
  packages/babel-runtime-corejs3/helpers/esm/superPropSet.js
Labels: PR: New Feature :rocket:, PR: Ready to be Merged

#16925 Only parse # as comment in .babelignore at line start
  packages/babel-core/src/config/files/configuration.ts
  packages/babel-core/test/config-chain.js
  packages/babel-core/test/fixtures/config/config-files/babelignore/.babelignore
Labels: PR: Bug Fix (next major) :bug:

#16732 Add `kind` to `TSModuleDeclaration`
  packages/babel-generator/src/generators/typescript.ts
  packages/babel-generator/test/fixtures/typescript/export-declare/output.js
  packages/babel-generator/test/fixtures/typescript/module-namespace-head-declare/output.js
  packages/babel-generator/test/fixtures/typescript/module-namespace-head-export/output.js
  packages/babel-generator/test/fixtures/typescript/module-namespace-head/output.js
  packages/babel-generator/test/preserve-format.js
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/src/types.ts
  packages/babel-parser/test/fixtures/experimental/export-extensions/export-with-ts/output.json
  packages/babel-parser/test/fixtures/typescript/const/initializer-ambient-context/output.json
  packages/babel-parser/test/fixtures/typescript/const/invalid-initializer-ambient-context/output.json
  packages/babel-parser/test/fixtures/typescript/declare/eval-dts/output.json
  packages/babel-parser/test/fixtures/typescript/declare/eval/output.json
  packages/babel-parser/test/fixtures/typescript/declare/module-class/output.json
  packages/babel-parser/test/fixtures/typescript/declare/module-function/output.json
  packages/babel-parser/test/fixtures/typescript/declare/namespace-class/output.json
  packages/babel-parser/test/fixtures/typescript/declare/namespace-function/output.json
  packages/babel-parser/test/fixtures/typescript/estree-compat/shorthand-ambient-module/output.json
  packages/babel-parser/test/fixtures/typescript/export/declare/output.json
  packages/babel-parser/test/fixtures/typescript/export/export-value-declaration/output.json
  packages/babel-parser/test/fixtures/typescript/export/nested-same-name/output.json
  packages/babel-parser/test/fixtures/typescript/import/not-top-level/output.json
  packages/babel-parser/test/fixtures/typescript/module-namespace/body-declare/output.json
  packages/babel-parser/test/fixtures/typescript/module-namespace/body-nested-declare/output.json
  packages/babel-parser/test/fixtures/typescript/module-namespace/body-nested/output.json
  packages/babel-parser/test/fixtures/typescript/module-namespace/body/output.json
  packages/babel-parser/test/fixtures/typescript/module-namespace/declare-shorthand/output.json
  packages/babel-parser/test/fixtures/typescript/module-namespace/global-in-module/output.json
  packages/babel-parser/test/fixtures/typescript/module-namespace/head-declare/output.json
  packages/babel-parser/test/fixtures/typescript/module-namespace/head-export/output.json
  packages/babel-parser/test/fixtures/typescript/module-namespace/head/output.json
  packages/babel-parser/test/fixtures/typescript/module-namespace/top-level-await/output.json
  packages/babel-parser/test/fixtures/typescript/scope/export-func-in-declare-module/output.json
  packages/babel-parser/test/fixtures/typescript/scope/export-import-in-declare-module/output.json
  packages/babel-parser/test/fixtures/typescript/scope/export-namespace/output.json
  packages/babel-parser/test/fixtures/typescript/scope/module-declaration-var-2/output.json
  packages/babel-parser/test/fixtures/typescript/scope/module-declaration-var/output.json
  packages/babel-parser/test/fixtures/typescript/scope/redeclaration-import-equals-var/output.json
  packages/babel-parser/test/fixtures/typescript/scope/redeclaration-in-different-module-and-top-level/output.json
  packages/babel-parser/test/fixtures/typescript/scope/redeclaration-in-different-module/output.json
  packages/babel-parser/test/fixtures/typescript/scope/redeclaration-in-nested-module/output.json
  packages/babel-types/src/ast-types/generated/index.ts
  packages/babel-types/src/builders/generated/index.ts
  packages/babel-types/src/definitions/typescript.ts
Labels: PR: Internal :house:, pkg: generator, pkg: parser, area: typescript, pkg: types

#16926 Fix loading of modules with TLA in Node.js 23
  eslint.config.mjs
  packages/babel-core/src/config/files/module-types.ts
  packages/babel-core/test/async.js
  packages/babel-core/test/fixtures/async/plugin-mjs-tla-native/babel.config.cjs
  packages/babel-core/test/fixtures/async/plugin-mjs-tla-native/package.json
  packages/babel-core/test/fixtures/async/plugin-mjs-tla-native/plugin.js
  scripts/integration-tests/e2e-react-native.sh
Labels: PR: Bug Fix :bug:, Priority: High

#16928 Workaround Node.js bug for parallel loading of TLA modules
  packages/babel-core/src/config/files/module-types.ts
  packages/babel-core/test/async.js
  packages/babel-core/test/fixtures/async/config-mjs-tla-native/babel.config.js
  packages/babel-core/test/fixtures/async/config-mjs-tla-native/package.json
  packages/babel-core/test/fixtures/async/config-mjs-tla-native/plugin.js
  packages/babel-core/test/fixtures/babel-compile-async-parallel.mjs
  packages/babel-core/test/helpers/esm.js
Labels: PR: Bug Fix :bug:, Priority: High

#16862 feat: support async plugin's pre/post
  packages/babel-core/src/config/full.ts
  packages/babel-core/src/config/validation/plugins.ts
  packages/babel-core/src/transformation/index.ts
  packages/babel-core/src/transformation/plugin-pass.ts
  packages/babel-core/test/async.js
  packages/babel-core/test/fixtures/async/plugin-pass-is-async/babel.config.js
  packages/babel-core/test/fixtures/async/plugin-pass-is-async/plugin.js
  packages/babel-core/test/fixtures/async/plugin-post-chaining/babel.config.js
  packages/babel-core/test/fixtures/async/plugin-post-chaining/plugin.js
  packages/babel-core/test/fixtures/async/plugin-post/plugin.js
  packages/babel-core/test/fixtures/async/plugin-pre-chaining/babel.config.js
  packages/babel-core/test/fixtures/async/plugin-pre-chaining/plugin.js
  packages/babel-core/test/fixtures/async/plugin-pre/plugin.js
Labels: PR: New Feature :rocket:, pkg: core

#16896 Inline `@babel/highlight` in `@babel/code-frame`
  Gulpfile.mjs
  packages/babel-code-frame/package.json
  packages/babel-code-frame/src/defs.ts
  packages/babel-code-frame/src/highlight.ts
  packages/babel-code-frame/src/index.ts
  packages/babel-code-frame/test/color-detection.js
  packages/babel-code-frame/test/index.js
  packages/babel-code-frame/tsconfig.json
  packages/babel-highlight/.npmignore
  packages/babel-highlight/README.md
  packages/babel-highlight/package.json
  packages/babel-highlight/test/index.js
  packages/babel-highlight/tsconfig.json
  tsconfig.json
  tsconfig.paths.json
  yarn.lock
Labels: PR: Internal :house:

#16932 fix: CI with Node v23.1.0
  packages/babel-core/test/helpers/esm.js
Labels: PR: Fixes failing main

#16933 Update `@babel/*` dependencies
  .yarnrc.yml
  babel.config.js
  package.json
  scripts/integration-tests/e2e-babel-old-version.sh
  scripts/integration-tests/e2e-babel.sh
  yarn.lock
Labels: PR: Dependency ⬆️

#16936 fix(parser): offset internal index locations by startIndex
  packages/babel-parser/src/parser/base.ts
  packages/babel-parser/src/parser/comments.ts
  packages/babel-parser/src/parser/expression.ts
  packages/babel-parser/src/parser/index.ts
  packages/babel-parser/src/parser/statement.ts
  packages/babel-parser/src/parser/util.ts
  packages/babel-parser/src/plugins/flow/index.ts
  packages/babel-parser/src/plugins/placeholders.ts
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/src/tokenizer/index.ts
  packages/babel-parser/src/tokenizer/state.ts
  packages/babel-parser/test/fixtures/core/categorized/startcolumn-specified/output.json
  packages/babel-parser/test/fixtures/core/categorized/startindex-specified/output.json
  packages/babel-parser/test/fixtures/core/categorized/startindex-startline-and-startcolumn-specified/output.json
  packages/babel-parser/test/helpers/run-fixture-tests.js
Labels: PR: Bug Fix :bug:, pkg: parser, i: regression

#16946 Fix CI e2e-babel error
  eslint.config.mjs
  eslint/babel-eslint-parser/test/index.js
  yarn.lock
Labels: PR: Fixes failing main

#16937 fix: Account for offsets when creating new Position instances
  packages/babel-parser/src/parser/statement.ts
  packages/babel-parser/src/tokenizer/index.ts
  packages/babel-parser/src/tokenizer/state.ts
  packages/babel-parser/test/fixtures/core/categorized/start-not-specified/input.js
  packages/babel-parser/test/fixtures/core/categorized/start-not-specified/output.json
  packages/babel-parser/test/fixtures/core/categorized/startcolumn-specified/output.json
  packages/babel-parser/test/fixtures/core/categorized/startindex-specified/output.json
  packages/babel-parser/test/fixtures/core/categorized/startindex-startline-and-startcolumn-specified/output.json
  packages/babel-parser/test/helpers/run-fixture-tests.js
  packages/babel-parser/test/helpers/to-fuzzed-options.js
Labels: PR: Bug Fix :bug:, pkg: parser, i: regression

#16948 Add test for current wrong behavior
  packages/babel-generator/src/token-map.ts
  packages/babel-generator/test/preserve-format.js
Labels: PR: Bug Fix :bug:, pkg: generator

#16903 fix: Parse placeholder for TS namespace
  packages/babel-parser/src/tokenizer/types.ts
  packages/babel-parser/test/fixtures/placeholders/expression/object/input.js
  packages/babel-parser/test/fixtures/placeholders/expression/object/output.json
  packages/babel-parser/test/fixtures/placeholders/typescript/export-namespace/input.ts
  packages/babel-parser/test/fixtures/placeholders/typescript/export-namespace/output.json
Labels: PR: Bug Fix :bug:, pkg: parser
