Repository babel/babel, pull requests merged in 2025-04, with the labels that each got.

#17156 fix: Objects and arrays with multiple references should not be evaluated
  packages/babel-traverse/src/path/evaluation.ts
  packages/babel-traverse/test/evaluation.js
Labels: PR: Bug Fix :bug:, pkg: traverse

#17221 Reduce generated names size for the 10th-11th
  packages/babel-plugin-bugfix-v8-spread-parameters-in-optional-chaining/test/fixtures/assumption-pureGetters/function-call/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2021-12-classes--to-es2015/expressions-static-blocks/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2022-03-classes--to-es2015/expressions-static-blocks/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-01-classes--to-es2015/expressions-static-blocks/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-05-classes--to-es2015/expressions-static-blocks/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-classes--to-es2015/expressions-static-blocks/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-misc--to-es2015/initField-existing-derived-constructor/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-ordering--to-es2015/class-decorators-without-element-decorators/output.js
  packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-ordering/class-decorators-without-element-decorators/output.js
  packages/babel-plugin-transform-arrow-functions/test/fixtures/arrow-functions/arguments/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/assumption-noDocumentAll/optional-chain-before-member-call/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private-loose/optional-chain-before-member-call-with-transform/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private-loose/optional-chain-before-member-call/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private-loose/optional-chain-before-property-with-transform/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private-loose/optional-chain-before-property/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private-loose/optional-chain-delete-property-with-transform/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private-loose/optional-chain-member-optional-call-with-transform/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private-loose/optional-chain-member-optional-call/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private-loose/optional-chain-optional-member-call-with-transform/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private-loose/optional-chain-optional-member-call/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private-loose/optional-chain-optional-property-with-transform/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private/optional-chain-before-member-call-with-transform/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private/optional-chain-before-member-call/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private/optional-chain-before-property-with-transform/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private/optional-chain-before-property/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private/optional-chain-delete-property-with-transform/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private/optional-chain-member-optional-call-with-transform/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private/optional-chain-member-optional-call/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private/optional-chain-optional-member-call-with-transform/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private/optional-chain-optional-member-call/output.js
  packages/babel-plugin-transform-class-properties/test/fixtures/private/optional-chain-optional-property-with-transform/output.js
  packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/empty-array-pattern/output.js
  packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/parameters-object-rest-used-in-default/output.js
  packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/parameters/output.js
  packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/variable-destructuring/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/assumption-noDocumentAll/cast-to-boolean/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/assumption-noDocumentAll/memoize/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/general/cast-to-boolean/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/general/function-call/output.js
  packages/babel-plugin-transform-optional-chaining/test/fixtures/loose/cast-to-boolean/output.js
  packages/babel-plugin-transform-parameters/test/fixtures/parameters/rest-member-expression-deoptimisation/output.js
  packages/babel-traverse/src/scope/index.ts
Labels: PR: Polish :nail_care:

#17217 Harden variable declarator validations
  packages/babel-traverse/test/scope.js
  packages/babel-types/src/definitions/core.ts
  packages/babel-types/test/validate.js
Labels: PR: Breaking Change :boom:

#17219 test: add basic typescript-eslint integration tests
  eslint/babel-eslint-parser/package.json
  eslint/babel-eslint-parser/test/typescript-estree.test.js
  yarn.lock
Labels: PR: Internal :house:

#16844 Migrate `@babel/register` to cts
  packages/babel-register/experimental-worker.js
  packages/babel-register/package.json
  packages/babel-register/src/browser.cts
  packages/babel-register/src/cache.cts
  packages/babel-register/src/experimental-worker.cts
  packages/babel-register/src/experimental-worker.js
  packages/babel-register/src/hook.cts
  packages/babel-register/src/index.cts
  packages/babel-register/src/is-in-register-worker.cts
  packages/babel-register/src/node.cts
  packages/babel-register/src/nodeWrapper.cts
  packages/babel-register/src/types.cts
  packages/babel-register/src/worker-client.cts
  packages/babel-register/src/worker/babel-core.cts
  packages/babel-register/src/worker/cache.cts
  packages/babel-register/src/worker/handle-message.cts
  packages/babel-register/src/worker/handle-message.js
  packages/babel-register/src/worker/index.cts
  packages/babel-register/src/worker/index.js
  packages/babel-register/src/worker/transform.cts
  packages/babel-register/test/cache.js
  scripts/generators/tsconfig.js
  tsconfig.paths.json
  yarn.config.cjs
Labels: PR: Internal :house:, pkg: register

#17228 Update firefox bugfix compat data
  packages/babel-compat-data/data/plugin-bugfixes.json
  packages/babel-compat-data/data/plugins.json
  packages/babel-compat-data/scripts/data/plugin-features.js
  packages/babel-compat-data/scripts/utils-build-data.js
  packages/babel-preset-env/test/fixtures/bugfixes-always-enabled/class-in-computed-field-firefox-90/stdout.txt
  packages/babel-preset-env/test/fixtures/bugfixes-babel-8/_esmodules/stdout.txt
  packages/babel-preset-env/test/fixtures/corejs3/usage-browserslist-config-ignore/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/browserslists-defaults-not-ie/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/browserslists-defaults/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/browserslists-last-2-versions-not-ie/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/browserslists-defaults-not-ie/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/browserslists-defaults/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/browserslists-last-2-versions-not-ie/stdout.txt
Labels: PR: Bug Fix :bug:

#17226 Fill optional AST properties when both estree and typescript parser plugin are enabled (Part 2)
  eslint/babel-eslint-parser/src/convert/convertTokens.cts
  eslint/babel-eslint-parser/test/index.js
  eslint/babel-eslint-parser/test/typescript-estree.test.js
  packages/babel-generator/test/fixtures/flow/parentheses/input.js
  packages/babel-generator/test/fixtures/flow/parentheses/output.js
  packages/babel-generator/test/preserve-format.js
  packages/babel-parser/src/parser/expression.ts
  packages/babel-parser/src/parser/lval.ts
  packages/babel-parser/src/parser/node.ts
  packages/babel-parser/src/parser/statement.ts
  packages/babel-parser/src/plugins/estree.ts
  packages/babel-parser/src/plugins/flow/index.ts
  packages/babel-parser/src/plugins/placeholders.ts
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/src/plugins/v8intrinsic.ts
  packages/babel-parser/src/types.ts
Labels: PR: Bug Fix :bug:

#17230 Disallow get/set in TSPropertySignature
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/test/fixtures/typescript/interface/get-set-properties/output.json
  packages/babel-parser/test/fixtures/typescript/interface/invalid-get-properties/input.ts
  packages/babel-parser/test/fixtures/typescript/interface/invalid-get-properties/options.json
  packages/babel-parser/test/fixtures/typescript/interface/invalid-set-properties/input.ts
  packages/babel-parser/test/fixtures/typescript/interface/invalid-set-properties/options.json
Labels: PR: Spec Compliance :eyeglasses:, pkg: parser, area: typescript

#17236 migrate babel-compat-data build script to mjs
  packages/babel-compat-data/package.json
  packages/babel-compat-data/scripts/build-bugfixes-targets.mjs
  packages/babel-compat-data/scripts/build-corejs3-proposals.mjs
  packages/babel-compat-data/scripts/build-data.mjs
  packages/babel-compat-data/scripts/build-modules-support.mjs
  packages/babel-compat-data/scripts/chromium-to-electron.mjs
  packages/babel-compat-data/scripts/data/corejs2-built-in-features.mjs
  packages/babel-compat-data/scripts/data/legacy-plugin-aliases.mjs
  packages/babel-compat-data/scripts/data/plugin-bugfixes.mjs
  packages/babel-compat-data/scripts/data/plugin-features.mjs
  packages/babel-compat-data/scripts/utils-build-data.mjs
  packages/babel-standalone/src/index.ts
Labels: PR: Internal :house:

#17193 Stricter TSImportType options parsing
  packages/babel-parser/src/parser/expression.ts
  packages/babel-parser/src/plugins/estree.ts
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-jsx-options/options.json
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-options-trailing-comma-babel-7/input.ts
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-options-trailing-comma-babel-7/options.json
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-options-trailing-comma-babel-7/output.json
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-options-trailing-comma/input.ts
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-options-trailing-comma/options.json
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-options-trailing-comma/output.json
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-string-options-babel-7/input.ts
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-string-options-babel-7/options.json
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-string-options-babel-7/output.json
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-string-options/input.ts
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-string-options/options.json
  packages/babel-parser/test/fixtures/typescript/types/import-type-dynamic-with-string-options/output.json
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-dynamic-with-jsx-options/input.ts
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-dynamic-with-jsx-options/options.json
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-options-escaped-with/input.ts
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-options-escaped-with/options.json
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-options-string-with/input.ts
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-options-string-with/options.json
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-options-trailing-comma/input.ts
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-options-trailing-comma/options.json
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-options-with-computed-properties/input.ts
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-options-with-computed-properties/options.json
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-options-with-spread-element/input.ts
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-options-with-spread-element/options.json
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-options-with-trailing-comma/input.ts
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-options-with-trailing-comma/options.json
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-trailing-comma/input.ts
  packages/babel-parser/test/fixtures/typescript/types/invalid-import-type-trailing-comma/options.json
  packages/babel-types/src/ast-types/generated/index.ts
  packages/babel-types/src/definitions/typescript.ts
Labels: PR: Spec Compliance :eyeglasses:, pkg: parser, area: typescript

#17233 Create ChainExpression within TSInstantiationExpression
  packages/babel-helper-fixtures/src/index.ts
  packages/babel-parser/src/parser/expression.ts
  packages/babel-parser/src/plugins/estree.ts
  packages/babel-parser/src/plugins/typescript/index.ts
  packages/babel-parser/src/types.ts
  packages/babel-parser/test/fixtures/estree/typescript/instantiation-expression-optional-chain-babel-7/input.ts
  packages/babel-parser/test/fixtures/estree/typescript/instantiation-expression-optional-chain-babel-7/options.json
  packages/babel-parser/test/fixtures/estree/typescript/instantiation-expression-optional-chain-babel-7/output.json
  packages/babel-parser/test/fixtures/estree/typescript/instantiation-expression-optional-chain/input.ts
  packages/babel-parser/test/fixtures/estree/typescript/instantiation-expression-optional-chain/options.json
  packages/babel-parser/test/fixtures/estree/typescript/instantiation-expression-optional-chain/output.json
Labels: PR: Bug Fix :bug:

#16538 Reduce `interopRequireWildcard` size
  packages/babel-helpers/src/helpers-generated.ts
  packages/babel-helpers/src/helpers/interopRequireWildcard.ts
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/copy-getters-setters-star/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/copy-getters-setters/output.js
  packages/babel-plugin-transform-modules-commonjs/test/fixtures/misc/import-const-throw/output.js
  packages/babel-runtime-corejs3/helpers/esm/interopRequireWildcard.js
  scripts/integration-tests/e2e-jest.sh
Labels: PR: Output optimization :microscope:

#17231 fix apply()/call() annotated as pure
  packages/babel-helper-remap-async-to-generator/src/index.ts
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-iife-apply-call-no-pure/input.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-iife-apply-call-no-pure/output.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/regression/T7194/output.js
Labels: PR: Bug Fix :bug:, Spec: Async Functions

#16965 [Babel 8] perf: Improve traverse performance
  packages/babel-traverse/src/cache.ts
  packages/babel-traverse/src/path/index.ts
  packages/babel-traverse/src/path/modification.ts
  packages/babel-traverse/src/path/removal.ts
  packages/babel-traverse/src/path/replacement.ts
  packages/babel-traverse/src/traverse-node.ts
  packages/babel-traverse/test/modification.js
  packages/babel-traverse/test/replacement.js
Labels: pkg: traverse, PR: Performance (next major) :running_woman:

#17253 chore: bump compat-data sources
  package.json
  packages/babel-compat-data/data/plugins.json
  packages/babel-compat-data/package.json
  packages/babel-compat-data/scripts/build-data.mjs
  packages/babel-compat-data/scripts/build-modules-support.mjs
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs2-no-import/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs2-versions-decimals/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs2-versions-strings/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs3-no-import/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs3-versions-decimals/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs3-versions-strings-minor-3.0/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs3-versions-strings-minor-3.1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs3-versions-strings/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs3/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-no-corejs-no-import/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-no-corejs/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/plugins-only/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/entry-corejs3-no-import/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/entry-corejs3-versions-strings-minor-3.0/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/entry-corejs3-versions-strings-minor-3.1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/entry-corejs3/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/plugins-only/stdout.txt
  packages/babel-preset-env/test/fixtures/plugins-integration/class-features-node-12-babel-7/stdout.txt
  packages/babel-preset-env/test/fixtures/plugins-integration/class-features-node-12/stdout.txt
  yarn.lock
Labels: PR: Dependency ⬆️

#17256 Tune plugin compat data
  packages/babel-compat-data/data/plugin-bugfixes.json
  packages/babel-compat-data/data/plugins.json
  packages/babel-compat-data/scripts/build-corejs2-built-in-features.mjs
  packages/babel-compat-data/scripts/build-data.mjs
  packages/babel-compat-data/scripts/data/plugin-features.mjs
  packages/babel-compat-data/scripts/utils-build-data.mjs
  packages/babel-preset-env/test/fixtures/bugfixes-always-enabled/class-in-computed-field-firefox-50/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs2-specific-targets/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/entry-corejs3-specific-targets/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs2-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs2-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs2-none-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs2-none-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs2-proposals-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs2-proposals-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs2-shippedProposals-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs2-shippedProposals-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs3-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs3-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs3-none-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs3-none-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs3-proposals-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs3-proposals-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs3-shippedProposals-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs3-shippedProposals-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs3-versions-strings-minor-3.0-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs3-versions-strings-minor-3.0-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs3-versions-strings-minor-3.1-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-corejs3-versions-strings-minor-3.1-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-no-corejs-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-no-corejs-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-no-corejs-none-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug-babel-7/usage-no-corejs-none-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/entry-corejs3-specific-targets/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-none-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-none-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-proposals-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-proposals-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-shippedProposals-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-shippedProposals-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-versions-strings-minor-3.0-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-versions-strings-minor-3.0-2/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-versions-strings-minor-3.1-1/stdout.txt
  packages/babel-preset-env/test/fixtures/debug/usage-corejs3-versions-strings-minor-3.1-2/stdout.txt
Labels: PR: Internal :house:

#17251 Fix: propagate argument evaluation errors through async promise chain
  packages/babel-helper-wrap-function/src/index.ts
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params-destructuring/exec.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params-destructuring/input.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params-destructuring/options.json
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params-destructuring/output.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/exec.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/input.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/options.json
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/output.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/class-method-arity-ignore-length/input.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/class-method-arity-ignore-length/options.json
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/class-method-arity-ignore-length/output.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/class-method-arity/input.js
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/class-method-arity/options.json
  packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/class-method-arity/output.js
Labels: PR: Bug Fix :bug:, Spec: Async Functions

#17260 Include Babel 8 in coverage report
  .github/workflows/ci.yml
  codecov.yml
Labels: area: tests, repo automation :robot:

#17266 Update Yarn to 4.9.1
  .yarn/releases/yarn-4.3.1.cjs
  .yarn/releases/yarn-4.9.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: PR: Dependency ⬆️

#17265 [babel 8] Drop CJS support from `@babel/parser`
  Gulpfile.mjs
  packages/babel-parser/index.cjs
  packages/babel-parser/package.json
  yarn.config.cjs
Labels: PR: Breaking Change :boom:

#17261 [babel 8] Remove unnecessary CJS ESM wrapper
  .github/workflows/e2e-tests-breaking-esm.yml
  packages/babel-core/.npmignore
  packages/babel-core/cjs-proxy-dev.cjs
  packages/babel-core/cjs-proxy.cjs
  packages/babel-core/package.json
  packages/babel-core/src/index.ts
  packages/babel-core/test/api.js
  packages/babel-core/test/esm-cjs-integration.js
  packages/babel-core/test/fixtures/esm-cjs-integration/eager-plugin-as-string.cjs
  packages/babel-core/test/fixtures/esm-cjs-integration/eager-plugin-required.cjs
  packages/babel-core/test/fixtures/esm-cjs-integration/lazy-plugin-as-string.cjs
  packages/babel-core/test/fixtures/esm-cjs-integration/lazy-plugin-required.cjs
  packages/babel-core/test/fixtures/esm-cjs-integration/plugins/eager.cjs
  packages/babel-core/test/fixtures/esm-cjs-integration/plugins/lazy.cjs
  packages/babel-core/test/fixtures/esm-cjs-integration/transform-sync.cjs
  scripts/generators/npm-ignore.js
  yarn.config.cjs
Labels: PR: Internal (next major) :house:

#17273 fix invalid gulp watch usage
  Gulpfile.mjs
Labels: PR: Fixes failing main

#17254 Allow `using of` as lexical declaration within for
  packages/babel-parser/src/parser/statement.ts
  packages/babel-parser/src/tokenizer/index.ts
  packages/babel-parser/test/fixtures/experimental/_no-plugin/explicit-resource-management-for-variable-declaration/input.js
  packages/babel-parser/test/fixtures/experimental/_no-plugin/explicit-resource-management-for-variable-declaration/options.json
  packages/babel-parser/test/fixtures/experimental/explicit-resource-management/invalid-for-using-of-equal-equal/input.js
  packages/babel-parser/test/fixtures/experimental/explicit-resource-management/invalid-for-using-of-equal-equal/options.json
  packages/babel-parser/test/fixtures/experimental/explicit-resource-management/invalid-for-using-of-no-initializer/input.js
  packages/babel-parser/test/fixtures/experimental/explicit-resource-management/invalid-for-using-of-no-initializer/output.json
  packages/babel-parser/test/fixtures/experimental/explicit-resource-management/valid-for-using-declaration-binding-of/input.js
  packages/babel-parser/test/fixtures/experimental/explicit-resource-management/valid-for-using-declaration-binding-of/output.json
  packages/babel-parser/test/fixtures/experimental/explicit-resource-management/valid-using-binding-of/input.js
  packages/babel-parser/test/fixtures/experimental/explicit-resource-management/valid-using-binding-of/output.json
  packages/babel-parser/test/fixtures/typescript/explicit-resource-management/options.json
  packages/babel-parser/test/fixtures/typescript/explicit-resource-management/valid-for-using-declaration-binding-of/input.js
  packages/babel-parser/test/fixtures/typescript/explicit-resource-management/valid-for-using-declaration-binding-of/output.json
Labels: PR: Spec Compliance :eyeglasses:, Spec: Explicit Resource Management

#17275 Rebuild Makefile.mjs
  Makefile.mjs
Labels: PR: Fixes failing main

#17279 Bumped picocolors version to prevent webpack warnings
  packages/babel-code-frame/package.json
  yarn.lock
Labels: PR: Dependency ⬆️
