Repository babel/babel, pull requests merged in 2025-09, with the labels that each got.

#17494 Type checking babel-types scripts
  .github/workflows/release.yml
  Gulpfile.mjs
  Makefile.mjs
  Makefile.source.mjs
  eslint.config.mjs
  lib/libdom-minimal.d.ts
  packages/babel-types/scripts/generators/asserts.ts
  packages/babel-types/scripts/generators/ast-types.ts
  packages/babel-types/scripts/generators/builders.ts
  packages/babel-types/scripts/generators/constants.ts
  packages/babel-types/scripts/generators/docs.ts
  packages/babel-types/scripts/generators/flow.ts
  packages/babel-types/scripts/generators/typescript-legacy.ts
  packages/babel-types/scripts/generators/validators.ts
  packages/babel-types/scripts/utils/fieldHelpers.ts
  packages/babel-types/scripts/utils/formatBuilderName.js
  packages/babel-types/scripts/utils/formatBuilderName.ts
  packages/babel-types/scripts/utils/stringifyValidator.js
  packages/babel-types/scripts/utils/stringifyValidator.ts
  packages/babel-types/scripts/utils/toFunctionName.js
  packages/babel-types/src/ast-types/generated/index.ts
  packages/babel-types/src/definitions/core.ts
  packages/babel-types/src/definitions/experimental.ts
  packages/babel-types/src/definitions/typescript.ts
  packages/babel-types/src/definitions/utils.ts
  packages/babel-types/tsconfig.json
  scripts/generators/tsconfig.js
Labels: PR: Internal :house:, pkg: types

#17504 fix: ensure scope.push register in anonymous fn
  packages/babel-traverse/src/scope/index.ts
  packages/babel-traverse/test/scope.js
Labels: PR: Bug Fix :bug:

#17503 Fix `JSXIdentifier` handling in `isReferencedIdentifier`
  packages/babel-helper-create-class-features-plugin/src/decorators.ts
  packages/babel-helper-member-expression-to-functions/src/util.ts
  packages/babel-plugin-transform-block-scoping/src/validation.ts
  packages/babel-plugin-transform-optional-chaining/src/util.ts
  packages/babel-traverse/scripts/generators/asserts.js
  packages/babel-traverse/scripts/generators/validators.js
  packages/babel-traverse/src/path/generated/asserts.d.ts
  packages/babel-traverse/src/path/generated/validators.d.ts
  packages/babel-traverse/src/path/introspection.ts
  packages/babel-traverse/src/path/lib/virtual-types-validator.ts
  packages/babel-traverse/src/scope/index.ts
  packages/babel-traverse/test/path/virtual-types-validators.js
  packages/babel-traverse/test/path/virtual-validators.js
  packages/babel-types/scripts/generators/validators.ts
  packages/babel-types/src/validators/generated/index.ts
Labels: PR: Bug Fix :bug:

#17501 fix: update identifier to unicode 17
  packages/babel-helper-validator-identifier/package.json
  packages/babel-helper-validator-identifier/scripts/generate-identifier-regex.cjs
  packages/babel-helper-validator-identifier/src/identifier.ts
  packages/babel-helper-validator-identifier/test/identifier.spec.js
  yarn.lock
Labels: PR: Spec Compliance :eyeglasses:

#17512 [babel 8] Update default `@babel/runtime` version
  packages/babel-plugin-transform-runtime/src/index.ts
  packages/babel-plugin-transform-runtime/test/fixtures/regression/17510/input.mjs
  packages/babel-plugin-transform-runtime/test/fixtures/regression/17510/options.json
  packages/babel-plugin-transform-runtime/test/fixtures/regression/17510/output.mjs
Labels: PR: Bug Fix (next major) :bug:

#17523 Run Prettier E2E test only on Babel 8
  .github/workflows/e2e-tests.yml
  scripts/integration-tests/e2e-prettier.sh
Labels: PR: Fixes failing main

#17526 chore: simplify parseArrayLike
  packages/babel-parser/src/parser/expression.ts
  packages/babel-parser/src/plugins/flow/index.ts
  packages/babel-parser/src/plugins/typescript/index.ts
Labels: pkg: parser

#17518 [Babel 8] Use `t.traverseFast` to replace some `path.traverse`
  packages/babel-helper-create-class-features-plugin/src/decorators.ts
  packages/babel-plugin-bugfix-firefox-class-in-computed-class-key/src/index.ts
  packages/babel-plugin-transform-modules-systemjs/src/index.ts
  packages/babel-plugin-transform-typescript/src/index.ts
Labels: PR: Performance (next major) :running_woman:
